/* PARIAS — Acte II · ALYCIA DE CALLENSBOURG
 * ═══════════════════════════════════════════════════════════════════════
 * Dix étapes, du pack. Elle n'est jamais une récompense : leur lien vient de
 * leur puissance, de leur condition de Parias et de leur méfiance commune.
 *
 * Sa mécanique n'appartient qu'à elle : PLUS ON LUI DONNE, PLUS ELLE RECULE.
 * Protection, place à Karlsberg, ressources — chaque chose reçue monte sa
 * peur de dépendre. C'est la seule relation du jeu où la générosité est une
 * menace, et c'est écrit noir sur blanc dans son dossier.
 *
 * Le Prix des Parias ne s'applique pas : elle en est une.
 * ═══════════════════════════════════════════════════════════════════════ */

const ALYCIA = {

/* ══ L'OUVERTURE — ce qui reste de l'hiver ═══════════════════════════════ */
a2_ouverture:{
  lieu:"Cendrepont · la fonte · vingt-et-unième année après la Purge",
  titre:"Ce que l'hiver a laissé",
  texte:[
    { sobre:"L'hiver a duré quatre mois. Il crève en trois jours.",
      intense:"L'hiver a duré quatre mois. Il crève en trois jours, sous un vent du sud qui arrive un mardi et qui décroche la neige des toits pendant quarante heures.",
      extreme:"L'hiver a duré quatre mois. Il crève en trois jours, sous un vent du sud qui arrive un mardi et décroche la neige des toits pendant quarante heures d'affilée.\n\nEt le bourg se met à puer tout ce qu'il avait planqué dessous depuis Frimaire. La fosse de l'auberge. Deux chiens crevés derrière la forge. Le charnier à cochons qu'on n'a pas recouvert assez. Voilà l'odeur du printemps dans une vallée, et il n'y a pas une chanson dans ces provinces qui en parle." },
    () => a('as_cause_tombee')
      ? "L'assise de Chastel est repartie en Ventôse : onze chariots, deux pleins de registres, et une cause renvoyée qu'on instruira six mois de plus pour ne rien trouver."
      : "L'assise de Chastel est repartie en Ventôse. Onze chariots, une cause jugée, un homme pendu le jeudi.",
    () => {
      if(a('as_nom_donne')) return "§ Votre nom est à la ligne quatorze d'un rôle d'assise, en trois exemplaires, partis par trois routes. C'est fait. Ça ne se reprend pas.";
      if(a('as_prenom'))    return "§ *Yohan, homme d'armes, sans maison.* Un clerc de Chastel recopiera cette ligne un jour, et il s'arrêtera dessus, et il ira chercher un autre volume.";
      if(a('as_silence_rôle')) return "§ Il y a un blanc dans le rôle de l'assise d'hiver. Un homme de quarante-quatre ans sait exactement où, et il n'a rien dit à personne, ce qui coûte plus cher que de parler.";
      if(a('as_onde_salle')) return "§ Rien n'a été porté au rôle. Quarante personnes ont vu onze chandelles s'arrêter en même temps. Un rôle, ça se rature ; quarante personnes, non.";
      return "§ Personne n'a rien écrit sur vous. C'est ce que vous vouliez. Ça a marché et ça ne vaut rien.";
    },
    "Quatre mois dans un bourg de six cents culs-terreux qui ont parlé de vous à toutes les tables, tous les jours, en baissant la voix quand vous entriez et en la remontant avant que la porte soit refermée.",
    "Et quatre mois à retourner une phrase.",
    { sobre:"*Ce n'est pas Chastel qui a fait rayer Karlsberg.*",
      intense:"*Ce n'est pas Chastel qui a fait rayer Karlsberg. C'est quelqu'un de chez nous qui le leur a demandé, et Chastel a dit oui, parce qu'on dit toujours oui à ce genre de demande.*",
      extreme:"*Ce n'est pas Chastel qui a fait rayer Karlsberg. C'est quelqu'un de chez nous qui le leur a demandé, et Chastel a dit oui — on dit toujours oui à ce genre de demande, ça ne coûte rien et ça arrange tout le monde.*\n\nVotre mère a dit ça sur un pont il y a vingt ans, à une chose qui garde tout ce qu'on lui donne. Elle n'a pas donné le nom. Elle a réfléchi, sur ce pont, avec deux gosses dans une charrette de louage derrière elle, et elle a décidé de ne pas le donner pour que ses fils vivent vieux.\n\nElle s'est trompée d'un fils." },
    "Le col rouvre à la Saint-Marc. Vous avez un cheval, une épée, deux pistolets, quarante ans devant vous si personne ne s'en mêle, et une seule chose à faire de ces quarante ans.",
    "§ C'est ce matin-là qu'elle arrive.",
  ],
  effets:{ flags:['acte2'], faire:() => { A2(); ETAT.acte2.lieu = 'cendrepont'; },
           marque:"L'Acte II commence : quelqu'un, dans votre propre maison, a demandé qu'on la raye.",
           court:"La question" },
  suite:'al_mauvaise', libelleSuite:"Elle arrive" },

/* ══ 1-2 · UN NOM MURMURÉ · LA MAUVAISE FEMME ════════════════════════════ */
al_mauvaise:{
  qui:'alycia',
  lieu:"L'auberge du Héron · la salle basse",
  titre:"La mauvaise femme",
  texte:[
    "Elle a payé trois nuits d'avance, signé le registre *Mahaut de Serain, dame de compagnie*, et dîné seule au fond deux soirs de suite sans lever les yeux une fois.",
    { sobre:"Le troisième soir, elle s'assoit en face de vous.",
      intense:"Le troisième soir, elle traverse la salle et s'assoit en face de vous sans demander. Trente-trois ans. Une robe de bonne coupe et de mauvaise province, taillée pour qu'on ne la regarde pas — et qui échoue, parce que ce n'est pas la robe qu'on regarde.",
      extreme:"Le troisième soir elle traverse la salle basse et s'assoit en face de vous sans demander la permission, ce que personne ne fait dans une salle où il y a onze hommes et une seule femme.\n\nTrente-trois ans. Une robe de bonne coupe et de très mauvaise province, taillée exprès pour qu'on ne la regarde pas, et qui rate complètement son office — parce que ce n'est pas la robe qu'on regarde. Deux hommes du fond n'ont pas décroché depuis qu'elle est entrée. Elle le sait. Elle s'en sert : elle a choisi cette table parce que de là, ils sont derrière elle, et qu'un homme qui fixe un dos finit toujours par se lever." },
    "« On m'envoie vous proposer du travail. »",
    "« Quelle maison ? »",
    { sobre:"« Pas avant que vous ayez dit oui ou non. »",
      intense:"« Je ne le dirai pas avant que vous ayez dit oui ou non. C'est la condition. » Elle a un demi-sourire qui n'a rien d'aimable. « Et oui, elle est agaçante. Elle est faite pour. »",
      extreme:"« Je ne le dirai pas avant que vous ayez dit oui ou non. C'est la condition, elle n'est pas de moi, et je ne la discuterai pas. » Elle a un demi-sourire qui n'a strictement rien d'aimable. « Oui, elle est agaçante. Elle est faite pour l'être. Vous seriez surpris du nombre d'hommes d'armes qui vident leur sac entier rien que pour avoir le dernier mot sur une condition agaçante. »" },
    "§ Un homme vous a servi la même phrase cet hiver. Il fermait les portes avant de dire bonjour et il est mort depuis.",
    "« Le travail. »",
    "« À onze lieues d'ici, il y a une femme qui fait disparaître des gens. Sept en dix-huit mois. Que des hommes d'armes. Aucun corps, jamais, pas un doigt. »",
    "« Employés par qui ? »",
    { sobre:"« Des gens qui cherchent des Parias. »",
      intense:"« Des gens dont c'est le métier de trouver des Parias. » Elle ne baisse pas la voix d'un demi-ton. « Il y en a. Beaucoup plus qu'on ne croit. Ce n'est pas une confrérie, c'est un marché : tarif à la tête, payé au résultat, et le tarif a doublé en six ans. »",
      extreme:"« Des gens dont c'est le métier de trouver des Parias. » Elle ne baisse pas la voix d'un demi-ton, et deux têtes se tournent, et elle ne les regarde pas. « Il y en a. Beaucoup plus qu'on ne croit et pas du tout ceux qu'on croit. Ce n'est pas une confrérie de fanatiques, messire, c'est un marché — tarif à la tête, payé au résultat, plus une prime si on ramène de quoi identifier. Le tarif a doublé en six ans. Ça vous dira quelque chose sur ce qui reste en stock. »" },
    "« Et on veut qu'on l'arrête. »",
    "« On veut qu'on la crève. Trois cents couronnes. »",
    { sobre:"Elle pose les deux mains à plat sur la table.",
      intense:"Elle pose les deux mains à plat sur la table, doigts écartés, et elle attend en vous regardant droit — sans ciller, longtemps, jusqu'à ce que ce soit franchement désagréable.",
      extreme:"Elle pose les deux mains à plat sur la table, doigts écartés, et elle attend. Elle vous regarde droit dans les yeux sans ciller, très longtemps, jusqu'à ce que ce soit franchement désagréable et un peu au-delà — c'est un procédé, il est grossier, il marche sur à peu près tout le monde et elle ne se donne même pas la peine de le déguiser." },
    "§ « Alors ? »",
  ],
  choix:[
    { t:"« Non. »",
      detail:"Sans explication · sans négocier · sans demander qui paie",
      va:'al_non' },
    { t:"« Qui paie ? »",
      detail:"Elle a dit qu'elle ne le dirait pas · c'est exactement pour ça qu'on demande",
      va:'al_qui' },
    { t:"« Trois cents. Où est-elle ? »",
      detail:"Prendre le contrat · c'est une épreuve et vous ne savez pas encore que c'en est une",
      ferme:"Ferme : la version de cette rencontre où elle vous croit du premier coup",
      risque:"définitif", definitif:true, va:'al_oui' },
    { t:"« C'est vous. »",
      detail:"Deux mains à plat · trois nuits payées d'avance · une table qui met deux hommes dans son dos · Perception + intellect contre 12",
      risque:"calculé",
      test:{ carac:'perception', comp:'tactique', dc:12, manoeuvre:'lire_alycia',
             situation:() => (a('onde_sur_soi') ? 2 : 0) + (a('tr_karlsberg') ? 1 : 0) },
      degres:{ dominante:'al_devinee', couteuse:'al_devinee', echec:'al_rate' } },
  ],
},

al_non:{
  qui:'alycia',
  texte:[
    "« Non. »",
    "Elle attend la suite. Il n'y en a pas.",
    { sobre:"« Vous ne demandez rien ? »",
      intense:"« Vous ne demandez pas qui paie. Vous ne demandez pas ce qu'elle a fait. Vous ne demandez pas si trois cents se négocient — et ça se négocie, tout se négocie. »\n\n« Non. »\n\n« Pourquoi ? »\n\n« Parce que vous avez dit *des gens qui cherchent des Parias* en me regardant. »",
      extreme:"« Vous ne demandez pas qui paie. Vous ne demandez pas ce qu'elle a fait à ces sept-là. Vous ne demandez même pas si trois cents couronnes se négocient — et ça se négocie, messire, tout se négocie, il n'y a que les imbéciles et les prêtres pour croire le contraire. »\n\n« Non. »\n\n« Pourquoi ? »\n\n« Parce que vous avez dit *des gens dont c'est le métier de trouver des Parias* en me regardant droit dans les yeux. Et parce que vous avez posé les deux mains à plat sur la table avant de le dire. »" },
    "§ Quelque chose lâche dans sa figure et met un temps à se remettre en place.",
    { sobre:"« Vous auriez pu dire oui, y aller, et me tuer. »",
      intense:"« Vous auriez pu dire oui, prendre l'acompte, faire onze lieues et me couper la gorge dans mon sommeil pour trois cents couronnes. » Elle se penche. « Vous avez fait pire cet hiver pour moins cher. J'ai la liste. »",
      extreme:"« Vous auriez pu dire oui, prendre l'acompte, faire onze lieues et m'ouvrir la gorge pendant que je dors, pour trois cents couronnes et sans que personne au monde ne vous demande rien. » Elle se penche par-dessus la table, et elle sent la route et la sueur froide et rien d'autre — pas de parfum, ce qui est une décision. « Vous avez fait bien pire cet hiver pour bien moins cher. J'ai la liste, elle tient sur une page, et il y a deux lignes dessus dont vous ne vous vantez pas. »" },
    "« Probablement. »",
    "« Alors pourquoi non ? »",
    "Vous ne répondez pas. Il n'y a rien à répondre qui ne soit pas une déclaration, et elle le sait, et c'est très exactement pour ça qu'elle a posé la question.",
    { sobre:"Elle retourne les mains, paumes en l'air.",
      intense:"Elle retourne lentement les mains, paumes en l'air. Chez elle, ça veut manifestement dire quelque chose — et vous mettrez trois ans à comprendre quoi.",
      extreme:"Elle retourne lentement les deux mains, paumes en l'air, sur la table. Chez elle ça veut dire quelque chose ; vous mettrez trois ans à comprendre quoi, et quand vous comprendrez ce sera pire. Il y a quatre cicatrices parallèles sur l'intérieur du poignet gauche, anciennes, régulières. Elle ne les cache pas et elle ne les montre pas non plus." },
    "« Alycia. De Callensbourg, si vous tenez à la particule. Je n'y tiens pas : ils ont rayé Callensbourg six ans avant Karlsberg et il n'en reste pas assez pour porter une particule. »",
  ],
  effets:{ flags:['al_rencontree','al_bien_commence'],
           faire:() => bouger('alycia', { relation:4, confiance:5 }),
           exploit:{ eclat:2, temoins:'un', quoi:"vous avez refusé un contrat contre un Paria sans poser de question" },
           marque:"Alycia de Callensbourg s'est nommée. Vous aviez refusé de la chasser avant de savoir qui elle était.",
           court:"Alycia" },
  suite:'al_deux_predateurs', libelleSuite:"Elle reste assise" },

al_qui:{
  qui:'alycia',
  texte:[
    "« Qui paie ? »",
    "« J'ai dit que je ne le dirais pas. »",
    "« Et moi je ne dis rien avant de le savoir. On peut rester assis. »",
    { sobre:"On reste assis. Onze minutes.",
      intense:"On reste assis. Onze minutes, dans une salle qui se vide, avec deux chopes qui refroidissent et une aubergiste qui finit par renoncer à essuyer la même table.",
      extreme:"On reste assis. Onze minutes exactement, dans une salle basse qui se vide, deux chopes de bière tiède qui achèvent de tourner, une aubergiste qui essuie la même table quatre fois avant de renoncer et de sortir.\n\nOnze minutes de silence entre deux personnes qui ont décidé chacune de leur côté de ne pas parler la première, c'est très long. Ça vous laisse tout le temps de constater qu'elle ne s'ennuie pas une seconde, qu'elle ne joue pas avec ses doigts, qu'elle ne regarde pas ailleurs — et qu'elle prend un plaisir tout à fait visible à vous voir tenir." },
    { sobre:"C'est elle qui cède, et elle cède en riant, ce qui n'est pas céder.",
      intense:"C'est elle qui cède, et elle cède en riant à moitié, ce qui n'est pas céder du tout : c'est encaisser une bonne carte.",
      extreme:"C'est elle qui cède, et elle cède en riant à moitié — un son bas, court, franchement satisfait — ce qui n'est pas céder du tout. C'est ramasser une bonne carte et le faire savoir." },
    "« Personne ne paie. Il n'y a pas de contrat, pas de commanditaire, et la femme de onze lieues n'existe pas. »",
    "« Alors vous vendez quoi ? »",
    { sobre:"« Rien. J'achète. »",
      intense:"« Rien du tout. J'achète. » Elle retourne les mains, paumes en l'air. « J'achetais de savoir ce que vous feriez, et vous venez de me le vendre pour onze minutes de silence. C'est donné. »",
      extreme:"« Rien du tout, messire. J'achète. » Elle retourne lentement les mains, paumes en l'air. « J'achetais de savoir ce que vous feriez d'un contrat comme celui-là, et vous venez de me le vendre pour onze minutes de silence dans une auberge qui pue le suif. C'est donné. Les six autres m'ont coûté beaucoup plus cher et m'en ont dit beaucoup moins. »" },
    "§ « Alycia. De Callensbourg, si vous tenez à la particule — ils l'ont rayée six ans avant la vôtre. »",
  ],
  effets:{ flags:['al_rencontree'],
           faire:() => bouger('alycia', { relation:3, confiance:3 }),
           marque:"Alycia de Callensbourg vous a testé et vous ne l'avez ni crue ni démentie.",
           court:"Alycia" },
  suite:'al_deux_predateurs', libelleSuite:"Elle reste assise" },

al_oui:{
  qui:'alycia',
  texte:[
    "« Trois cents. Où est-elle ? »",
    { sobre:"Elle ne cille pas. Un lieu, une route, un délai.",
      intense:"Elle ne cille pas. Un lieu — un relais de bûcherons à onze lieues à l'est —, une route, neuf jours, et la moitié de l'acompte en pièces qu'elle sort d'une bourse déjà préparée.",
      extreme:"Elle ne cille pas d'un cil. Un lieu — un relais de bûcherons à onze lieues à l'est —, une route, un délai de neuf jours, et cent cinquante couronnes d'acompte en pièces comptées d'avance qu'elle sort d'une bourse manifestement préparée pour ce moment précis, ce qui devrait vous alerter et ne vous alerte pas.\n\nPuis elle se lève, vous souhaite bonne route d'une voix parfaitement égale, et monte se coucher." },
    "§ Vous faites onze lieues à l'est. Il n'y a pas de relais de bûcherons. Il n'y en a jamais eu.",
    "Il y a une clairière, un feu éteint depuis deux jours, et sur une souche, calée sous une pierre, une feuille avec quatre mots.",
    "*Vous avez dit oui.*",
    { sobre:"Vous restez debout devant cette souche un long moment.",
      intense:"Vous restez debout devant cette souche un temps considérable, avec cent cinquante couronnes dans la sacoche et l'envie très nette de mettre le feu à la clairière.",
      extreme:"Vous restez debout devant cette souche un temps considérable. Cent cinquante couronnes dans la sacoche, neuf jours de route pour rien, et l'envie parfaitement nette de mettre le feu à cette clairière et de regarder ça brûler jusqu'au soir.\n\nCe qui vous retient n'est pas la sagesse. C'est qu'elle a manifestement prévu que vous en auriez envie." },
    "À votre retour, la chambre de *Mahaut de Serain* est vide et payée, et l'aubergiste vous rend cent cinquante couronnes que la dame a laissées pour vous.",
    "§ Elle vous retrouvera. Ce n'est pas une menace, c'est une méthode, et vous venez d'être classé.",
  ],
  effets:{ flags:['al_rencontree','al_rate_test'],
           faire:() => bouger('alycia', { relation:1, confiance:-4 }), cout:{ moral:8 },
           marque:"Vous avez accepté un contrat contre un Paria. Elle vous a laissé quatre mots sur une souche.",
           court:"Vous avez dit oui" },
  suite:'al_deux_predateurs', libelleSuite:"Trois semaines plus tard" },

al_devinee:{
  qui:'alycia',
  texte:[
    "« C'est vous. »",
    "Silence.",
    { sobre:"« Qu'est-ce qui m'a trahie ? »",
      intense:"« Qu'est-ce qui m'a trahie ? » Elle demande ça sans une once d'inquiétude, avec un intérêt strictement professionnel, et elle tire une tablette de cire de sa manche — vraiment, une tablette de cire — pour noter.\n\n« Les mains à plat. »\n\n« Ah. » Elle note. « Merci. »",
      extreme:"« Qu'est-ce qui m'a trahie ? » Elle le demande sans la moindre inquiétude, avec un intérêt strictement professionnel, et elle tire de sa manche une petite tablette de cire — vraiment — pour noter la réponse.\n\n« Les deux mains à plat sur la table avant de parler. Personne ne fait ça. »\n\n« Ah. » Elle note. « Merci, c'est utile. Quinze ans que je le fais et pas un des six autres ne me l'avait dit. » Un temps. « Ils étaient plus bêtes que vous. Ne vous emballez pas : ce n'est pas un compliment, c'est un classement, et il compte cinq places. »" },
    "« Vous alliez me tuer ? »",
    { sobre:"« J'allais vous regarder décider. »",
      intense:"« J'allais vous regarder décider. Ce n'est pas la même chose et c'est nettement plus instructif. »",
      extreme:"« J'allais vous regarder décider. Ce n'est pas du tout la même chose et c'est infiniment plus instructif. On apprend tout d'un homme à la seconde où on lui propose de l'argent pour tuer quelqu'un qu'il n'a jamais vu : le temps qu'il met, les questions qu'il pose, et surtout l'ordre dans lequel il les pose. Vous, vous avez posé la bonne en troisième. Ça vous met loin devant. »" },
    "« Et si j'avais dit oui ? »",
    "« Onze lieues à l'est, une souche, quatre mots dessus. » Elle range la tablette. « Sept ont dit oui. Aucun n'a lu les quatre mots : ils cherchaient tous une femme dans les bois. »",
    "§ « Alycia. De Callensbourg. Rayée six ans avant la vôtre, il n'en reste pas de quoi porter une particule. »",
    "« Vous savez donc qui je suis. »",
    { sobre:"« Depuis Nivôse. »",
      intense:"« Depuis Nivôse. Toute la province sait ce qui s'est passé dans cette cour, messire. J'ai passé l'hiver à décider si vous étiez le meilleur ou le pire événement de ma vie. »",
      extreme:"« Depuis Nivôse. Toute la province sait ce qui s'est passé dans cette cour, on ne parle que de ça de Chastel aux Marches, et je n'ai eu qu'à écouter des charretiers pendant quatre mois. » Elle referme sa tablette. « J'ai passé l'hiver entier à décider si vous étiez le meilleur ou le pire événement de ma vie. Ça m'a occupée. Je n'avais pas été occupée depuis six ans. »" },
    "« Vous avez décidé ? »",
    "« Non. »",
  ],
  effets:{ flags:['al_rencontree','al_devinee'],
           faire:() => bouger('alycia', { relation:5, confiance:4, attirance:3 }),
           exploit:{ eclat:3, temoins:'un', quoi:"vous avez démasqué Alycia de Callensbourg à la troisième phrase" },
           marque:"Vous avez reconnu Alycia sous un faux nom. Elle l'a noté sur une tablette de cire.",
           court:"Les mains à plat" },
  suite:'al_deux_predateurs', libelleSuite:"Elle range la tablette" },

al_rate:{
  qui:'alycia',
  texte:[
    "Il y a quelque chose de faux et votre main n'arrive pas à se poser dessus.",
    "Vous posez trois questions : la maison, le délai, la preuve. Elle répond aux trois, vite, bien, avec le détail exact qu'aurait une dame de compagnie envoyée par une maison qui ne veut pas être nommée.",
    { sobre:"§ Trop bien. Vous ne le voyez pas ce soir-là.",
      intense:"§ Trop bien, et beaucoup trop vite. Vous ne le voyez pas ce soir-là ; vous le verrez trois semaines plus tard en repassant la scène, comme tout le monde.",
      extreme:"§ Trop bien, beaucoup trop vite, et sans une seule hésitation sur des détails qu'une vraie envoyée aurait eu à chercher. Vous ne le voyez pas ce soir-là. Vous le verrez trois semaines plus tard, à cheval, en repassant la scène pour la neuvième fois — exactement comme les six autres, ce qui est l'ennuyeux : sa méthode marche même sur ceux qui finissent par comprendre." },
    "Vous ne prenez pas le contrat, parce que quelque chose ne va pas. Vous ne le refusez pas non plus, parce que vous ne savez pas quoi.",
    "Elle part le lendemain matin sans vous saluer.",
    "L'aubergiste vous rend un papier qu'elle a laissé pour vous. Quatre mots.",
    "*Vous n'avez pas dit non.*",
  ],
  effets:{ flags:['al_rencontree','al_tiede'],
           faire:() => bouger('alycia', { relation:2, confiance:0 }),
           marque:"Alycia est partie en laissant quatre mots : « Vous n'avez pas dit non. »",
           court:"Pas dit non" },
  suite:'al_deux_predateurs', libelleSuite:"Trois semaines plus tard" },

};

/* ══ 3 · DEUX PRÉDATEURS ═════════════════════════════════════════════════ */
const ALYCIA_2 = {

al_deux_predateurs:{
  qui:'alycia',
  lieu:"Route Grise · à trois lieues au sud de Cendrepont",
  titre:"Deux prédateurs",
  melee:true,
  effets:{ melee:{ position:"sur la route", note:"Six · deux arcs" } },
  texte:[
    () => a('al_rate_test') || a('al_tiede')
      ? "Trois semaines plus tard, ils sont six sur la route du sud, et elle est déjà là."
      : "Ils sont six sur la route du sud, et elle est là avant vous.",
    { sobre:"Ce ne sont pas des brigands. Ça se voit à l'ordre dans lequel ils se placent.",
      intense:"Ce ne sont pas des brigands. Ça se voit à l'ordre dans lequel ils se placent : deux arcs sur le talus, trois en travers de la route à six pas d'écart, et un qui reste en arrière avec les chevaux et qui ne fera rien du tout. C'est une disposition. Quelqu'un la leur a apprise.",
      extreme:"Ce ne sont pas des brigands, et ça se voit à l'ordre dans lequel ils se placent : deux arcs sur le talus, trois en travers de la route à six pas d'écart — pas trois, pas huit : six —, et un en arrière avec les chevaux qui ne fera rien de la journée. C'est une disposition enseignée. Elle a un nom, elle s'apprend en quatre jours, et on l'enseigne à Mont-Draken." },
    "« Yohan de Karlsberg. »",
    "§ Trois mois. Il a fallu trois mois à une ligne de rôle d'assise pour arriver sur une route et se transformer en six hommes.",
    "Alycia sort du fossé à leur gauche, sans se presser, les mains vides.",
    "« Sept, en fait », dit-elle. « Vous en avez oublié une. »",
    { sobre:"Ce qu'elle fait ensuite ne ressemble pas à ce que vous faites.",
      intense:"Ce qu'elle fait ensuite ne ressemble à rien de ce que vous faites. Vous, l'Onde pousse : elle déplace, elle renverse, elle casse. La sienne **prend**. Les deux archers du talus cessent d'être des archers — pas frappés, pas jetés : arrêtés, comme on arrête une horloge, avec les cordes encore tendues et les yeux ouverts.",
      extreme:"Ce qu'elle fait ne ressemble à rien de ce que vous faites. Votre Onde pousse : elle déplace, renverse, casse. La sienne prend. Les deux archers du talus cessent d'être des archers — pas frappés, pas jetés : arrêtés, comme une horloge, corde encore tendue, yeux ouverts, et l'un des deux met quatre secondes à comprendre que sa poitrine ne bouge plus. Il ne tombe pas tout de suite. C'est ça, le pire : rien ne tombe tout de suite." },
    "Il reste quatre hommes, et l'un d'eux a lâché son épée sans s'en apercevoir.",
  ],
  choix:[
    { t:"Les quatre autres",
      detail:"Trois en travers de la route, un aux chevaux · Force + épées contre 10",
      risque:"dangereux",
      test:{ carac:'force', comp:'epees', dc:10, adversaire:'chasseurs', manoeuvre:'quatre', equipement:2,
             situation:2 },
      degres:{ dominante:'al_quatre_dom', couteuse:'al_quatre_cout', echec:'al_quatre_ko' } },
    { t:"« Arrêtez. » — à elle",
      detail:"Elle vient d'en arrêter deux · elle n'a pas fini · et vous voulez savoir qui les envoie",
      risque:"calculé",
      test:{ carac:'presence', comp:null, dc:11, manoeuvre:'arreter_alycia',
             situation:() => Math.floor(lien('alycia').confiance / 3) },
      degres:{ dominante:'al_arret_dom', couteuse:'al_arret_cout', echec:'al_quatre_ko' } },
    { t:"L'Onde, avec elle",
      detail:"Deux Parias sur une route, à découvert, devant quatre témoins qui vont mourir",
      ferme:"Ferme : toute possibilité qu'un des six reparte en pouvant raconter",
      risque:"définitif", definitif:true,
      test:{ carac:'volonte', comp:'onde', dc:9, manoeuvre:'onde_route', cout:{ concentration:25 } },
      degres:{ dominante:'al_onde_dom', couteuse:'al_onde_dom', echec:'al_quatre_ko' } },
  ],
},

al_quatre_dom:{
  melee:true,
  texte:[
    "Quatre hommes qui viennent de voir deux de leurs camarades s'arrêter debout ne sont plus quatre hommes : ce sont quatre personnes qui essaient de comprendre.",
    { sobre:"Ça prend moins de temps que ça n'en faudrait pour l'expliquer.",
      intense:"Ça prend moins de temps qu'il n'en faudrait pour l'expliquer. Le premier n'a pas remonté sa garde. Le deuxième la remonte trop haut. Le troisième est bon, et il faut trois passes, et il a le temps de dire quelque chose qui commence par *attends*.",
      extreme:"Ça prend moins de temps qu'il n'en faudrait pour l'expliquer. Le premier n'a pas remonté sa garde et il meurt sans avoir décidé de se battre. Le deuxième la remonte trop haut. Le troisième est bon — il faut trois passes, il pare correctement les deux premières, et il a le temps de commencer un mot qui commence par *attends* et qu'il ne finira pas." },
    "Le quatrième, celui des chevaux, ne bouge pas de la matinée. Il a dix-neuf ans et il est payé pour tenir des rênes.",
    "§ Alycia le regarde. Elle ne fait rien. Elle attend, et c'est à vous.",
  ],
  effets:{ flags:['al_quatre','al_gamin_vivant'], cout:{ endurance:14 },
           faire:() => bouger('alycia', { relation:2 }),
           exploit:{ eclat:5, temoins:'un', quoi:"vous avez défait quatre chasseurs de Parias sur une route" },
           meleeMaj:{ position:"debout", note:"Il reste le gamin aux chevaux" } },
  suite:'al_gamin', libelleSuite:"Le gamin" },

al_quatre_cout:{
  melee:true,
  texte:[
    "Ils sont quatre, ils ont peur, et des hommes qui ont peur se battent mal et longtemps, ce qui est la pire combinaison.",
    { sobre:"Le troisième vous ouvre le dessus du bras avant de tomber.",
      intense:"Le troisième est un homme d'une quarantaine d'années qui a manifestement fait ça toute sa vie, et il ne se bat pas mieux que les autres : il se bat plus longtemps. Il vous ouvre le dessus du bras droit sur cinq pouces avant de tomber, et il tombe en s'excusant, ce qui est une chose qu'on entend et qu'on ne rapporte jamais.",
      extreme:"Le troisième a une quarantaine d'années et il a fait ça toute sa vie. Il ne se bat pas mieux : il se bat plus longtemps. Il vous ouvre le dessus du bras droit sur cinq pouces, jusqu'au muscle, et quand il tombe il dit *pardon* — pas à vous, pas à personne, comme on le dit en bousculant quelqu'un dans une rue. C'est la chose que vous rapporterez de cette route et vous ne la raconterez à personne." },
    "Le quatrième, celui des chevaux, dix-neuf ans, n'a pas bougé.",
    "§ Alycia ne fait rien. Elle attend, et c'est à vous.",
  ],
  effets:{ flags:['al_quatre','al_gamin_vivant'], cout:{ endurance:16, vitalite:10 },
           blessure:{ id:'bras_a2', zone:"Bras droit", type:"ouvert sur cinq pouces",
                      gravite:2, douleur:2, saignement:2, fonction:['force','epees','armes_lourdes'],
                      cicatrice:"cinq pouces sur le dessus du bras, larges" },
           faire:() => bouger('alycia', { relation:2 }),
           exploit:{ eclat:5, temoins:'un', quoi:"vous avez défait quatre chasseurs de Parias" },
           meleeMaj:{ position:"debout, le bras ouvert", note:"Il reste le gamin aux chevaux" } },
  suite:'al_gamin', libelleSuite:"Le gamin" },

al_quatre_ko:{
  melee:true,
  texte:[
    "Vous entrez mal et ils sont quatre.",
    { sobre:"Vous êtes au sol au bout de quinze secondes. Elle finit.",
      intense:"Vous êtes au sol au bout de quinze secondes, avec un genou dans le dos et une lame qui cherche le défaut sous l'aisselle — et vous ne mourez pas, parce qu'elle finit.\n\nElle finit les quatre. Sans bouger de l'endroit où elle est.",
      extreme:"Vous êtes au sol en quinze secondes, un genou dans le dos, une lame qui cherche le défaut sous l'aisselle. Vous ne mourez pas parce qu'elle finit — les quatre, sans bouger d'un pas, sans lever la main plus haut que la hanche. Ils s'arrêtent l'un après l'autre, dans l'ordre, comme quatre horloges qu'on remonterait à l'envers, et le dernier a le temps de voir les trois autres." },
    "Vous vous relevez dans un silence de route de campagne, avec six hommes autour de vous dont aucun n'a été touché par une arme.",
    "§ « Vous n'avez pas eu à faire ça », dites-vous.",
    "« Non », dit Alycia. « J'ai eu à décider si je le faisais, ce qui n'est pas pareil, et j'ai mis deux secondes de plus que d'habitude. »",
    "« Pourquoi ? »",
    "« Parce que vous étiez en train de perdre et que je me suis demandé si c'était une raison suffisante. »",
    "Le gamin aux chevaux, dix-neuf ans, n'a pas bougé.",
  ],
  effets:{ flags:['al_quatre','al_gamin_vivant','al_sauve_par_elle'],
           cout:{ endurance:20, vitalite:14, moral:10 },
           faire:() => bouger('alycia', { relation:2, confiance:-1 }),
           meleeMaj:{ position:"debout, mal", note:"Six morts, aucun par une arme" } },
  suite:'al_gamin', libelleSuite:"Le gamin" },

al_arret_dom:{
  melee:true,
  texte:[
    "« Arrêtez. »",
    "Elle s'arrête. Ce n'est pas rien : une femme qui a passé dix-huit mois à faire disparaître des gens s'arrête au milieu, sur un mot, dit par quelqu'un qu'elle connaît depuis trois semaines.",
    "« Pourquoi ? »",
    "« Parce qu'ils savent qui les paie et que nous, non. »",
    { sobre:"Elle réfléchit. Deux secondes. C'est très long.",
      intense:"Elle réfléchit deux secondes, ce qui est très long quand quatre hommes armés attendent à six pas, et ce qui dit tout de la façon dont cette femme fonctionne : elle ne s'arrête pas parce qu'on le lui demande, elle s'arrête parce que l'argument est bon.",
      extreme:"Elle réfléchit deux secondes — très long, quand quatre hommes armés attendent à six pas et qu'aucun des deux camps ne sait s'il doit avancer. Et c'est là qu'on comprend comment cette femme fonctionne : elle ne s'arrête pas parce qu'on le lui demande. Elle s'arrête parce que l'argument est meilleur que le sien, et elle le concède sans que ça lui coûte quoi que ce soit." },
    "« D'accord. »",
    "Ce qui suit tient en une minute : quatre hommes, deux Parias, et personne qui ait envie de commencer.",
    "Ils partent. Ils laissent leurs deux camarades arrêtés debout sur le talus, parce qu'on ne charge pas ça sur un cheval et parce qu'ils ne savent pas ce que c'est.",
    "§ Le gamin aux chevaux, dix-neuf ans, reste. Il reste parce que les quatre autres sont partis en oubliant de lui dire de venir.",
  ],
  effets:{ flags:['al_quatre_partis','al_gamin_vivant','al_arret'],
           faire:() => bouger('alycia', { relation:3, confiance:4 }),
           exploit:{ eclat:3, temoins:'quelques', quoi:"quatre chasseurs de Parias sont repartis sur leurs jambes" },
           marque:"Vous avez arrêté Alycia au milieu. Elle s'est arrêtée parce que l'argument était bon.",
           court:"Elle s'arrête" },
  suite:'al_gamin', libelleSuite:"Le gamin" },

al_arret_cout:{
  melee:true,
  texte:[
    "« Arrêtez. »",
    "Elle ne s'arrête pas tout de suite. Elle s'arrête après le troisième, ce qui fait une différence considérable pour le troisième.",
    { sobre:"« J'étais lancée. »",
      intense:"« J'étais lancée », dit-elle, et c'est la première fois qu'elle a l'air de quelqu'un qui s'excuse de quelque chose. « Ça ne se coupe pas comme un robinet. Personne ne m'a jamais appris à couper. »",
      extreme:"« J'étais lancée. » C'est la première fois qu'elle a l'air de s'excuser de quoi que ce soit. « Ça ne se coupe pas comme un robinet, messire. Personne ne m'a jamais appris à couper — personne ne m'a jamais rien appris du tout, on m'a rayée à dix-sept ans et j'ai découvert ce que je faisais en le faisant sur quelqu'un. »" },
    "Il reste un homme debout sur les quatre, et le gamin aux chevaux.",
    "L'homme debout ne bouge pas, ne fuit pas et ne parle pas. Il regarde ses trois camarades.",
    "§ « Demandez-lui », dit Alycia. « C'est ce que vous vouliez. »",
  ],
  effets:{ flags:['al_un_debout','al_gamin_vivant','al_arret'],
           faire:() => bouger('alycia', { relation:2, confiance:2 }), cout:{ moral:5 },
           marque:"Elle s'est arrêtée après le troisième. Personne ne lui a jamais appris à couper.",
           court:"Elle était lancée" },
  suite:'al_gamin', libelleSuite:"Demander" },

al_onde_dom:{
  melee:true,
  texte:[
    "Il n'y a jamais eu deux Parias au même endroit devant vous. Il n'y en a probablement jamais eu deux au même endroit depuis dix-neuf ans, sauf sur des bûchers.",
    { sobre:"Ce n'est pas une addition. C'est autre chose.",
      intense:"Ce n'est pas une addition : deux Ondes sur la même route ne font pas le double. Elles font autre chose, et ni vous ni elle ne l'aviez prévu. Ce qui pousse rencontre ce qui prend, et sur quarante pas de Route Grise l'air devient une matière qu'on voit.",
      extreme:"Ce n'est pas une addition — deux Ondes sur la même route ne font pas le double, elles font autre chose. Ce qui pousse rencontre ce qui prend, et sur quarante pas l'air cesse d'être de l'air : il devient une matière qu'on voit, qui tremble comme au-dessus d'une forge, avec le goût de pièce de monnaie si fort qu'on l'a dans la bouche pendant deux jours. Les quatre hommes sont enlevés du sol de six pieds. Ils redescendent sans avoir été touchés." },
    "§ Aucun des six ne repartira pour le raconter. C'était le prix affiché et vous l'avez payé sans discuter.",
    "Quand ça s'arrête, vous êtes tous les deux à genoux sur une route vide, à quatre pas l'un de l'autre, en train de saigner du nez, et Alycia de Callensbourg rit.",
    "« Quinze ans », dit-elle. « Quinze ans que je fais ça seule. »",
    "Elle ne finit pas la phrase et il n'y a rien à finir.",
    "§ Le gamin aux chevaux, dix-neuf ans, a survécu parce qu'il était en arrière et que rien de ce qui vient de se passer n'a été dirigé.",
  ],
  effets:{ flags:['al_onde_ensemble','al_gamin_vivant','a2_onde_publique'],
           cout:{ endurance:20, vitalite:8 },
           faire:() => bouger('alycia', { relation:5, attirance:4, confiance:2 }),
           exploit:{ eclat:9, suspicion:20, temoins:'un',
                     quoi:"deux Parias ont vidé quarante pas de Route Grise" },
           marque:"Vous avez employé l'Onde avec Alycia. Elle a ri.", court:"À deux" },
  suite:'al_gamin', libelleSuite:"Le gamin" },

al_gamin:{
  qui:'alycia',
  titre:"Dix-neuf ans, aux chevaux",
  texte:[
    "Il s'appelle Ancel, il a dix-neuf ans, il est payé quatre sous par jour pour tenir six chevaux, et il n'a pas bougé depuis le début parce que personne ne lui a dit de bouger.",
    "Il sait deux choses et il les dit toutes les deux sans qu'on ait à insister, parce qu'il a dix-neuf ans.",
    "« On est partis de Mont-Draken il y a onze jours. »",
    "§ Mont-Draken. L'école où l'on forme des hommes à tuer ce qui n'est pas humain.",
    "« Et la deuxième chose ? »",
    "« Il y a une liste. »",
    "Il la sort de sa veste, parce qu'il la porte, parce que c'est le gamin aux chevaux et qu'on lui donne les papiers à porter.",
    { sobre:"Onze noms. Le vôtre est le neuvième.",
      intense:"Onze noms sur une feuille, à l'encre, dans une écriture de clerc militaire. Le vôtre est le neuvième et il est écrit en entier. Sept des onze sont barrés.",
      extreme:"Onze noms sur une feuille, à l'encre, dans une écriture de clerc militaire, avec une colonne de dates en marge. Le vôtre est le neuvième, écrit en entier, avec la mention *assise d'hiver, Cendrepont* et une date de Nivôse. Sept des onze sont barrés — pas raturés : barrés d'un trait propre, à la règle, avec une date de barrement." },
    "Alycia lit par-dessus votre épaule et elle ne dit rien pendant un long moment.",
    "Puis :",
    "« Le quatrième, c'est moi. Il n'est pas barré. »",
    "« Et les sept qui le sont ? »",
    "§ « Sept personnes qui avaient ce que nous avons, et dont je n'ai jamais entendu parler. »",
  ],
  effets:{ flags:['al_liste','a2_reseau_su','al_montdraken'],
           faire:() => { bouger('alycia', { relation:3, confiance:3 }); A2().pistes.sang = 1; },
           exploit:{ eclat:3, temoins:'un', quoi:"vous avez la liste de Mont-Draken" },
           marque:"Onze noms sur une liste de Mont-Draken. Sept barrés. Vous êtes le neuvième, Alycia la quatrième.",
           court:"Onze noms" },
  suite:'al_offre_karlsberg', libelleSuite:"Ce qu'elle propose" },

};
Object.assign(ALYCIA, ALYCIA_2);

/* ══ LA ROUTE ════════════════════════════════════════════════════════════ */
const ALYCIA_3 = {

al_offre_karlsberg:{
  qui:'alycia',
  titre:"Ce qu'elle propose",
  texte:[
    "Elle plie la liste et elle la met dans sa propre manche, ce qui est un geste et pas une distraction.",
    "« Sept barrés en six ans. Je n'ai connu aucun des sept. »",
    "« Vous connaissez les autres ? »",
    "« Certains. »",
    "§ *Certains.* C'est le premier mensonge par omission qu'elle vous fait, et vous le savez tous les deux, et aucun des deux ne relève.",
    "« Ce qui m'intéresse n'est pas la liste, messire. C'est comment on la fait. »",
    "« Comment on la fait ? »",
    { sobre:"« Comment on sait qui a ça. Il n'y a pas de signe. »",
      intense:"« Comment on sait qui a ça sous les côtes. Il n'y a pas de signe : les yeux clairs, c'est une bêtise, l'odeur de métal, c'en est une autre. On peut vivre soixante ans à côté d'un Paria sans rien voir. Alors comment est-ce qu'un homme de Mont-Draken écrit onze noms sur une feuille ? »",
      extreme:"« Comment on sait qui a ça sous les côtes. Il n'y a pas de signe — les yeux clairs, c'est une bêtise, l'odeur de métal, c'en est une autre, et on peut vivre soixante ans à côté d'un Paria sans rien voir du tout. Alors expliquez-moi comment un clerc militaire de Mont-Draken écrit onze noms sur une feuille, avec des dates en marge, sans jamais s'être trompé une seule fois. »" },
    "« Il a une liste plus vieille. »",
    "« Il a une liste plus vieille. » Elle hoche la tête. « Quelqu'un, il y a longtemps, a écrit qui avait ça et dans quelles maisons. Et ce quelqu'un-là, messire, n'était pas de Mont-Draken : c'était de chez nous. »",
    "§ *Quelqu'un de chez nous.* Elle vient de dire, sans le savoir, exactement les mots que Harn a rendus sur un pont.",
    "« Où sont les archives de Callensbourg ? »",
    "« Il n'y en a plus. J'ai vérifié à dix-sept ans, ce qui est le premier et le seul voyage que j'aie fait pour moi. » Un temps. « Où sont celles de Karlsberg ? »",
    "« Sous les ronces, à onze lieues de toute route entretenue. »",
    "« Vous y êtes allé ? »",
    "« Jamais. »",
    "« Depuis dix-neuf ans. »",
    "« Depuis dix-neuf ans. »",
    { sobre:"Elle ne demande pas pourquoi. Elle le sait.",
      intense:"Elle ne demande pas pourquoi et c'est le premier vrai cadeau qu'elle vous fait : n'importe qui d'autre aurait demandé pourquoi, et elle, elle a rayé Callensbourg de sa propre carte à dix-sept ans et elle n'y est jamais retournée non plus.",
      extreme:"Elle ne demande pas pourquoi, et c'est le premier vrai cadeau qu'elle vous fait. N'importe qui aurait demandé. Elle, elle a fait ce voyage-là à dix-sept ans, elle a trouvé ce qu'on trouve, et elle n'y est jamais retournée — et deux personnes qui ont chacune une adresse où elles ne vont pas n'ont pas besoin d'en parler." },
    "« Je vous y emmène. »",
    "« Ce n'est pas à vous de m'y emmener. »",
    "« Si. Vous ne savez pas y entrer et moi si : j'ai fait Callensbourg. Une maison rayée, ça se ferme d'une certaine façon, toujours la même, et il faut avoir vu la sienne pour savoir ouvrir celle d'un autre. »",
    "§ Trois semaines de route vers le nord-ouest, jusqu'aux Marches Grises.",
  ],
  effets:{ flags:['al_route_karlsberg'],
           faire:() => { A2().lieu = 'cendrepont'; },
           marque:"Alycia vous emmène à Karlsberg. Elle a fait Callensbourg à dix-sept ans.",
           court:"Elle m'y emmène" },
  suite:'al_route', libelleSuite:"Partir" },

al_route:{
  qui:'alycia',
  lieu:"Vers les Marches Grises · trois semaines",
  titre:"Trois semaines",
  texte:[
    { sobre:"Trois semaines à cheval avec quelqu'un, c'est plus long que ça n'en a l'air.",
      intense:"Trois semaines à cheval avec quelqu'un, c'est beaucoup plus long que ça n'en a l'air. On ne peut pas se taire trois semaines. On ne peut pas non plus parler trois semaines. On finit donc par faire ce que font tous les gens qui voyagent ensemble : on parle des heures certains jours et on ne s'adresse pas la parole pendant deux jours entiers, et les deux comptent.",
      extreme:"Trois semaines à cheval avec quelqu'un est beaucoup plus long que ça n'en a l'air. On ne peut pas se taire trois semaines ; on ne peut pas parler trois semaines. On fait donc ce que font tous les gens qui voyagent : on parle pendant des heures certains jours, on ne s'adresse pas la parole pendant deux jours entiers, et les deux comptent autant. On apprend aussi comment l'autre dort, ce qu'il fait de ses mains quand il ne pense à rien, et s'il se retourne quand un cheval bouge la nuit." },
    "Elle a trente-trois ans. Elle a été rayée à dix-sept, ce qui veut dire qu'elle a eu une enfance entière avec un nom, contrairement à vous.",
    "§ Elle est infiniment plus douée que vous et elle n'a eu personne pour le lui apprendre non plus.",
    "Il y a trois choses qu'on peut faire de trois semaines, et on ne peut pas faire les trois.",
  ],
  choix:[
    { t:"Lui apprendre à couper",
      si:() => a('al_arret') || a('al_onde_ensemble') || a('al_sauve_par_elle'),
      detail:"Personne ne lui a appris à s'arrêter · vous, on ne vous a rien appris non plus, mais vous vous êtes arrêté",
      va:'al_route_couper' },
    { t:"Lui demander Callensbourg",
      detail:"Ce qu'elle a trouvé à dix-sept ans · elle n'en a jamais parlé à personne",
      va:'al_route_callensbourg' },
    { t:"Ne rien demander du tout",
      detail:"Trois semaines de route, de feux, de pluie et de silence · et ce que ça vaut",
      va:'al_route_silence' },
    { t:"Lui dire pour votre mère",
      si:() => a('tr_mere'),
      detail:"Le pont, la charrette de louage, deux enfants, et une phrase rendue entière",
      ferme:"Ferme : le fait d'être le seul au monde à savoir ça",
      risque:"définitif", definitif:true, va:'al_route_mere' },
  ],
},

al_route_couper:{
  qui:'alycia',
  texte:[
    "« Personne ne vous a appris à couper. »",
    "« Personne ne m'a rien appris du tout. »",
    "« Moi non plus. Mais je me suis arrêté. »",
    "« Quand ? »",
    "§ Vous lui racontez le gué. La wyverne, ou le rond de craie, ou une salle basse pleine de gens — selon ce que vous avez fait de cette année-là — et surtout le moment précis où ça part et où l'on décide que ça s'arrête là.",
    { sobre:"Ce n'est pas une leçon. Il n'y a rien à enseigner.",
      intense:"Ce n'est pas une leçon : il n'y a rien à enseigner, aucun geste, aucun mot, aucune méthode. Il y a deux personnes assises devant un feu qui décrivent chacune une sensation à laquelle personne n'a jamais donné de nom, et qui découvrent au bout d'une heure que ce n'est pas la même chez les deux.",
      extreme:"Ce n'est pas une leçon : il n'y a rien à enseigner, aucun geste, aucune méthode, aucun mot qui existe. Il y a deux personnes devant un feu qui décrivent chacune une sensation à laquelle personne n'a jamais donné de nom — et qui découvrent, au bout d'une heure, que ce n'est pas la même chez les deux. Chez vous ça monte du plexus et ça sort. Chez elle ça descend de la nuque et ça se referme. Ce sont deux choses différentes qui portent le même nom depuis mille ans." },
    "Elle essaie, trois soirs de suite, sur rien — sur une flamme, sur un caillou, sur un oiseau qu'elle relâche.",
    "Le quatrième soir, elle arrête une flamme et la relâche.",
    "Elle ne dit rien du tout. Elle regarde le feu reprendre pendant une heure.",
    "§ Vous venez de lui donner quelque chose, et ce n'est pas rien, et elle le sait.",
    "C'est aussi la première fois qu'elle vous doit quelque chose, et ça, c'est autre chose.",
  ],
  effets:{ flags:['al_apprend_couper'],
           faire:() => bouger('alycia', { relation:4, confiance:5, attirance:2, peur:4 }),
           exploit:{ eclat:2, temoins:'aucun', quoi:"vous avez appris à quelqu'un à s'arrêter" },
           marque:"Vous avez appris à Alycia à couper. Elle vous doit quelque chose et ça la gêne.",
           court:"Couper" },
  suite:'kar_arrivee', libelleSuite:"Les Marches Grises" },

al_route_callensbourg:{
  qui:'alycia',
  texte:[
    "« Qu'est-ce que vous avez trouvé, à dix-sept ans ? »",
    "Elle met deux jours à répondre. Pas par refus : elle dit *plus tard* le premier soir, et *pas encore* le deuxième, et le troisième elle répond au milieu d'une conversation sur autre chose.",
    { sobre:"« Une ferme. »",
      intense:"« Une ferme. » Elle tient les rênes d'une main. « Ils n'avaient pas brûlé Callensbourg. Ils avaient brûlé les registres, gratté les pierres, rebaptisé le hameau, et ils avaient **vendu**. Il y avait une ferme dessus. Des gens dedans. Des enfants. »",
      extreme:"« Une ferme. » Elle tient les rênes d'une seule main et elle regarde la route. « Ils n'avaient pas brûlé Callensbourg : ils avaient brûlé les registres, gratté les pierres, rebaptisé le hameau et **vendu**. Il y avait une ferme dessus quand j'y suis arrivée. Des gens dedans, une bonne famille, six vaches, et trois enfants qui jouaient dans ce qui avait été la cour où mon père m'apprenait à monter. »" },
    "« Qu'est-ce que vous avez fait ? »",
    "« J'ai demandé de l'eau. On m'en a donné. J'ai bu, j'ai remercié, et je suis repartie. »",
    "Un temps.",
    "« J'avais dix-sept ans et je pouvais arrêter les six d'un coup. Je l'ai su là, exactement là, en buvant l'eau : que je pouvais et que je n'allais pas. »",
    "§ « C'est le seul jour de ma vie dont je sois sûre d'avoir eu raison. Tout le reste, je le repasse. »",
    "Elle ne dit rien pendant le reste de l'après-midi et vous ne demandez rien de plus.",
  ],
  effets:{ flags:['al_callensbourg'],
           faire:() => bouger('alycia', { relation:3, confiance:6 }),
           marque:"Callensbourg a été vendue, pas brûlée. Elle y a bu de l'eau à dix-sept ans et elle est repartie.",
           court:"Callensbourg" },
  suite:'kar_arrivee', libelleSuite:"Les Marches Grises" },

al_route_silence:{
  qui:'alycia',
  texte:[
    "Vous ne demandez rien.",
    { sobre:"Trois semaines. Il pleut onze jours sur vingt et un.",
      intense:"Trois semaines. Il pleut onze jours sur vingt et un, ce qui est normal au printemps dans les Marches, et deux personnes qui font du feu sous la pluie tous les soirs finissent par se répartir les tâches sans en avoir parlé : elle fait le feu, vous faites l'abri, et ni l'un ni l'autre ne sait à quel moment ça s'est décidé.",
      extreme:"Trois semaines, et il pleut onze jours sur vingt et un. Deux personnes qui font du feu sous la pluie tous les soirs finissent par se répartir les tâches sans jamais en avoir parlé : elle fait le feu — elle est meilleure, elle a une méthode avec de l'écorce de bouleau —, vous faites l'abri, et aucun des deux ne sait à quel moment ça s'est décidé. C'est ce genre de choses qui construit quelque chose entre deux personnes, et pas les conversations." },
    "§ Elle ne demande rien non plus. C'est peut-être le point commun le plus solide entre vous et il ne se dit pas.",
    "Le dix-neuvième soir, elle parle la première, sans raison, en regardant le feu.",
    "« Vous êtes le premier depuis quinze ans avec qui je n'ai pas eu à décider quoi cacher. »",
    "Vous ne répondez pas. Il n'y a rien à répondre et elle n'attend rien.",
    "Le lendemain, on voit les Marches Grises depuis une crête.",
  ],
  effets:{ flags:['al_silence'],
           faire:() => bouger('alycia', { relation:3, confiance:3, attirance:4 }),
           marque:"Trois semaines sans rien demander. Le dix-neuvième soir, elle a parlé la première.",
           court:"Le dix-neuvième soir" },
  suite:'kar_arrivee', libelleSuite:"Les Marches Grises" },

al_route_mere:{
  qui:'alycia',
  texte:[
    "Vous lui racontez le pont.",
    "Harn, deux cent onze ans, assis sur un parapet, les pieds vers l'amont. Une femme qui passe avec deux enfants et une charrette de louage il y a vingt ans. Et une phrase rendue entière, avec la voix, parce que ce qu'il garde il le garde entier.",
    "*Ils avaient l'ordonnance. Elle était signée du bas de la maison, pas du haut.*",
    { sobre:"Elle arrête son cheval au milieu de la route.",
      intense:"Elle arrête son cheval au milieu de la route, ce qu'elle n'a pas fait une fois en douze jours, et elle reste immobile assez longtemps pour que le vôtre s'impatiente.",
      extreme:"Elle arrête son cheval au milieu de la route — ce qu'elle n'a pas fait une seule fois en douze jours — et elle reste immobile assez longtemps pour que le vôtre s'impatiente et cherche l'herbe du bas-côté. Quand elle parle enfin, sa voix a changé de registre, et c'est la première fois." },
    "« Redites-le. »",
    "Vous le redites.",
    "« *Du bas de la maison.* »",
    "« Oui. »",
    "« Callensbourg aussi. »",
    "§ Elle le dit sans une hésitation, comme on constate qu'il pleut.",
    "« Comment le savez-vous ? »",
    "« Je ne le savais pas. Je viens de le savoir, à l'instant, en vous écoutant, parce que ça explique une chose que je traîne depuis quinze ans et que je n'avais jamais réussi à poser. »",
    "« Laquelle ? »",
    "« Ils sont arrivés la nuit. Ils sont entrés par la porte des cuisines, qui était la seule qu'on ne barrait pas, et ils savaient qu'on ne la barrait pas. » Elle remet son cheval en marche. « J'avais dix-sept ans et j'ai passé quinze ans à me dire qu'ils avaient eu de la chance. »",
    "« Vous avez une idée de qui ? »",
    "« Non. Et maintenant j'en ai une liste. »",
  ],
  effets:{ flags:['al_mere','al_callensbourg_dedans'],
           faire:() => { bouger('alycia', { relation:5, confiance:8, attirance:3 }); A2().pistes.sang = 2; },
           exploit:{ eclat:3, temoins:'aucun', quoi:"vous avez donné à quelqu'un la clef de sa propre maison" },
           marque:"Callensbourg aussi est tombée de l'intérieur. Ils sont entrés par la porte des cuisines.",
           court:"La porte des cuisines" },
  suite:'kar_arrivee', libelleSuite:"Les Marches Grises" },

};
Object.assign(ALYCIA, ALYCIA_3);
enregistrerScenes(ALYCIA);
