/* PARIAS — Acte II · KARLSBERG
 * ═══════════════════════════════════════════════════════════════════════
 * D'après V7_KAR_003 — Les Loups sous la cendre.
 *
 * Ce n'est pas un chantier et ce ne sera jamais un chantier. C'est une
 * adresse où l'on retourne pour comprendre, et ce qu'on y trouve renvoie
 * ailleurs — ce qui donne le voyage.
 *
 * Et c'est le seul endroit du jeu où lever une bannière est une décision
 * CONTRE quelqu'un : rassembler les Parias derrière un mur, c'est les rendre
 * tuables en un seul endroit. Alycia le dit, et elle a raison.
 * ═══════════════════════════════════════════════════════════════════════ */

const KARLS = {

kar_arrivee:{
  qui:'alycia',
  lieu:"Les Marches Grises · Karlsberg · aube grise",
  titre:"Onze lieues de toute route entretenue",
  texte:[
    { sobre:"On ne voit rien avant d'être dedans. C'est ça, une maison rayée.",
      intense:"On ne voit rien avant d'être dedans, et c'est exactement ça, une maison rayée : pas des ruines sur une hauteur, pas une silhouette qu'on aperçoit de loin. Vingt ans de ronces, de frênes de vingt pieds poussés dans les cours, et un chemin d'accès que personne n'entretient depuis qu'il ne mène plus nulle part.",
      extreme:"On ne voit rien avant d'être dedans. C'est ça, une maison rayée : pas des ruines sur une hauteur, pas de silhouette qu'on aperçoit à trois lieues. Vingt ans de ronces, des frênes de vingt pieds poussés dans les cours, et un chemin d'accès que personne n'entretient depuis qu'il ne mène plus nulle part. On marche dessus une demi-heure avant de comprendre qu'on marche dessus, et ce qui vous le fait comprendre est bête : le sol est plat sur trois pieds de large, régulièrement, et rien n'est plat dans une forêt." },
    "Sept cents personnes vivaient là il y a dix-neuf ans.",
    "§ Vous en avez neuf, vous. Neuf ans, une odeur de buis coupé, et une servante dont vous ne retrouvez plus le nom.",
    "Alycia descend de cheval la première et elle ne dit rien pendant un quart d'heure. Elle a fait ça une fois, à dix-sept ans, chez elle, et elle sait ce que c'est.",
    { sobre:"Sous les ronces, la pierre porte encore la trace d'un loup noir.",
      intense:"Ce qui reste debout, c'est la façade nord et l'escalier des cuisines. Le reste est de la pierre couchée sous vingt ans de végétation. Et au bas de la façade nord, sous les ronces, à hauteur de main, la pierre porte encore la trace d'un loup.",
      extreme:"Ce qui reste debout : la façade nord sur quarante pieds, l'escalier des cuisines, et une portion de voûte qui n'a pas de raison d'être encore là. Le reste est de la pierre couchée sous vingt ans de ronces, de sureau et d'orties d'homme. Et au bas de la façade nord, à hauteur de main, sous une couche de mousse qu'on retire d'un revers de manche, la pierre porte un loup — le même que sur une borne d'arpentage, de profil, la gueule fermée, encadré de deux traits verticaux." },
    "Yohan l'effleure et la poussière tombe d'un seul coup, comme si la porte avait retenu son souffle pendant une génération.",
    "Alycia observe la marque. Le sourire qu'elle portait sur la route a disparu.",
    "« Si tu ouvres », dit-elle — et c'est la première fois qu'elle vous tutoie — « tu ne visiteras pas seulement des ruines. Tu annonceras à ceux qui savent écouter que quelque chose est revenu. »",
  ],
  effets:{ flags:['kar_arrive'], faire:() => { A2().lieu = 'karlsberg'; },
           marque:"Vous êtes à Karlsberg. Il reste la façade nord, l'escalier des cuisines, et un loup sur une pierre.",
           court:"Karlsberg" },
  suite:'kar_porte', libelleSuite:"La porte ensevelie" },

kar_porte:{
  qui:'alycia',
  titre:"La porte ensevelie",
  texte:[
    "Ce n'est pas une porte : c'est un linteau et deux montants sous six pieds de ronces, et derrière, de la terre.",
    "Il faut trois heures pour dégager, à deux, avec ce qu'on a.",
    { sobre:"Derrière la terre, il y a une pierre plate avec un creux au milieu.",
      intense:"Derrière six pieds de terre, il y a une dalle plate, et au milieu de la dalle un creux de la taille d'une paume, poli, qui n'a pas été fait par le temps.",
      extreme:"Derrière six pieds de terre, une dalle de granite gris et, au milieu, un creux de la taille exacte d'une paume d'homme adulte — poli, régulier, avec un très léger bourrelet sur le pourtour. Ce n'est pas de l'usure : c'est taillé. Quelqu'un a taillé ça en sachant à quoi ça servirait, et il y a autour, à un pouce du bord, quatre entailles qui ne veulent rien dire pour vous et qui font pâlir Alycia." },
    "« Callensbourg avait la même », dit-elle. « Pas au même endroit. Sur la cave à sel, sous l'escalier. »",
    "« Vous l'avez ouverte ? »",
    "« Non. » Un temps. « J'avais dix-sept ans et j'étais seule, et je ne savais pas ce qu'il y avait derrière. »",
    "§ Elle sait maintenant. Vous le voyez à la façon dont elle regarde le creux.",
  ],
  choix:[
    { t:"Poser la paume dans le creux",
      detail:"C'est fait pour ça · c'est fait pour la vôtre · et ça se verra",
      ferme:"Ferme : toute version où Karlsberg reste une rumeur",
      risque:"définitif", definitif:true, va:'kar_paume' },
    { t:"Chercher une autre entrée",
      detail:"Sans sang, sans Onde, avec des mains et du temps · Perception + intellect contre 11",
      risque:"prudent",
      test:{ carac:'perception', comp:'tactique', dc:11, manoeuvre:'entree',
             situation:() => a('al_callensbourg') ? 2 : 0 },
      degres:{ dominante:'kar_autre_dom', couteuse:'kar_autre_cout', echec:'kar_autre_ko' } },
    { t:"Demander à Alycia ce qu'elle sait vraiment de cette porte",
      si:() => !a('kar_demande'),
      detail:"Elle a dit « pas au même endroit » · elle sait donc où était la sienne, et pourquoi",
      va:'kar_demande' },
    { t:"« Les Karlsberg sont morts. On repart. »",
      detail:"Onze lieues de retour · et une question qui reste sans réponse",
      ferme:"Ferme : les archives, le registre, et tout ce qui est derrière cette dalle",
      risque:"définitif", definitif:true, va:'kar_repart' },
  ],
},

kar_demande:{
  qui:'alycia',
  texte:[
    "« Qu'est-ce que vous savez de cette porte ? »",
    "Elle ne répond pas tout de suite, et quand elle répond elle répond à une autre question, ce qui est sa façon de dire la vérité.",
    { sobre:"« Il y en a une dans chaque maison qui avait ça. »",
      intense:"« Il y en a une dans chaque maison qui avait ça sous les côtes. Une par maison, jamais deux, toujours cachée, et toujours sur une paume. » Elle passe le pouce sur le bord du creux. « Ce ne sont pas des maisons qui avaient un pouvoir, messire. Ce sont des maisons qui gardaient quelque chose. »",
      extreme:"« Il y en a une dans chaque maison qui avait ça sous les côtes. Une par maison, jamais deux, toujours cachée, toujours ouverte à la paume. » Elle passe le pouce sur le bourrelet du creux, dans le sens du polissage, comme un tailleur de pierre lit une taille. « Ce ne sont pas des maisons qui avaient un pouvoir. Ce sont des maisons à qui l'on avait confié quelque chose, et je crois qu'on ne nous l'a jamais dit parce qu'on est morts avant d'avoir l'âge de l'apprendre. »" },
    "« Confié par qui ? »",
    "« Aucune idée. »",
    "« Vous mentez. »",
    "« Non. » Elle vous regarde. « Je devine, et je ne dirai pas une devinette dans une ruine, parce que si je me trompe vous la garderez vingt ans. »",
    "§ Les quatre entailles autour du creux ne sont pas humaines. Elles sont trop régulières et trop fines, et elles ont été faites d'un seul geste chacune.",
    "« Les entailles, en revanche, je peux vous les dire. Ce n'est pas de la taille de pierre. »",
    "« C'est quoi ? »",
    "« C'est de l'écriture. Et je ne sais pas la lire, mais je sais à quoi ressemblent les lettres humaines et à quoi ressemblent les autres. »",
  ],
  effets:{ flags:['kar_demande','kar_sait_confie','a2_indice_elfe'],
           faire:() => { bouger('alycia', { confiance:3 }); A2().pistes.onde = 1; },
           marque:"Une porte à paume par maison de Paria. Et quatre entailles autour, qui ne sont pas de l'écriture humaine.",
           court:"Les entailles" },
  suite:'kar_porte', libelleSuite:"La dalle" },

kar_paume:{
  qui:'alycia',
  titre:"La paume",
  texte:[
    "Vous posez la paume dans le creux. Il est à la bonne taille et il l'est de façon désagréable.",
    { sobre:"Rien pendant trois secondes. Puis la dalle descend.",
      intense:"Rien pendant trois secondes. Puis la pierre devient tiède sous la main — pas chaude : tiède, comme une pierre qu'on aurait quittée il y a une minute — et la dalle descend de trois pouces et coulisse sur la gauche, sans un bruit, sur un mécanisme qui n'a pas bougé depuis dix-neuf ans et qui ne grince pas.",
      extreme:"Rien pendant trois secondes. Puis la pierre devient tiède sous la paume — pas chaude, tiède, exactement comme une pierre qu'on aurait quittée il y a une minute — et l'air prend son goût de pièce de monnaie sous la langue. La dalle descend de trois pouces, coulisse sur la gauche sans un bruit, sur un mécanisme qui n'a pas servi depuis dix-neuf ans et qui ne grince pas, parce qu'il n'y a pas de mécanisme." },
    "Il en sort de l'air. De l'air sec, froid, et respirable, ce qui est impossible après dix-neuf ans et ce qui règle en une seconde la question de savoir si ces gens avaient un pouvoir ou gardaient quelque chose.",
    "§ Alycia recule d'un pas. C'est le seul pas en arrière qu'elle fera de tout l'acte.",
    "« Il l'a senti », dit-elle.",
    "« Qui ? »",
    "« Tout ce qui sait écouter. Moi, à quatorze lieues, j'aurais su. »",
  ],
  effets:{ flags:['kar_ouvert','kar_paume'], suspicion:10,
           exploit:{ eclat:6, suspicion:12, temoins:'aucun', quoi:"une porte de Karlsberg s'est ouverte pour la première fois en dix-neuf ans" },
           marque:"Vous avez ouvert Karlsberg avec votre paume. Ce qui sait écouter l'a su.",
           court:"La porte" },
  suite:'kar_crypte', libelleSuite:"Descendre" },

kar_autre_dom:{
  texte:[
    "Il y a toujours une autre entrée. Il y en a toujours une : un puits, une cave à glace, un conduit de latrines, une descente de cellier — les maisons sont percées comme des fromages et personne ne pense jamais aux trous par où sortent les choses sales.",
    { sobre:"C'est le conduit de la glacière. Onze pieds, en biais, et il faut ramper.",
      intense:"C'est le conduit de la glacière : dix-huit pouces de large, onze pieds en biais, bouché par vingt ans de feuilles tassées qu'il faut sortir à la main. On y passe sur le dos, la tête la première, avec les bras au-dessus, et on ne peut pas revenir en arrière.",
      extreme:"C'est le conduit de la glacière : dix-huit pouces de large, onze pieds en biais, bouché par vingt ans de feuilles tassées et de terre lessivée qu'il faut sortir à la main, une poignée à la fois, pendant deux heures. On y passe sur le dos, tête la première, bras au-dessus, sans possibilité de revenir. À mi-parcours il y a une odeur qui n'est ni la terre ni la feuille et qu'on décide de ne pas identifier." },
    "§ La maison ne sait pas que vous êtes entré. C'était tout l'objet.",
    "Alycia passe après vous, plus facilement, et elle fait une remarque en sortant du conduit qui vaut tout le reste :",
    "« Vous êtes le seul Karlsberg vivant et vous êtes entré chez vous par les latrines. Votre père vous aurait giflé. »",
    "« Probablement. »",
    "« Le mien m'aurait giflée aussi. C'est en gros tout ce que j'ai gardé de lui. »",
  ],
  effets:{ flags:['kar_ouvert','kar_discret'], cout:{ endurance:16 },
           faire:() => bouger('alycia', { relation:2, attirance:2 }),
           marque:"Vous êtes entré à Karlsberg par le conduit de la glacière. La maison ne l'a pas su.",
           court:"La glacière" },
  suite:'kar_crypte', libelleSuite:"Descendre" },

kar_autre_cout:{
  texte:[
    "Le conduit de la glacière tient onze pieds et il cède au neuvième.",
    { sobre:"Vous tombez de six pieds sur un sol de cave. Quelque chose se plante dans la cuisse.",
      intense:"Vous tombez de six pieds sur un sol de cave jonché de ce que vingt ans font tomber d'une voûte, et il y a là-dedans un morceau de ferronnerie — un gond, une penture, un fragment de grille — qui entre dans la cuisse gauche par en dessous et qui ne ressort pas.",
      extreme:"Vous tombez de six pieds sur un sol de cave jonché de ce que vingt ans font tomber d'une voûte. Il y a là-dedans un fragment de penture rouillée, dressé, et il entre dans la cuisse gauche par en dessous sur quatre pouces et n'en ressort pas. Il faut le sortir à la main, dans le noir, en aveugle, et une ferraille de vingt ans qui sort d'une cuisse emporte avec elle tout ce qu'elle avait dessus." },
    "Alycia descend par le conduit sans problème, ce qui est agaçant, et elle passe vingt minutes à nettoyer ça avec de l'eau-de-vie et sans un commentaire.",
    "§ Vous êtes entré sans que la maison le sache. C'est ce que vous vouliez et c'est ce que ça coûte.",
  ],
  effets:{ flags:['kar_ouvert','kar_discret'], cout:{ endurance:18, vitalite:12 },
           blessure:{ id:'cuisse_kar', zone:"Cuisse gauche", type:"percée par une penture de vingt ans",
                      gravite:2, douleur:3, saignement:2, fonction:['agilite','endurance','lutte'],
                      cicatrice:"un trou rond au-dessus du genou, et ce qui a poussé dedans" },
           faire:() => bouger('alycia', { relation:2 }),
           marque:"Vous êtes tombé dans votre propre glacière et vous vous êtes empalé sur une penture.",
           court:"La penture" },
  suite:'kar_crypte', libelleSuite:"Descendre" },

kar_autre_ko:{
  texte:[
    "Vous cherchez deux jours. Il y a un puits comblé, une cave effondrée, un conduit qui se termine sur de la maçonnerie neuve — neuve : quelqu'un a muré ce conduit après la Purge, ce qui est en soi un renseignement dont vous ne saurez rien faire.",
    "Le troisième jour, Alycia s'assied sur une pierre et dit la chose que vous refusiez d'entendre depuis deux jours.",
    "§ « Il y a une porte faite pour ta main, à quarante pas d'ici, et tu passes trois jours dans des trous. »",
    "« Oui. »",
    "« Pourquoi ? »",
    "« Parce que si je la pose, ça se saura. »",
    "« Ça se sait déjà. » Elle montre le sud d'un mouvement de menton. « Il y a de la fumée à deux lieues depuis hier soir, et ce n'est pas un charbonnier : un charbonnier fume trois jours, celle-là a fumé quatre heures et s'est arrêtée. »",
  ],
  effets:{ flags:['kar_perdu_temps','kar_fumee'], cout:{ endurance:14, moral:5 },
           marque:"Trois jours à chercher une autre entrée, et de la fumée à deux lieues au sud.",
           court:"La fumée" },
  suite:'kar_porte', libelleSuite:"Revenir à la dalle" },

kar_repart:{
  qui:'alycia',
  titre:"On repart",
  texte:[
    "« Les Karlsberg sont morts. On repart. »",
    "Alycia ne discute pas. Elle remonte à cheval, elle attend que vous soyez en selle, et elle prend la route du sud sans un mot pendant deux heures.",
    { sobre:"Au bout de deux heures : « C'est une décision ou c'est de la peur ? »",
      intense:"Au bout de deux heures, sans tourner la tête : « C'est une décision ou c'est de la peur ? Je demande sans jugement : les deux se défendent, et j'ai pris la deuxième à dix-sept ans devant une ferme avec six vaches. »",
      extreme:"Au bout de deux heures, sans tourner la tête : « C'est une décision ou c'est de la peur ? Je demande sans jugement — les deux se défendent, et à dix-sept ans j'ai pris la deuxième devant une ferme avec six vaches et trois enfants dans la cour. Je ne me le reproche pas. Je constate seulement qu'on ne peut pas prendre la deuxième deux fois : la première fois ça s'appelle survivre, la seconde ça s'appelle autre chose. »" },
    "§ Vous repartez. La dalle reste sous six pieds de terre dégagée, ce qui est pire que sous six pieds de terre, parce que maintenant elle est visible.",
    "Il y avait de la fumée à deux lieues au sud. Vous ne l'avez pas vue et Alycia n'a rien dit.",
  ],
  effets:{ flags:['kar_refuse','kar_dalle_decouverte'], cout:{ moral:10 },
           faire:() => { bouger('alycia', { confiance:-2 }); A2().lieu = 'karlsberg'; },
           marque:"Vous avez dégagé la dalle de Karlsberg et vous êtes reparti sans l'ouvrir.",
           court:"Reparti" },
  suite:'a2_carte', libelleSuite:"La carte" },

};

/* ══ LA CRYPTE ═══════════════════════════════════════════════════════════ */
const KARLS_2 = {

kar_crypte:{
  qui:'alycia',
  lieu:"Sous Karlsberg",
  titre:"La crypte des noms effacés",
  texte:[
    { sobre:"Des dizaines de statues ont perdu leur visage.",
      intense:"Trente-quatre statues, en deux rangs, sur toute la longueur d'une salle voûtée de quatre-vingts pieds. Toutes ont perdu leur visage — pas usé : **retiré**, au ciseau, proprement, en trois ou quatre coups chacune. Quelqu'un a passé une semaine ici avec un maillet.",
      extreme:"Trente-quatre statues en deux rangs, sur quatre-vingts pieds de voûte. Toutes ont perdu leur visage — pas usé par le temps : retiré au ciseau, proprement, trois ou quatre coups chacune, avec les éclats encore par terre au pied de chaque socle parce que personne n'a balayé. Quelqu'un a passé une semaine ici, à la lumière, avec un maillet et un ciseau à froid, en descendant la rangée dans l'ordre. C'est un travail. On l'a payé à quelqu'un." },
    "Sur les socles, les noms ont été piqués au poinçon jusqu'à ne plus rien vouloir dire. Sur trois d'entre eux, l'ouvrier s'est fatigué et on lit encore une syllabe.",
    "§ Sur le mur du fond, une fresque : des chevaliers sous une bannière noire, et au centre quelque chose qu'on ne distingue pas parce que la couche a sauté.",
    "Et devant la fresque, un coffre de fer.",
    { sobre:"Autour du coffre, quatre corps. Ils sont récents.",
      intense:"Autour du coffre, quatre corps. Ils sont récents — trois semaines, quatre au plus, ce qui se juge à l'odeur et à autre chose. Ils portent le gris de Mont-Draken. Aucun n'a une blessure.",
      extreme:"Autour du coffre, quatre corps de trois ou quatre semaines, en gris de Mont-Draken, et aucun n'a une blessure. Pas une entaille, pas un os cassé, pas une trace de lien. Ils sont morts debout et ils sont tombés là où ils étaient : deux face au coffre, un qui se retournait, et un qui avait déjà fait quatre pas vers la sortie. Celui-là a les mains en avant." },
    "Alycia se penche sur le plus proche et elle reste penchée un long moment.",
    "« Ce n'est pas moi », dit-elle. « Au cas où. »",
    "« Je sais. »",
    "« Non, vous ne savez pas, et c'est très bien. » Elle se redresse. « Ce n'est pas moi parce que ce n'est pas ce que ça fait. Moi j'arrête. Ça, ça a **refusé**. »",
    "« Refusé quoi ? »",
    "§ « Refusé qu'ils soient là. Il y a une différence entre tuer un homme et décider qu'il n'a pas le droit d'être dans une pièce. »",
    "Elle regarde le coffre, à quatre pas, et elle ne s'en approche pas.",
    "« Vous, allez-y. C'est chez vous. Moi je reste ici. »",
  ],
  effets:{ flags:['kar_crypte','kar_quatre_corps','kar_montdraken_venu'],
           cout:{ moral:6 },
           marque:"Quatre hommes de Mont-Draken morts sans blessure dans la crypte de Karlsberg.",
           court:"Quatre corps" },
  suite:'kar_embuscade', libelleSuite:"Le coffre" },

kar_embuscade:{
  melee:true,
  titre:"« Le dernier loup devait rester une rumeur »",
  effets:{ melee:{ position:"au milieu de la crypte", note:"Ils sont dans l'escalier" } },
  texte:[
    "Vous faites quatre pas vers le coffre.",
    { sobre:"Un carreau d'arbalète se brise contre la pierre près de votre tête.",
      intense:"Un carreau d'arbalète se brise contre la pierre à un pied de votre tête et vous couvre la joue d'éclats de granite. Il vient de l'escalier — celui par lequel vous n'êtes pas descendus.",
      extreme:"Un carreau d'arbalète se brise contre le montant d'une statue à un pied de votre tête, et vous prenez une poignée d'éclats de granite dans la joue et le coin de l'œil. Il vient de l'escalier ouest, celui par lequel vous n'êtes pas descendus, et un carreau qui arrive de là veut dire que quelqu'un connaissait cette crypte mieux que vous et vous y attendait depuis un moment." },
    "« Le dernier loup devait rester une rumeur. »",
    "§ La voix vient d'en haut de l'escalier. Elle est posée, elle articule, et elle n'a pas peur.",
    "Ils sont cinq. Ils tiennent l'escalier ouest et ils ne descendent pas — parce que quatre de leurs camarades sont morts en descendant, et qu'ils l'ont vu.",
    "Alycia s'est mise derrière une statue sans que vous la voyiez bouger.",
  ],
  choix:[
    { t:"Se mettre à couvert et les identifier",
      detail:"Cinq, un escalier, et quatre morts qui leur interdisent de descendre · Perception + tactique contre 10",
      risque:"prudent",
      test:{ carac:'perception', comp:'tactique', dc:10, adversaire:'embuscade', manoeuvre:'couvert' },
      degres:{ dominante:'kar_emb_dom', couteuse:'kar_emb_cout', echec:'kar_emb_ko' } },

    { t:"L'Onde, dans un escalier de six pieds",
      detail:"Ils sont cinq dans un tube de pierre · Volonté + Onde contre 9",
      ferme:"Ferme : la possibilité qu'un des cinq redescende la colline",
      risque:"définitif", definitif:true,
      test:{ carac:'volonte', comp:'onde', dc:9, adversaire:'embuscade', manoeuvre:'onde_escalier',
             cout:{ concentration:25 } },
      degres:{ dominante:'kar_onde_dom', couteuse:'kar_onde_dom', echec:'kar_emb_ko' } },

    { t:"Feindre une blessure et attirer leur chef",
      detail:"Ils ne descendent pas · il faut leur donner une raison · Présence + tactique contre 11",
      risque:"dangereux",
      test:{ carac:'presence', comp:'tactique', dc:11, adversaire:'embuscade', manoeuvre:'feindre' },
      degres:{ dominante:'kar_feinte_dom', couteuse:'kar_feinte_cout', echec:'kar_emb_ko' } },

    { t:"« Les archives contre le nom de votre commanditaire »",
      detail:"Ils sont venus pour le coffre · vous êtes assis dessus · et ils ont vu mourir quatre camarades",
      risque:"calculé",
      test:{ carac:'presence', comp:null, dc:12, adversaire:'embuscade', manoeuvre:'echange',
             situation:() => a('al_liste') ? 3 : 0 },
      degres:{ dominante:'kar_echange_dom', couteuse:'kar_echange_cout', echec:'kar_emb_ko' } },
  ],
},

kar_emb_dom:{
  melee:true,
  texte:[
    "Vous vous mettez derrière un socle et vous regardez, ce que personne ne fait sous une arbalète et qui est la seule chose à faire.",
    { sobre:"Cinq. Trois arbalètes, deux épées. Et un qui donne les ordres sans tirer.",
      intense:"Cinq. Trois arbalètes à cric — des armes de siège, lentes, quarante secondes de rechargement — et deux épées. Et un sixième, qu'on ne compte pas parce qu'il ne tire pas : il est en haut des marches, il ne descend pas, et il donne les ordres à voix normale.",
      extreme:"Cinq, et un sixième qu'on ne compte pas d'abord parce qu'il ne tire pas. Trois arbalètes à cric — armes de siège, quarante secondes de rechargement, et un escalier de six pieds n'en laisse tirer qu'une à la fois. Deux épées derrière. Et en haut des marches, hors de portée, un homme qui donne les ordres à voix normale et qui ne les crie pas, ce qui veut dire qu'il a l'habitude d'être obéi sans crier." },
    "§ Trois arbalètes dans un tube de six pieds ne font pas trois arbalètes. Elles en font une, quarante secondes sur quarante.",
    "Vous comptez. Quarante secondes après le troisième carreau, il y a un trou de neuf secondes où aucune des trois n'est prête, et où deux épées tiennent seules un escalier contre un homme qui monte.",
    "Neuf secondes, c'est un escalier de dix-huit marches.",
    "Vous les prenez.",
    { sobre:"Les deux épées ne tiennent pas.",
      intense:"Les deux épées ne tiennent pas neuf secondes contre quelqu'un qui monte en sachant qu'il a neuf secondes. Le premier va par-dessus la rampe, ce qui fait vingt pieds. Le deuxième se rend, et il se rend d'une façon particulière : il pose son arme et il s'assied sur une marche.",
      extreme:"Les deux épées ne tiennent pas neuf secondes contre un homme qui monte en sachant qu'il en a neuf. Le premier passe par-dessus la rampe et fait vingt pieds sur du dallage. Le deuxième se rend, et il se rend d'une manière qu'on ne voit jamais : il pose son arme sur une marche, il s'assied à côté, et il met les mains sur les genoux comme un homme qui attend qu'on l'appelle." },
    "Les trois arbalétriers ont lâché leurs cric et sont partis par le haut.",
    "§ Il reste celui qui donnait les ordres. Il n'est pas parti.",
  ],
  effets:{ flags:['kar_emb_gagnee','kar_chef_vivant','kar_un_rendu'], cout:{ endurance:16 },
           exploit:{ eclat:5, temoins:'un', quoi:"vous avez pris un escalier tenu par cinq hommes" },
           meleeMaj:{ position:"en haut de l'escalier", note:"Un rendu · le chef n'est pas parti" } },
  suite:'kar_chef', libelleSuite:"Celui qui donnait les ordres" },

kar_emb_cout:{
  melee:true,
  texte:[
    "Vous vous mettez à couvert, vous comptez les rechargements, et vous vous trompez d'un cric.",
    { sobre:"Le carreau vous prend l'épaule gauche de face. Il traverse.",
      intense:"Un carreau d'arbalète à cric tiré à onze pas ne se pare pas et ne s'esquive pas : il arrive. Il vous prend l'épaule gauche de face, il traverse le cuir, le muscle et ressort par-derrière, et il vous colle contre un socle de statue avec assez de force pour que vous restiez debout deux secondes sans le vouloir.",
      extreme:"Un carreau à cric tiré à onze pas ne se pare pas, ne s'esquive pas : il arrive. Il vous prend l'épaule gauche de face, traverse le cuir, le deltoïde, l'omoplate, et ressort de six pouces derrière. Il vous cloue une seconde contre le socle d'une statue sans visage. Ça ne fait pas mal tout de suite — un carreau ne fait jamais mal tout de suite — mais le bras gauche cesse d'être à vous, et il le restera trois mois." },
    "Vous montez quand même. On monte toujours quand même : c'est la seule chose que ce métier apprenne vraiment.",
    "Les deux épées de l'escalier tiennent onze secondes au lieu de neuf, et onze secondes contre un homme avec un carreau dans l'épaule, c'est presque assez.",
    "§ Presque. Il en reste un, assis sur une marche, qui a posé son arme.",
    "Et celui qui donnait les ordres n'est pas parti.",
  ],
  effets:{ flags:['kar_emb_gagnee','kar_chef_vivant','kar_un_rendu'],
           cout:{ endurance:20, vitalite:18 },
           blessure:{ id:'epaule_kar', zone:"Épaule gauche", type:"traversée par un carreau à cric",
                      gravite:3, douleur:3, saignement:3, fonction:['force','lutte','bouclier','epees','jet'],
                      cicatrice:"deux trous, devant et derrière, et un bras qui met trois mois" },
           exploit:{ eclat:5, temoins:'un', quoi:"vous avez pris l'escalier avec un carreau dans l'épaule" },
           meleeMaj:{ position:"en haut de l'escalier", note:"Un carreau dans l'épaule" } },
  suite:'kar_chef', libelleSuite:"Celui qui donnait les ordres" },

kar_emb_ko:{
  melee:true,
  texte:[
    "Vous faites ce qu'il ne faut pas faire dans une crypte tenue par trois arbalètes : vous avancez à découvert.",
    { sobre:"Deux carreaux. Le deuxième vous met au sol.",
      intense:"Deux carreaux. Le premier passe. Le deuxième vous prend la cuisse droite de plein et vous met au sol au milieu de quatre-vingts pieds de dallage, à découvert, à onze pas de trois hommes qui rechargent.",
      extreme:"Deux carreaux. Le premier passe à un pouce du cou. Le deuxième prend la cuisse droite de plein, casse le fémur net, et vous met au sol au milieu de quatre-vingts pieds de dallage, à découvert, à onze pas de trois hommes qui rechargent en quarante secondes." },
    "§ Ce qui suit ne vient pas de vous.",
    { sobre:"Alycia sort de derrière sa statue.",
      intense:"Alycia sort de derrière sa statue et elle monte l'escalier au pas. Pas en courant : au pas, dans l'axe, à découvert, contre trois arbalètes.\n\nIls n'ont pas le temps d'en armer une seule.",
      extreme:"Alycia sort de derrière sa statue et monte l'escalier au pas. Pas en courant : au pas, dans l'axe, entièrement à découvert, contre trois arbalètes à onze pas. Ils n'ont pas le temps d'en armer une. Ils s'arrêtent l'un après l'autre, du bas vers le haut, dans l'ordre où elle monte — et le dernier, tout en haut, a le temps de voir les quatre autres et de comprendre, et c'est celui-là qu'elle laisse pour la fin exprès." },
    "Quand elle redescend, elle a le nez qui saigne et elle ne s'en occupe pas.",
    "« Vous avez trois mois de jambe », dit-elle. « Ne discutez pas. »",
    "§ Il en reste un, en haut : celui qui donnait les ordres. Elle ne l'a pas touché.",
    "« Celui-là, c'est à vous », dit-elle. « Je ne vous ai pas tout pris. »",
  ],
  effets:{ flags:['kar_emb_gagnee','kar_chef_vivant','al_sauve_par_elle_2'],
           cout:{ endurance:24, vitalite:25, moral:10 },
           blessure:{ id:'femur', zone:"Cuisse droite", type:"fémur cassé par un carreau à cric",
                      gravite:3, douleur:3, saignement:2, fonction:['agilite','endurance','force','lutte','equitation'],
                      cicatrice:"une jambe qui a mis quatre mois et qui restera plus courte d'un demi-pouce" },
           faire:() => bouger('alycia', { relation:2, confiance:2 }),
           meleeMaj:{ position:"au sol", note:"Elle a monté l'escalier au pas" } },
  suite:'kar_chef', libelleSuite:"Celui qui donnait les ordres" },

kar_onde_dom:{
  melee:true,
  texte:[
    "Un escalier de six pieds de large et dix-huit marches est une chose qu'on a inventée pour se défendre, et c'est très efficace contre des hommes.",
    { sobre:"Vous ouvrez la main dans le tube.",
      intense:"Vous ouvrez la main dans le tube. Il n'y a nulle part où aller : c'est de la pierre à gauche, de la pierre à droite, de la pierre au-dessus, et cinq hommes au milieu qui partent tous ensemble vers le haut comme de l'eau dans une conduite.",
      extreme:"Vous ouvrez la main dans le tube, et un escalier de six pieds devient une conduite. Il n'y a nulle part où aller : pierre à gauche, pierre à droite, pierre au-dessus. Les cinq partent ensemble vers le haut comme de l'eau chassée, et ce qui arrive en haut d'un escalier de dix-huit marches à cette vitesse ne ressemble plus à cinq hommes. Le linteau de la porte descend ensuite, avec trois pieds de maçonnerie, et bouche la moitié de l'ouverture." },
    "§ Le silence, après. C'est toujours le silence qui est difficile.",
    "Alycia sort de derrière sa statue. Elle regarde l'escalier, puis vous, puis l'escalier.",
    "« Voilà », dit-elle. « Maintenant je sais ce que je regardais sur la route. »",
    "« Et ? »",
    "« Et je préfère la mienne. La mienne s'arrête. »",
    "§ Il reste celui qui donnait les ordres : il était en haut, derrière le linteau, et le linteau lui a sauvé la vie en tombant.",
  ],
  effets:{ flags:['kar_emb_gagnee','kar_chef_vivant','a2_onde_publique','kar_escalier_bouche'],
           cout:{ endurance:16, concentration:20 },
           faire:() => bouger('alycia', { attirance:2, peur:2 }),
           exploit:{ eclat:8, suspicion:14, temoins:'un', quoi:"cinq hommes sont montés d'un escalier sans le vouloir" },
           meleeMaj:{ position:"au pied de l'escalier", note:"Le linteau est tombé" } },
  suite:'kar_chef', libelleSuite:"Celui qui donnait les ordres" },

kar_feinte_dom:{
  melee:true,
  texte:[
    "Ils ne descendent pas parce que quatre des leurs sont morts en descendant. Il faut donc leur donner une raison de descendre plus forte que quatre morts.",
    "Vous tombez.",
    { sobre:"On ne feint pas une blessure en criant. On la feint en se taisant.",
      intense:"On ne feint pas une blessure en criant : personne ne crie. On la feint en s'asseyant lourdement, en essayant deux fois de se relever, et en laissant le deuxième essai échouer d'une façon qui n'a rien de spectaculaire. C'est le petit ratage qui convainc, jamais le grand.",
      extreme:"On ne feint pas une blessure en criant — personne ne crie, c'est la première chose qu'on apprend en voyant des blessés. On la feint en s'asseyant lourdement, en essayant de se relever deux fois, et en laissant le second essai rater d'une manière parfaitement ordinaire : la main qui glisse sur le dallage, le genou qui ne prend pas. C'est le petit ratage qui convainc. Le grand, personne n'y croit." },
    "Le chef descend au bout de quarante secondes, parce qu'un homme à terre au milieu d'une crypte est une occasion et parce que quatre morts sans blessure ne sont peut-être qu'un poison dans l'air.",
    "Il descend avec deux épées et il laisse les arbalètes en haut, ce qui est exactement l'erreur.",
    "§ Vous vous relevez à sept pas.",
    "Les deux épées ne durent pas. Lui, il ne se bat pas : il recule contre le coffre de fer et il lève les mains, ce qui est la première chose intelligente que quiconque ait faite dans cette crypte.",
  ],
  effets:{ flags:['kar_emb_gagnee','kar_chef_vivant','kar_chef_pris'], cout:{ endurance:14 },
           exploit:{ eclat:4, temoins:'un', quoi:"vous avez fait descendre un homme qui savait ne pas descendre" },
           meleeMaj:{ position:"devant le coffre", note:"Il a levé les mains" } },
  suite:'kar_chef', libelleSuite:"Il a levé les mains" },

kar_feinte_cout:{
  melee:true,
  texte:[
    "Vous tombez, et il descend, et il descend avec les trois arbalètes.",
    { sobre:"Un homme prudent ne laisse pas ses arbalètes en haut.",
      intense:"Un homme prudent ne laisse pas ses arbalètes en haut de l'escalier quand il descend voir un blessé. Celui-ci n'est pas prudent : il est méthodique, ce qui est pire, et il fait descendre les trois en premier.",
      extreme:"Un homme prudent ne laisse pas ses arbalètes en haut quand il descend voir un blessé. Celui-ci n'est pas prudent : il est méthodique, ce qui est bien pire. Il fait descendre les trois arbalétriers d'abord, en file, avec ordre de ne pas dépasser la sixième marche — la limite exacte où sont tombés ses quatre camarades, qu'il a mesurée." },
    "Vous vous relevez sous trois arbalètes à onze pas. Il y en a une qui part.",
    "Le carreau vous prend le flanc droit, entre deux côtes, et n'en ressort pas.",
    "§ Ce qui suit se règle au corps à corps, ce qui est le seul endroit où trois arbalètes ne servent plus à rien.",
    "Il en reste un debout à la fin, contre le coffre de fer, les mains levées : celui qui donnait les ordres.",
  ],
  effets:{ flags:['kar_emb_gagnee','kar_chef_vivant','kar_chef_pris'],
           cout:{ endurance:20, vitalite:20 },
           blessure:{ id:'flanc_kar', zone:"Flanc droit", type:"carreau entre deux côtes, resté dedans",
                      gravite:3, douleur:3, saignement:3, fonction:['force','endurance','agilite','lutte'],
                      cicatrice:"un carreau qu'on n'a jamais entièrement sorti" },
           meleeMaj:{ position:"devant le coffre", note:"Un carreau dans le flanc" } },
  suite:'kar_chef', libelleSuite:"Il a levé les mains" },

kar_echange_dom:{
  melee:true,
  texte:[
    "« Vous êtes venus pour le coffre. Je suis assis dessus. »",
    "Silence dans l'escalier.",
    "« Et vous avez quatre camarades par terre autour de moi qui n'ont pas de blessure. »",
    { sobre:"« Qu'est-ce que vous proposez ? »",
      intense:"« Qu'est-ce que vous proposez ? » La voix d'en haut n'a pas bougé d'un ton. C'est un homme qui négocie depuis un escalier avec quatre morts en bas, et il négocie exactement comme s'il était dans un bureau.",
      extreme:"« Qu'est-ce que vous proposez ? » La voix d'en haut n'a pas bougé d'un demi-ton. Un homme qui négocie depuis un escalier, avec quatre de ses hommes morts en bas sans une blessure, et qui négocie exactement du ton dont on discute d'un prix de fourrage. C'est le renseignement le plus utile de la journée." },
    "« Les archives. Vous les emportez. Contre le nom de celui qui vous paie. »",
    "« Ce sont des archives de votre maison. »",
    "« Je sais lire. Je les lirai avant. »",
    "§ Onze secondes.",
    "« Marché. »",
    "Il descend seul, sans arme, jusqu'à la sixième marche et pas plus bas — la limite exacte où sont tombés ses hommes, qu'il a mesurée et qu'il ne franchira pas.",
    "« Le nom d'abord », dit-il. « Parce que si je vous donne les archives d'abord, vous ne me donnerez rien. Et si je vous donne le nom d'abord, vous me donnerez les archives, parce que vous êtes le genre d'homme qui tient un marché. Je vous ai regardé pendant vingt minutes. »",
  ],
  effets:{ flags:['kar_echange','kar_chef_vivant','kar_marche'], 
           exploit:{ eclat:4, temoins:'quelques', quoi:"vous avez négocié depuis une crypte avec cinq arbalètes au-dessus" },
           meleeMaj:{ position:"au pied de l'escalier", note:"Il est sur la sixième marche" } },
  suite:'kar_chef', libelleSuite:"Le nom d'abord" },

kar_echange_cout:{
  melee:true,
  texte:[
    "« Les archives contre le nom de votre commanditaire. »",
    "« Non. »",
    "C'est net, immédiat, et sans regret : un homme qui refuse en une seconde a déjà pesé l'offre avant qu'on la fasse.",
    "« Vous me proposez de vendre celui qui me paie pour un coffre que je vais prendre de toute façon quand vous serez mort. Vous n'êtes pas en position de proposer quoi que ce soit, messire, vous êtes en position de proposer un délai, et un délai je peux vous le donner : partez maintenant et je ne fais pas tirer. »",
    "§ Il est raisonnable. C'est la troisième fois cette année qu'un homme parfaitement raisonnable vous explique tranquillement comment vous allez perdre.",
    "Vous ne partez pas. Ce qui suit se règle dans un escalier, à l'ancienne, et ça coûte ce que coûtent les escaliers.",
    "Il en reste un debout : lui.",
  ],
  effets:{ flags:['kar_emb_gagnee','kar_chef_vivant'],
           cout:{ endurance:20, vitalite:14 },
           blessure:{ id:'main_kar', zone:"Main gauche", type:"deux doigts sur une lame, dans un escalier",
                      gravite:2, douleur:2, saignement:2, fonction:['lutte','bouclier','jet'],
                      cicatrice:"deux doigts raides à froid" },
           meleeMaj:{ position:"en haut de l'escalier", note:"Il est le dernier" } },
  suite:'kar_chef', libelleSuite:"Le dernier" },

};
Object.assign(KARLS, KARLS_2);

/* ══ LE COFFRE ═══════════════════════════════════════════════════════════ */
const KARLS_3 = {

kar_chef:{
  titre:"Celui qui donnait les ordres",
  texte:[
    "Il a cinquante ans, il s'appelle Bérold, il est sergent-instructeur de Mont-Draken depuis onze ans, et il ne demande pas sa vie.",
    "« Vous êtes le neuvième de la liste. »",
    "« Je sais. »",
    "« Alors vous savez aussi que je ne vous dirai pas grand-chose, parce que je ne sais pas grand-chose : je suis un sergent, on me donne un nom et une adresse. »",
    "§ « Mais je vais vous dire ce que je sais, parce que quatre de mes hommes sont morts dans cette pièce sans qu'on les touche, et que je veux que quelqu'un puisse me l'expliquer un jour. »",
    "« La liste. Qui l'a faite ? »",
    { sobre:"« Personne à Mont-Draken. Elle est arrivée. »",
      intense:"« Personne chez nous. Elle est arrivée il y a six ans, par le greffe de Chastel, dans un pli de transmission ordinaire — et le pli portait un cachet qui n'était pas celui de Chastel. » Il hausse les épaules. « Je l'ai vu parce que c'est moi qui ouvre les plis quand le capitaine n'est pas là. »",
      extreme:"« Personne chez nous. Elle est arrivée il y a six ans par le greffe de Chastel, dans un pli de transmission ordinaire, avec les rôles trimestriels — et le pli portait un cachet qui n'était pas celui de Chastel. Je l'ai vu parce que c'est moi qui ouvre les plis quand le capitaine n'est pas là, et parce que je regarde les cachets : c'est la seule chose intéressante dans un pli de transmission. »" },
    "« Quel cachet ? »",
    "« Je ne l'ai pas reconnu et je l'ai regardé longtemps. Ce n'était pas une maison de la province. C'était un cachet **ancien** : la cire était d'un rouge qu'on ne fait plus, et le dessin était mangé au milieu. »",
    "« Il ressemblait à quoi ? »",
    "Bérold, sergent-instructeur de Mont-Draken, onze ans de service, regarde le mur du fond de la crypte de Karlsberg.",
    "Et il regarde la fresque : des chevaliers sous une bannière noire, et au centre une couche qui a sauté.",
    "§ « À ça, messire. Il ressemblait à ce qui manque au milieu de votre mur. »",
  ],
  effets:{ flags:['kar_berold','a2_cachet','a2_papier_ouvert'],
           faire:() => { A2().pistes.papier = 1; },
           exploit:{ eclat:3, temoins:'un', quoi:"un sergent de Mont-Draken vous a dit d'où venait la liste" },
           marque:"La liste est arrivée à Mont-Draken par le greffe de Chastel, sous un cachet ancien qu'aucun sergent n'a reconnu.",
           court:"Le cachet" },
  choix:[
    { t:"Le laisser partir",
      detail:"Il a onze ans de service, quatre morts dans la crypte, et il n'a rien à vendre de plus",
      va:'kar_berold_part' },
    { t:"Le tuer",
      detail:"Il sait où vous êtes · il sait ce qu'il y avait dans ce coffre · et il rentre à Mont-Draken",
      ferme:"Ferme : le seul homme de Mont-Draken qui vous ait parlé",
      risque:"définitif", definitif:true, va:'kar_berold_mort' },
    { t:"L'emmener",
      detail:"Un sergent-instructeur qui a vu quatre hommes mourir sans blessure · et qui veut une explication",
      risque:"dangereux", definitif:true, va:'kar_berold_garde' },
  ],
},

kar_berold_part:{
  texte:[
    "Il monte l'escalier sans se retourner, en enjambant ce qu'il faut enjamber, et il ne dit ni merci ni rien d'autre.",
    "À la douzième marche il s'arrête quand même.",
    "« Le capitaine a demandé une commission au conseil de province. Sur les manifestations de l'Onde. Elle lui a été accordée en Ventôse. »",
    "« Qu'est-ce que ça change ? »",
    { sobre:"« Une commission, ça donne le droit d'entrer. »",
      intense:"« Une commission, messire, ça ne donne pas le droit de tuer : ça donne le droit d'**entrer**. De réquisitionner, de faire ouvrir, de convoquer. Jusqu'à Ventôse, Mont-Draken envoyait six hommes sur une route. À partir de maintenant, il enverra un magistrat et vingt. »",
      extreme:"« Une commission ne donne pas le droit de tuer. Elle donne le droit d'entrer : réquisitionner, faire ouvrir, convoquer sous peine. Jusqu'à Ventôse, Mont-Draken envoyait six hommes sur une route et espérait. À partir de maintenant il enverra un magistrat, vingt hommes et un ordre écrit — et personne dans cette province n'a jamais su comment on refuse un ordre écrit. »" },
    "« Pourquoi me dire ça ? »",
    "« Parce que vous m'avez laissé partir et que ça m'oblige. » Il reprend l'escalier. « Ne comptez pas sur une deuxième fois : on m'a expliqué ce que vous êtes, et j'y crois. »",
  ],
  effets:{ flags:['kar_berold_libre','a2_commission','a2_montdraken_sait'],
           faire:() => retenir('charles', "un de ses sergents est reparti vivant de Karlsberg et lui a tout raconté"),
           marque:"Mont-Draken a obtenu une commission du conseil de province sur les manifestations de l'Onde.",
           court:"La commission" },
  suite:'kar_coffre', libelleSuite:"Le coffre" },

kar_berold_mort:{
  texte:[
    "Il ne se défend pas et il ne supplie pas. Il dit une seule chose et il la dit vite, parce qu'il a compris à votre visage qu'il n'a pas le temps d'en dire deux.",
    "« La commission. Ventôse. »",
    "Puis c'est fini.",
    "§ Vous ne saurez jamais ce que ces trois mots voulaient dire, et vous les retournerez pendant deux ans.",
    { sobre:"Alycia n'a rien dit pendant.",
      intense:"Alycia n'a rien dit pendant et elle ne dit rien après, ce qui n'est pas de l'approbation. Au bout d'un moment, en regardant le corps : « Il allait vous donner autre chose. »\n\n« Peut-être. »\n\n« Non. Il allait. Il avait la posture. »",
      extreme:"Alycia n'a rien dit pendant, et elle ne dit rien après, ce qui n'est pas de l'approbation. Au bout d'un long moment, en regardant le corps sans se pencher : « Il allait vous donner autre chose. »\n\n« Peut-être. »\n\n« Non — il allait. Il avait la posture de quelqu'un qui a encore une chose à dire et qui cherche comment la placer. J'ai passé quinze ans à faire parler des gens comme lui, messire. Je sais à quoi ça ressemble et vous venez de le tuer trois secondes avant. »" },
    "Quatre hommes de Mont-Draken sont morts dans cette crypte sans une blessure, et un cinquième avec.",
    "Personne ne rentrera pour l'expliquer.",
  ],
  effets:{ flags:['kar_berold_mort','a2_montdraken_muet'],
           cout:{ moral:8 },
           faire:() => { bouger('alycia', { confiance:-2 }); retenir('charles', "six de ses hommes ont disparu à Karlsberg et personne n'est revenu"); },
           exploit:{ eclat:4, temoins:'aucun', quoi:"six hommes de Mont-Draken ne sont pas rentrés" },
           marque:"Vous avez tué Bérold trois secondes avant qu'il ne dise autre chose.", court:"Trois secondes" },
  suite:'kar_coffre', libelleSuite:"Le coffre" },

kar_berold_garde:{
  texte:[
    "« Vous venez avec nous. »",
    "« Non. »",
    "« Ce n'était pas une question. »",
    { sobre:"« Si. » Il s'assied sur une marche.",
      intense:"« Si, c'en était une, et j'y réponds non. » Il s'assied sur la sixième marche, celle qu'il n'a pas voulu franchir. « J'ai cinquante ans, une femme, deux filles et onze ans de service. Vous pouvez me tuer, vous pouvez me traîner, vous ne pouvez pas m'emmener : ce n'est pas la même chose et vous le savez. »",
      extreme:"« Si, c'en était une, et j'y réponds non. » Il s'assied sur la sixième marche — celle qu'il n'a pas voulu franchir, celle où sont tombés ses hommes. « J'ai cinquante ans, une femme, deux filles à Mont-Draken, et onze ans de service. Vous pouvez me tuer. Vous pouvez me traîner sur onze lieues. Vous ne pouvez pas m'emmener : ce n'est pas le même mot et vous savez très bien lequel des deux vous êtes en train de me proposer. »" },
    "Il vient quand même. Pas parce qu'on l'a convaincu : parce qu'il veut savoir ce qui a tué ses hommes et qu'il n'y a qu'un endroit au monde où l'apprendre.",
    "§ Il voyagera avec vous une saison. C'est un homme méthodique et il regarde tout.",
    "« Une condition, messire. Le jour où je décide de rentrer, je rentre, et je raconte tout. Je ne mentirai pas à mon capitaine. »",
    "« D'accord. »",
    "« Vous acceptez trop vite. Ça veut dire que vous croyez me convaincre. » Il se relève. « Personne n'a jamais convaincu Charles de Mont-Draken de quoi que ce soit, et je le connais depuis vingt-deux ans. »",
  ],
  effets:{ flags:['kar_berold_avec','a2_montdraken_sait'],
           faire:() => { bouger('alycia', { confiance:-1, relation:1 }); retenir('charles', "un de ses sergents voyage avec vous, et il rentrera"); },
           marque:"Bérold voyage avec vous une saison. Il rentrera et il racontera tout.", court:"Bérold" },
  suite:'kar_coffre', libelleSuite:"Le coffre" },

kar_coffre:{
  qui:'alycia',
  titre:"Ce que porte un nom",
  texte:[
    "Le coffre de fer n'est pas fermé. Il n'a jamais été fermé : le fermoir est un simple loquet et il n'y a pas de serrure, parce qu'on ne met pas de serrure dans une pièce où l'on ne peut pas entrer.",
    "Il y a trois choses dedans.",
    { sobre:"Un registre. Une chevalière. Un morceau de bannière qui n'a pas brûlé.",
      intense:"**Un registre** relié de veau, brûlé sur un tiers, à l'angle inférieur — pas dans un incendie : sur une flamme, tenu par quelqu'un qui a changé d'avis.\n\n**Une chevalière** d'homme, en argent, avec un loup de profil, la gueule fermée.\n\n**Un morceau de bannière** de deux pieds sur trois, noir, avec la moitié d'un loup blanc, coupé net au ciseau et non déchiré.",
      extreme:"**Un registre** relié de veau brun, brûlé sur un tiers à l'angle inférieur — pas dans un incendie : sur une flamme, tenu à la main, par quelqu'un qui l'a approché du feu et qui a changé d'avis au bout de neuf secondes. Les bords sont carbonisés en arc de cercle régulier.\n\n**Une chevalière** d'homme, en argent, un loup de profil, la gueule fermée. L'intérieur de l'anneau est usé de façon asymétrique : elle a été portée quarante ans par la même main.\n\n**Un morceau de bannière**, deux pieds sur trois, noir, la moitié d'un loup blanc dessus. Coupé net au ciseau. Pas déchiré, pas brûlé : coupé, avec soin, par quelqu'un qui voulait en garder une moitié et en laisser une autre." },
    "Alycia n'a pas approché. Elle est restée à quatre pas depuis le début et elle y reste.",
    "§ Le registre est de la main de votre père. Vous ne l'avez pas vue depuis dix-neuf ans et vous la reconnaissez à la troisième ligne.",
    "Ce n'est pas un livre de comptes. C'est une correspondance recopiée : quarante ans de lettres entre maisons, transcrites par un homme méthodique qui gardait la trace de ce qu'il écrivait.",
    "Onze maisons. Callensbourg est la troisième.",
    "« Callensbourg est dedans », dites-vous.",
    "Elle ne bouge pas.",
    "« Lisez la dernière page. »",
    "« Comment savez-vous qu'il y a une dernière page ? »",
    "§ « Parce qu'il y en a toujours une, messire, et parce qu'elle n'est jamais de la même main. »",
  ],
  effets:{ flags:['kar_coffre','kar_registre','kar_chevaliere','kar_banniere'],
           faire:() => { A2().pistes.sang = Math.max(A2().pistes.sang, 2); },
           exploit:{ eclat:5, temoins:'aucun', quoi:"vous avez ouvert le coffre de votre père" },
           marque:"Le registre de votre père : quarante ans de correspondance entre onze maisons. Callensbourg est la troisième.",
           court:"Onze maisons" },
  suite:'kar_derniere_page', libelleSuite:"La dernière page" },

kar_derniere_page:{
  titre:"La dernière page",
  texte:[
    "Elle a raison. Elle n'est pas de la même main.",
    "§ C'est celle de votre mère, et elle est datée de trois jours avant.",
    { sobre:"Ce n'est pas une lettre. C'est une liste de quatre lignes.",
      intense:"Ce n'est pas une lettre et ce n'est pas un adieu. C'est une liste de quatre lignes, écrite vite, sans formule, par quelqu'un qui savait qu'il n'aurait pas le temps d'écrire deux fois.\n\nEn haut, trois mots : *Ceux qui savent.*",
      extreme:"Ce n'est ni une lettre ni un adieu. C'est une liste de quatre lignes écrite vite, sans formule, sans en-tête, avec une plume qui accroche parce qu'elle n'a pas été retaillée — par quelqu'un qui savait qu'il n'aurait pas le temps de recommencer.\n\nEn haut, trois mots, soulignés deux fois : *Ceux qui savent.*" },
    "*L'intendant — Perrin de Vaux*",
    "*Le chapelain*",
    "*Le maître d'armes*",
    "*Ma sœur*",
    "§ Quatre. Trois fonctions et une personne.",
    "Le chapelain et le maître d'armes n'ont pas de nom. Ils n'en avaient pas besoin : celle qui écrivait savait qui ils étaient, et elle écrivait pour elle-même, dans une pièce, trois jours avant.",
    { sobre:"« Votre tante est vivante ? »",
      intense:"« Votre tante est vivante ? » demande Alycia, à quatre pas, sans être venue voir la page.\n\n« Je ne sais pas. »\n\n« Vous ne savez pas si votre tante est vivante. »\n\n« Je ne sais pas si j'ai une tante. J'avais neuf ans. »",
      extreme:"« Votre tante est vivante ? » demande Alycia depuis ses quatre pas, sans être venue voir la page, ce qui veut dire qu'elle a entendu la liste dans le silence de votre lecture.\n\n« Je ne sais pas. »\n\n« Vous ne savez pas si votre tante est vivante. »\n\n« Je ne sais pas si j'ai une tante. J'avais neuf ans, et à neuf ans on ne compte pas les adultes d'une maison de sept cents personnes : on en connaît onze et on croit que c'est tout le monde. »" },
    "Quatre lignes. Quatre personnes qui savaient, trois jours avant.",
    "L'une des quatre a écrit à Chastel.",
  ],
  effets:{ flags:['kar_quatre_noms','a2_question_ouverte'],
           faire:() => { A2().pistes.sang = Math.max(A2().pistes.sang, 2); },
           exploit:{ eclat:4, temoins:'aucun', quoi:"vous savez maintenant qu'ils étaient quatre" },
           marque:"Quatre lignes de la main de votre mère : l'intendant Perrin de Vaux, le chapelain, le maître d'armes, et sa sœur.",
           court:"Ceux qui savent" },
  suite:'kar_apres', libelleSuite:"Remonter" },

};
Object.assign(KARLS, KARLS_3);

/* ══ CE QU'ON FAIT D'UNE MAISON RAYÉE ════════════════════════════════════ */
const KARLS_4 = {

kar_apres:{
  qui:'alycia',
  lieu:"Karlsberg · la façade nord · le soir",
  titre:"Ce qu'on en fait",
  texte:[
    "On remonte au jour avec un registre, une chevalière, un morceau de bannière et quatre lignes.",
    "Il reste une décision, et c'est la seule de tout cet acte qui ne se rattrape pas : cette maison est derrière vous et elle est ouverte.",
    { sobre:"Alycia parle la première, ce qui n'est pas son habitude.",
      intense:"Alycia parle la première, ce qui n'est pas son habitude, et elle parle en regardant les ronces et pas vous — ce qui veut dire qu'elle a préparé ce qu'elle va dire pendant qu'on remontait l'escalier.",
      extreme:"Alycia parle la première, ce qui n'est pas son habitude, et elle parle en regardant les ronces et pas vous. Elle a préparé ça pendant qu'on remontait l'escalier, et probablement depuis trois semaines de route, et probablement depuis le premier soir dans une salle basse à Cendrepont." },
    "« Il y a quarante et un Parias vivants dans les quatre provinces. »",
    "« Vous savez le chiffre. »",
    "« Je sais le chiffre, les noms, et où sont trente-huit d'entre eux. C'est ce que je fais depuis quinze ans, et vous alliez le découvrir de toute façon, alors autant que ce soit moi qui le dise. »",
    "§ Elle vous a menti par omission depuis le premier soir, et elle vient de le solder avant qu'on le lui demande.",
    "« Quarante et un », dit-elle. « Vous savez ce qui arrive à quarante et une personnes qu'on rassemble derrière un mur ? »",
    "« Elles sont défendues. »",
    { sobre:"« Elles sont trouvées. »",
      intense:"« Elles sont **trouvées**, messire. En quinze ans, je n'en ai pas perdu un seul, et la seule raison c'est qu'ils sont dans trente-huit endroits et qu'aucun ne connaît l'adresse des autres. Un château, c'est une adresse. C'est même la définition d'un château. »",
      extreme:"« Elles sont trouvées. En quinze ans je n'en ai pas perdu un seul — pas un — et la seule raison est qu'ils sont dans trente-huit endroits différents, qu'aucun ne connaît l'adresse d'un autre, et que moi seule ai la liste et je la porte dans ma tête. Un château est une adresse. C'est la définition même d'un château : un endroit qu'on peut désigner sur une carte et devant lequel on peut poser des hommes. »" },
    "« Et si le mur tient ? »",
    "« Les murs tiennent toujours, jusqu'au jour où ils ne tiennent plus, et ce jour-là tout le monde est dedans. »",
    "Elle se tourne enfin.",
    "« Je ne vous dis pas ce qu'il faut faire. Je vous dis ce que je ferai : si vous relevez cette bannière, je ne vous amènerai personne. Pas par colère. Parce que ce serait les tuer. »",
  ],
  choix:[
    { t:"Refermer. Ne rien dire à personne.",
      detail:"On remet la terre, on laisse les ronces · et Karlsberg reste une rumeur",
      risque:"prudent", definitif:true, va:'kar_fermer' },

    { t:"En faire un refuge, sans bannière",
      detail:"Des gens, pas un château · pas de nom, pas de mur, pas d'adresse qu'on puisse écrire",
      risque:"calculé", definitif:true, va:'kar_refuge' },

    { t:"Relever les Bannières du Loup",
      detail:"Déclarer que Karlsberg existe · devant la province, par acte · et contre elle",
      ferme:"Ferme : l'aide d'Alycia de Callensbourg pour les trente-huit qu'elle cache",
      risque:"définitif", definitif:true, va:'kar_bannieres' },

    { t:"Tout emporter et brûler le reste",
      detail:"Le registre, la chevalière, la bannière · et plus rien à lire ici pour personne",
      ferme:"Ferme : ce que d'autres auraient pu trouver dans cette crypte",
      risque:"définitif", definitif:true, va:'kar_bruler' },
  ],
},

kar_fermer:{
  qui:'alycia',
  texte:[
    "On remet la terre. Ça prend une journée et c'est beaucoup plus long à refermer qu'à ouvrir, ce qui est vrai de tout.",
    "On replante des ronces par-dessus — vraiment : on va en chercher, on les couche, on les cale avec des pierres, et dans deux ans on ne verra plus rien.",
    { sobre:"Alycia travaille avec vous toute la journée sans un mot.",
      intense:"Alycia travaille avec vous toute la journée sans un mot, et à la fin elle a les mains dans le même état que les vôtres, ce qui n'était pas obligatoire.",
      extreme:"Alycia travaille avec vous toute la journée sans un mot : la terre, les pierres, les ronces qu'on couche et qu'on cale. À la fin elle a les mains dans le même état que les vôtres — ouvertes en travers des paumes, pleines d'épines qu'il faudra sortir une par une le soir — et ce n'était absolument pas obligatoire, et elle ne le fera jamais remarquer." },
    "§ Les quatre corps de Mont-Draken restent en bas. On ne les remonte pas : c'est une crypte et ils y sont mieux que dehors.",
    "Le soir, on repart. La façade nord disparaît derrière les frênes au bout de quatre cents pas.",
    "« Vous reviendrez », dit-elle.",
    "« Probablement. »",
    "« Non, pas probablement. Vous reviendrez, et vous ouvrirez, et vous le ferez le jour où quelque chose vous y forcera. » Elle regarde la route. « J'aurais préféré que ce soit un choix. C'est plus solide, un choix. »",
  ],
  effets:{ flags:['kar_ferme'],
           faire:() => { bouger('alycia', { relation:3, confiance:5 }); A2().lieu = 'karlsberg'; },
           marque:"Vous avez refermé Karlsberg de vos mains et replanté les ronces par-dessus.",
           court:"Refermé" },
  suite:'a2_carte', libelleSuite:"La carte" },

kar_refuge:{
  qui:'alycia',
  texte:[
    "« Pas un château. Des gens. »",
    "Elle vous laisse développer et elle écoute jusqu'au bout, ce qu'elle fait mieux que la plupart.",
    "Pas de bannière, pas d'acte, pas de nom déposé nulle part. La façade nord reste des ruines vues de l'extérieur, et elle le restera : rien ne se relève, rien ne se répare qui se voie à trois cents pas.",
    { sobre:"En dessous, c'est autre chose : il y a quatre-vingts pieds de voûte sèche.",
      intense:"En dessous, c'est autre chose. Il y a quatre-vingts pieds de voûte sèche, de l'air qui circule par un conduit que personne n'a bouché en dix-neuf ans, un puits, et une porte qui ne s'ouvre qu'à une paume. Ce n'est pas un château. C'est ce que les maisons rayées font depuis toujours et que personne n'écrit nulle part.",
      extreme:"En dessous, c'est autre chose : quatre-vingts pieds de voûte sèche, un conduit d'air que personne n'a bouché en dix-neuf ans, un puits dont l'eau est bonne, et une porte qui ne s'ouvre qu'à une paume — c'est-à-dire à personne, sauf à ceux à qui elle s'ouvre. Ce n'est pas un château. C'est exactement ce que les maisons rayées ont toujours fait et que personne n'a jamais écrit, parce qu'écrire une cachette est la seule façon sûre de la perdre." },
    "« Combien ? » demande-t-elle.",
    "« Quatre. Six au plus. Ceux qui n'ont nulle part. »",
    "« Six sur quarante et un. »",
    "« Six sur quarante et un. »",
    "§ Elle réfléchit longtemps, et ce qu'elle dit ensuite est ce qu'elle a de plus proche d'un compliment.",
    "« Six, ça ne se remarque pas. Trente-huit, si. » Un temps. « Vous avez trouvé la seule version de cette idée que je ne peux pas refuser, et je n'aime pas être manœuvrée. »",
    "« Ce n'était pas une manœuvre. »",
    "« Je sais. C'est pour ça que je n'aime pas ça. »",
  ],
  effets:{ flags:['kar_refuge','a2_reseau_protege'],
           faire:() => { bouger('alycia', { relation:4, confiance:4, peur:3 }); A2().refuge = 2; A2().lieu = 'karlsberg'; },
           exploit:{ eclat:3, temoins:'aucun', quoi:"il y a six personnes sous Karlsberg et personne ne le sait" },
           marque:"Karlsberg est un refuge de six personnes sous des ruines. Pas de bannière, pas d'acte, pas d'adresse.",
           court:"Le refuge" },
  suite:'a2_carte', libelleSuite:"La carte" },

kar_bannieres:{
  qui:'alycia',
  titre:"Les Bannières du Loup",
  texte:[
    "Le morceau de bannière fait deux pieds sur trois. Il en faut une de douze.",
    "§ On ne relève pas une bannière avec un chiffon : on la relève avec un acte, un héraut, et quelqu'un qui accepte de l'enregistrer.",
    { sobre:"Ça prend une saison et onze couronnes de taxe.",
      intense:"Ça prend une saison entière, un déplacement à Chastel, un greffe, une taxe de onze couronnes, et un commissaire aux titres qui regarde le formulaire pendant très longtemps avant de le prendre.",
      extreme:"Ça prend une saison entière : un déplacement à Chastel, un guichet, un formulaire de relèvement de titre en trois exemplaires, une taxe de onze couronnes, et un commissaire aux titres qui regarde le formulaire pendant très longtemps avant de le prendre. Il ne dit rien. Il le prend. Il le cote, il le date, et il le pose sur la pile de droite — et il n'y a rien de plus définitif au monde qu'une pièce posée sur la pile de droite." },
    "Alycia n'est pas venue à Chastel.",
    "Elle est partie le matin où vous avez annoncé ce que vous alliez faire, sans dispute, sans reproche, en donnant à ses affaires le temps normal qu'il faut pour les charger sur un cheval.",
    "« Vous m'en voulez ? »",
    "« Non. »",
    "« Alycia. »",
    { sobre:"« Je ne vous en veux pas. Je ne vous amènerai personne. Les deux sont vrais. »",
      intense:"« Je ne vous en veux pas et je ne vous amènerai personne. Les deux sont vrais en même temps, et vous allez passer des années à croire que le deuxième contredit le premier. » Elle serre la sangle. « Vous relevez une maison. C'est une bonne chose. Ce n'est simplement pas la même bonne chose que la mienne. »",
      extreme:"« Je ne vous en veux pas, et je ne vous amènerai personne. Les deux sont vrais en même temps et vous allez passer des années à croire que le second contredit le premier. » Elle serre la sangle de son bât, méthodiquement, en vérifiant deux fois. « Vous relevez une maison. C'est une bonne chose — sincèrement, sans ironie : une maison rayée qui se relève, c'est une chose qui devrait arriver plus souvent. Ce n'est simplement pas la même bonne chose que la mienne, et le monde ne nous laissera pas les faire toutes les deux. »" },
    "Elle monte à cheval.",
    "« Si vous avez besoin de moi, je viendrai. Pas avec eux. Seule. »",
    "§ Trois mois plus tard, la bannière noire au loup blanc est enregistrée au bailliage de Chastel, volume cent-quarante-trois, section des titres relevés.",
    "C'est la première fois en dix-neuf ans que quelqu'un écrit *Karlsberg* dans un registre sans une rature à côté.",
  ],
  effets:{ or:-11, flags:['kar_bannieres','a2_bannieres'], suspicion:35,
           faire:() => { bouger('alycia', { relation:-2, confiance:1, peur:-2 }); A2().bannieres = true; A2().lieu = 'chastel';
                         retenir('caleb', "vous avez relevé une maison, ce qui fait de vous un concurrent");
                         retenir('charles', "vous avez déclaré publiquement une maison de Parias"); },
           exploit:{ eclat:16, temoins:'province', quoi:"la maison Karlsberg est relevée au registre du bailliage" },
           marque:"Les Bannières du Loup sont relevées, enregistrées au volume cent-quarante-trois. Alycia est partie seule.",
           court:"Les Bannières" },
  suite:'a2_carte', libelleSuite:"La carte" },

kar_bruler:{
  qui:'alycia',
  texte:[
    "On emporte les trois choses et on brûle le reste.",
    { sobre:"Il y a beaucoup à brûler et ça prend deux jours.",
      intense:"Il y a beaucoup plus à brûler qu'on ne croyait : sous le coffre, dans un renfoncement, il y a onze caisses de correspondance — quarante ans de lettres reçues, celles dont le registre n'était que la copie des réponses. Ça prend deux jours et il faut sortir chaque caisse au jour parce qu'on ne fait pas de feu dans une crypte.",
      extreme:"Il y a beaucoup plus à brûler qu'on ne croyait. Sous le coffre, dans un renfoncement qu'on ne voit qu'accroupi, onze caisses de correspondance : quarante ans de lettres **reçues**, celles dont le registre de votre père n'était que la copie des réponses. Il faut les monter une par une par l'escalier ouest, quatre-vingts pieds, et faire le feu dehors, parce qu'on ne fait pas de feu dans une crypte sans conduit — et parce qu'il faut voir brûler." },
    "§ Vous lisez pendant deux jours et vous brûlez au fur et à mesure. C'est la seule façon : lire d'abord tout puis brûler, personne n'y arrive.",
    "Il y a là-dedans quarante ans d'une maison. Des dettes, des mariages, une querelle de bornage avec Chastel qui a duré onze ans, la commande d'un cheval, la mort d'un enfant en bas âge dont vous n'aviez jamais entendu parler et qui aurait été votre frère.",
    "Et onze maisons qui écrivaient à la vôtre, dont trois qui existent encore.",
    "« Vous en gardez combien ? » demande Alycia le deuxième soir.",
    "« Trois lettres. »",
    "« Sur quarante ans. »",
    "« Sur quarante ans. »",
    "§ Le reste part en deux jours de feu, dans une cour où poussent des frênes de vingt pieds.",
    "Personne ne lira jamais ce que quelqu'un d'autre aurait pu lire ici. C'était l'idée, et c'est fait, et ça ne se défait pas.",
  ],
  effets:{ flags:['kar_brule','kar_trois_lettres'], cout:{ moral:12 },
           faire:() => { bouger('alycia', { relation:2, confiance:2 }); A2().lieu = 'karlsberg'; A2().pistes.sang = Math.max(A2().pistes.sang, 3); },
           exploit:{ eclat:2, temoins:'aucun', quoi:"quarante ans d'une maison sont partis en deux jours de feu" },
           marque:"Vous avez brûlé quarante ans de correspondance de Karlsberg. Vous en avez gardé trois lettres.",
           court:"Trois lettres" },
  suite:'a2_carte', libelleSuite:"La carte" },

};
Object.assign(KARLS, KARLS_4);
enregistrerScenes(KARLS);
