/* PARIAS — Acte II · LES TROIS HOMMES, EN ENTIER
 * ═══════════════════════════════════════════════════════════════════════
 * Caleb, Lucius et Charles avaient chacun une rencontre. Ils ont maintenant
 * un arc, et les trois arcs mordent au même endroit : le chantier.
 *
 * C'est le cœur politique de l'acte. Relever une maison n'est pas un
 * problème de pierre — c'est un problème de gens qui n'ont pas envie qu'une
 * maison de Parias se relève, et qui disposent d'instruments beaucoup plus
 * fins qu'une armée.
 *
 *   CALEB    achète. Il ne vous attaque jamais : il achète ce dont vous avez
 *            besoin, avant vous, et vous le revend au prix qu'il décide.
 *   LUCIUS   légitime. Il peut vous donner un titre qu'aucun bailliage ne
 *            peut vous retirer — au prix d'être le premier à le reconnaître,
 *            lui, comme roi.
 *   CHARLES  vérifie. Il ne hait pas les Parias : il protège les hommes de
 *            ce qui n'en est pas, et il n'est pas certain que vous en soyez.
 *
 * Aucun des trois n'est un méchant. Deux d'entre eux ont raison sur
 * l'essentiel, et c'est ce qui rend l'acte politique au lieu de martial.
 * ═══════════════════════════════════════════════════════════════════════ */

const POLITIQUE = {

/* ══ CALEB — CELUI QUI ACHÈTE ═════════════════════════════════════════════ */

cb_creances:{
  qui:'caleb',
  lieu:() => `Fort-aux-Princes · le cabinet · ${dateA2()}`,
  titre:"Ce qu'il a acheté ce trimestre",
  texte:[
    "Le cabinet des créances de Fort-aux-Princes occupe deux pièces, emploie quatre clercs, et n'a pas d'armes au mur.",
    { sobre:"Caleb vous reçoit avec un état.",
      intense:"Caleb de Fort-aux-Princes vous reçoit avec un état de quatre pages, qu'il a fait établir avant votre arrivée parce qu'il savait que vous viendriez.",
      extreme:"Caleb de Fort-aux-Princes vous reçoit debout, avec un état de quatre pages qu'il a fait établir la semaine précédente. Il n'a pas su que vous veniez : il a su que vous viendriez, ce qui n'est pas la même compétence et se paie beaucoup plus cher. Il tourne l'état vers vous, à l'endroit, comme on présente un contrat." },
    "« Vous montez quelque chose aux Marches Grises. »",
    "« Oui. »",
    "« Avec de la pierre, des bras et du grain, et sans un sou d'or, ce qui est remarquable et ce dont je vous fais compliment sincèrement. » Il pose un doigt sur la page. « Malheureusement, ce n'est pas comme ça que ça marche. »",
    "§ Sur l'état : les onze fournisseurs qui montent quelque chose chez vous.",
    "Le charretier de Bourg-l'Aigre. Le maréchal. Les deux carriers d'Estrées. Le charpentier de la vallée basse. Le meunier qui vous vend le grain que vous ne produisez pas encore.",
    "En face de chaque nom, un chiffre. En face de sept d'entre eux, une date : celle où Caleb a racheté leur dette.",
    { sobre:"« Sept sur onze », dit-il.",
      intense:"« Sept sur onze », dit-il, sans triomphe, du ton dont on annonce un relevé de pluie. « Ce trimestre. Le trimestre prochain, neuf. »",
      extreme:"« Sept sur onze », dit-il, sans le moindre triomphe, exactement du ton dont on annonce un relevé de pluviométrie. « Ce trimestre-ci. Le trimestre prochain, neuf — le charpentier a une fille à marier et le meunier a une meule fendue, donc les deux emprunteront avant Frimaire, et je serai là. Je ne les menace pas, je ne leur demande rien, je ne leur parle même pas de vous. J'achète leur dette au pair, ce qui est un bon prix pour eux, et j'attends. »" },
    "« Et ensuite ? »",
    "« Ensuite rien. C'est tout l'intérêt. » Il referme l'état. « Je n'ai pas besoin d'appeler ma créance, messire. Il me suffit qu'ils sachent que je l'ai. Un homme qui doit trois cents couronnes à Fort-aux-Princes ne refuse pas de vous livrer : il livre plus tard, il livre moins bien, il augmente un peu, et il ne sait pas lui-même pourquoi il le fait. »",
    "§ C'est une guerre. Elle ne comporte aucune violence, aucune illégalité, et il n'y a rien à en dire à un tribunal.",
    "« Pourquoi ? »",
    "« Parce qu'une maison neuve dans les Marches Grises fait baisser la valeur de tout ce que je possède au nord, de onze à quatorze pour cent selon les années. » Il hausse une épaule. « Ce n'est pas contre vous. Je ne vous connais pas. Si vous étiez mort demain je n'en éprouverais rien du tout, et si vous devenez utile je vous financerai moi-même. »",
  ],
  effets:{ flags:['cb_creances','a2_caleb_vu','a2_caleb_pression'],
           faire:() => { const C = CHANTIER(); C.pierre = Math.max(0, C.pierre - 3); C.grain = Math.max(0, C.grain - 3);
                         retenir('caleb', "il est venu voir l'état de ses fournisseurs, ce qui prouve qu'il compte"); },
           marque:"Caleb a racheté la dette de sept de vos onze fournisseurs. Il n'appellera pas ses créances : il lui suffit qu'elles existent.",
           court:"Sept sur onze" },
  choix:[
    { t:"« Combien pour les onze ? »",
      detail:"racheter les créances · c'est ce qu'il attend et il l'a chiffré",
      requisOr:900, risque:"calculé", va:'cb_racheter' },

    { t:"« Qu'est-ce que vous voulez ? »",
      detail:"la question directe · un marchand y répond toujours",
      risque:"calculé", va:'cb_veut' },

    { t:"« Alors je bâtirai avec des gens qui ne vous doivent rien. »",
      detail:"les Nains, les Khesh, les Parias · personne qui ait un compte à Fort-aux-Princes",
      risque:"définitif", ferme:"Ferme : les onze fournisseurs de la province",
      va:'cb_ailleurs' },

    { t:"Le menacer",
      detail:"il n'y a pas d'armes au mur, et il y a quatre clercs qui écrivent",
      risque:"dangereux", va:'cb_menace' },
  ],
},

cb_racheter:{
  qui:'caleb',
  titre:"Neuf cents couronnes",
  texte:[
    "« Combien pour les onze ? »",
    "Il donne le chiffre sans consulter l'état, ce qui veut dire qu'il l'avait préparé.",
    "« Neuf cents. »",
    "« C'est trois fois le pair. »",
    "« C'est deux fois et demie, et vous les paierez, parce que la seule chose qui vaille moins qu'une créance qu'on ne peut pas appeler, c'est un chantier qu'on ne peut pas approvisionner. »",
    "§ Il a raison sur le chiffre et il a raison sur le reste.",
    "Vous payez. Les quatre clercs mettent une heure à établir les actes de cession, et Caleb les signe tous les onze de la même main régulière, sans en relire un seul.",
    { sobre:"« Vous n'êtes pas fâché », constatez-vous.",
      intense:"« Vous n'avez pas l'air fâché », constatez-vous en signant le dernier.\n\n« Pourquoi le serais-je ? J'ai acheté onze créances au pair et je les ai revendues à deux et demie. C'est ma meilleure opération du trimestre. »",
      extreme:"« Vous n'avez pas l'air fâché », constatez-vous en signant le dernier acte.\n\n« Pourquoi diable le serais-je ? » Il a l'air sincèrement surpris qu'on le lui demande. « J'ai acheté onze créances au pair il y a quatre mois, je les revends à deux et demie aujourd'hui, en une heure, sans risque et sans un mot plus haut que l'autre. C'est ma meilleure opération du trimestre et de loin. Vous croyiez quoi — que je voulais votre ruine ? Je veux un rendement, messire. Votre ruine ne rapporte rien du tout. »" },
    "« Et si je n'avais pas payé ? »",
    "« Alors j'aurais gardé les créances et vous auriez mis six ans au lieu de trois. » Il range sa plume. « Les deux me convenaient. C'est ça, une bonne position. »",
  ],
  effets:{ or:-900, flags:['cb_rachete','a2_caleb_paye'],
           faire:() => retenir('caleb', "il a payé neuf cents couronnes sans marchander, ce qui me dit ce qu'il a"),
           exploit:{ eclat:4, temoins:'quelques', quoi:"onze créances rachetées en une heure" },
           marque:"Neuf cents couronnes pour onze créances. Sa meilleure opération du trimestre, et il l'a dit.",
           court:"Neuf cents" },
  plusTard:"Il sait maintenant que vous pouviez payer neuf cents couronnes. C'est une information qu'il n'avait pas ce matin.",
  suite:'cb_quarante', libelleSuite:"Il n'a pas fini" },

cb_veut:{
  qui:'caleb',
  titre:"Ce qu'il veut",
  texte:[
    "« Qu'est-ce que vous voulez ? »",
    { sobre:"« Bonne question. Enfin. »",
      intense:"« Bonne question », dit-il. « Enfin. Vous n'imaginez pas le nombre de gens qui viennent ici me menacer avant de la poser. »",
      extreme:"« Bonne question », dit-il, et pour la première fois il s'assoit. « Enfin. Vous n'imaginez pas le nombre de seigneurs de cette province qui viennent dans cette pièce, découvrent que je tiens leurs fournisseurs, et passent une demi-heure à me menacer avant de poser la seule question qui pouvait leur servir à quelque chose. Trois sur quatre. Et ce sont des gens qui ont hérité de terres. »" },
    "Il retourne l'état et écrit trois lignes au dos.",
    "**Une.** Que Karlsberg ne lève jamais de péage sur la voie de la vallée. « Vous êtes en travers de ma route du nord. C'est tout mon problème et c'est mon seul problème. »",
    "**Deux.** Qu'il ait un droit de préemption sur ce que produit votre forge, au prix du marché. « Pas un privilège. Un droit de premier refus. »",
    "**Trois.** Que si Karlsberg tombe, ce qui en reste lui revienne avant tout autre créancier.",
    "§ Les trois sont raisonnables. La troisième est un couteau.",
    "« Vous pariez sur ma chute. »",
    "« Je me couvre contre elle, ce qui est le contraire. » Il pousse la feuille. « Un homme qui parie sur votre chute la provoque. Un homme qui s'en couvre s'en désintéresse — et je vous garantis que vous préférez la deuxième sorte devant chez vous. »",
  ],
  effets:{ flags:['cb_termes','a2_caleb_vu'],
           marque:"Trois clauses : pas de péage, préemption sur la forge, et ce qui reste de Karlsberg si elle tombe.",
           court:"Trois lignes au dos" },
  choix:[
    { t:"Signer les trois",
      detail:"la route reste franche · et il cesse d'acheter vos fournisseurs",
      risque:"définitif", ferme:"Ferme : le péage de la vallée, et ce qui reste si vous tombez",
      definitif:true, va:'cb_signe' },
    { t:"Signer les deux premières",
      detail:"refuser la troisième · et voir s'il tient à sa couverture",
      risque:"calculé", va:'cb_deux' },
    { t:"Ne rien signer",
      detail:"garder le péage · il vaudra un jour bien plus que trois cents couronnes l'an",
      risque:"définitif", ferme:"Ferme : la paix marchande avec Fort-aux-Princes",
      va:'cb_ailleurs' },
  ],
},

cb_signe:{
  qui:'caleb',
  titre:"Trois clauses",
  texte:[
    "Vous signez les trois. Les quatre clercs font trois expéditions, dont une pour le bailliage.",
    { sobre:"Le lendemain, la route est franche.",
      intense:"Le lendemain, ses convois passent chez vous sans payer, et les vôtres descendent à Fort-aux-Princes sans être fouillés. En quatre jours, le grain arrive.",
      extreme:"Le lendemain matin, ses convois passent par la voie de la vallée sans payer un sou, et les vôtres descendent à Fort-aux-Princes sans être fouillés à l'entrée — ce qui, découvrez-vous, était le vrai coût de la situation précédente : deux heures par charroi, à chaque fois, depuis huit mois. En quatre jours le grain arrive. En trois semaines, deux carriers d'Estrées demandent à travailler pour vous à l'année." },
    "§ Une route franche vaut, en pratique, plus qu'un péage. Il le savait et il vous l'a laissé découvrir seul, ce qui est sa façon de faire une faveur.",
    "La troisième clause dort dans un tiroir de bailliage.",
    "Elle y dormira dix ans. Puis un jour, quelqu'un l'en sortira, et ce jour-là vous serez peut-être mort.",
  ],
  effets:{ flags:['cb_signe','a2_route_franche','a2_caleb_pacte'],
           faire:() => { retenir('caleb', "il a signé les trois, dont la troisième, ce que peu font"); },
           exploit:{ eclat:5, temoins:'quelques', quoi:"la voie de la vallée est franche" },
           marque:"Trois clauses signées. La route est franche. La troisième dort au bailliage.",
           court:"La route franche" },
  plusTard:"Si Karlsberg tombe, ce qui en reste va d'abord à Fort-aux-Princes. C'est écrit et c'est déposé.",
  suite:'cb_quarante', libelleSuite:"Il n'a pas fini" },

cb_deux:{
  qui:'caleb',
  titre:"Deux sur trois",
  texte:[
    "« Les deux premières. Pas la troisième. »",
    { sobre:"Il ne discute pas.",
      intense:"Il ne discute pas une seconde, ce qui vous inquiète immédiatement — un marchand qui ne discute pas une clause qu'il a écrite lui-même vient d'apprendre quelque chose.",
      extreme:"Il ne discute pas une seule seconde. Il raye la troisième ligne, paraphe la rature, fait recopier. Et c'est précisément ce qui devrait vous inquiéter : un marchand qui ne défend pas une clause qu'il a écrite de sa main vient soit d'obtenir ce qu'il voulait ailleurs, soit d'apprendre quelque chose qui vaut plus que la clause." },
    "« Vous refusez de vous couvrir contre ma chute », dit-il en signant.",
    "« Je refuse de la mettre par écrit. »",
    "« C'est la même chose et ce n'est pas grave. » Il rend la plume. « Vous venez de me dire que vous croyez tenir. Les hommes qui croient tenir empruntent moins, se défendent mieux, et durent plus longtemps. Je révise votre notation à la hausse, messire, et ça vous coûtera moins cher que la clause. »",
    "§ Vous venez de gagner une négociation contre un homme qui compte, et vous n'arrivez pas à vous en réjouir.",
    "La route est franche à partir de Frimaire.",
  ],
  effets:{ flags:['cb_deux','a2_route_franche','a2_caleb_pacte'],
           faire:() => retenir('caleb', "il a refusé la troisième clause, donc il croit tenir, donc il tiendra"),
           exploit:{ eclat:6, temoins:'quelques', quoi:"deux clauses sur trois, et la route franche quand même" },
           marque:"Deux clauses sur trois. Il n'a pas discuté la rature et il a révisé votre notation à la hausse.",
           court:"Deux sur trois" },
  suite:'cb_quarante', libelleSuite:"Il n'a pas fini" },

cb_ailleurs:{
  qui:'caleb',
  titre:"Sans lui",
  texte:[
    "« Alors je bâtirai avec des gens qui ne vous doivent rien. »",
    { sobre:"Il réfléchit sérieusement.",
      intense:"Il réfléchit sérieusement, et il fait le calcul devant vous, à voix haute, parce que c'est un homme qui pense mieux en parlant.",
      extreme:"Il réfléchit sérieusement, et il fait le calcul devant vous à voix haute, parce que c'est un homme qui pense mieux en parlant et qui n'a jamais eu besoin de cacher son raisonnement à qui que ce soit." },
    "« Des Nains sans montagne, des Khesh qui vous doivent de l'eau, quarante et un Parias que personne ne peut identifier, et une elfe qui ne détourne pas les yeux. » Il hoche la tête. « Oui. Ça peut marcher. Ce sont exactement les quatre populations sur lesquelles je n'ai aucune prise, et vous êtes le seul homme des quatre provinces à les avoir toutes les quatre. »",
    "« Alors ? »",
    "« Alors vous bâtirez plus lentement, plus cher, et sans jamais pouvoir acheter un essieu à trois lieues de chez vous. » Il se rassoit. « Et vous aurez une maison qui ne doit rien à personne d'ici, ce qui est très exactement ce que la province ne pardonne pas. Je vous souhaite bonne chance sincèrement. Ce sera intéressant à regarder. »",
    "§ Il ne vous fait pas la guerre. Il vous retire simplement de son marché, et il n'y a rien à en dire.",
    "Onze fournisseurs cessent progressivement de livrer. Aucun ne rompt : ils livrent plus tard, moins bien, et un peu plus cher, exactement comme il l'avait décrit.",
  ],
  effets:{ flags:['cb_sans','a2_caleb_froid'],
           faire:() => { const C = CHANTIER(); C.pierre = Math.max(0, C.pierre - 4); C.grain = Math.max(0, C.grain - 4);
                         retenir('caleb', "il a refusé mon marché en face, poliment, et il avait les moyens de le faire"); },
           marque:"Vous bâtirez sans la province. Onze fournisseurs livrent plus tard, moins bien, un peu plus cher.",
           court:"Sans la province" },
  plusTard:"Vous ne pouvez plus acheter un essieu à trois lieues de chez vous. Tout doit venir de plus loin.",
  suite:'a2_carte', libelleSuite:"La carte" },

cb_menace:{
  qui:'caleb',
  titre:"Quatre clercs qui écrivent",
  texte:[
    { sobre:"Vous vous avancez. Les quatre clercs ne lèvent pas la tête.",
      intense:"Vous vous avancez d'un pas. Les quatre clercs ne lèvent pas la tête — ils continuent d'écrire, tous les quatre, sans un temps d'arrêt, et c'est ça qui vous arrête.",
      extreme:"Vous vous avancez d'un pas et vous laissez la phrase se former. Les quatre clercs ne lèvent pas la tête. Ils continuent d'écrire, tous les quatre, sans un temps d'arrêt, sans un regard, et c'est très exactement ça qui vous arrête net : ils ont déjà vu ça. Souvent. Ça fait partie de la journée de travail, comme la pluie." },
    "Caleb ne bouge pas non plus.",
    "« Vous pouvez me tuer », dit-il. « Ça se fait, c'est même arrivé à mon père. Je vais vous décrire le lendemain, parce que personne ne le fait jamais et que c'est instructif. »",
    "« Ce ne sera pas nécessaire. »",
    "« Si. » Il compte sur ses doigts. « Un : mes créances ne meurent pas avec moi, elles passent à ma nièce, qui a vingt-six ans et beaucoup moins de patience que moi. Deux : les quatre hommes qui écrivent derrière vous témoigneront, et un cabinet des créances est le seul endroit de cette province où le témoignage de quatre clercs vaut celui d'un noble. Trois : Fort-aux-Princes appelle ses créances toutes en même temps, ce que je ne fais jamais, et onze fournisseurs vous ferment leur porte le même jeudi. »",
    "§ Il n'a pas haussé la voix une seule fois.",
    "« Vous êtes un homme d'armes, messire, et un bon, à ce qu'on m'écrit. Ici, ça ne sert à rien du tout. C'est très désagréable et vous vous y ferez. »",
  ],
  effets:{ flags:['cb_menace','a2_caleb_hostile'], suspicion:6,
           faire:() => { bouger('alycia', { confiance:-1 });
                         retenir('caleb', "il m'a menacé dans mon cabinet, devant quatre clercs, ce qui était stupide"); },
           marque:"Vous l'avez menacé. Les quatre clercs n'ont pas levé la tête et il vous a décrit le lendemain.",
           court:"Quatre clercs" },
  suite:'cb_veut', libelleSuite:"« Qu'est-ce que vous voulez ? »" },

cb_quarante:{
  qui:'caleb',
  lieu:() => `Karlsberg · ${dateA2()}`,
  titre:"Quarante hommes",
  texte:[
    "Ils arrivent une saison plus tard, sans prévenir, un matin : quarante hommes en ordre, avec un sergent, des outils, et pas une bannière.",
    { sobre:"Il n'y a pas de lettre.",
      intense:"Le sergent n'a pas de lettre. Il a un ordre verbal de trois phrases, qu'il récite exactement comme on le lui a donné, et il n'en sait pas plus que vous.",
      extreme:"Le sergent n'a pas de lettre — c'est la première chose que vous vérifiez et c'est la première chose qui cloche. Il a un ordre verbal en trois phrases, qu'il récite mot pour mot, du ton d'un homme qui l'a répété quatre fois sur la route pour ne pas se tromper, et qui n'en sait strictement pas plus que vous sur ce que ça veut dire." },
    "« Messire de Fort-aux-Princes met quarante hommes à la disposition de Karlsberg. »",
    "« Pour quelle durée ? »",
    "« Il n'a pas dit. »",
    "« À quelles conditions ? »",
    "« Il a dit : sans conditions. »",
    "§ Quarante hommes sans bannière, sans lettre et sans conditions.",
    { sobre:"C'est le plus beau cadeau de l'acte et c'est un piège parfait.",
      intense:"C'est le plus beau cadeau qu'on vous ait fait, et c'est un piège parfait — parfait au sens technique : il n'y a aucun crochet, aucun fil, rien à refuser précisément.",
      extreme:"C'est le plus beau cadeau qu'on vous ait fait de toute votre vie, et c'est un piège parfait au sens technique du terme : il n'y a aucun crochet, aucun fil, aucune clause, rien de précis à refuser. Quarante hommes payés par un autre, qui bâtissent vos murs et qui, si un jour on leur demande à qui ils obéissent, répondront la vérité — et la vérité n'est pas *à Karlsberg*." },
    "Ils travaillent bien. Ils travaillent même très bien : ce sont des gens de Fort-aux-Princes, habitués aux chantiers, encadrés, réguliers.",
    "En deux saisons, ils montent plus de mur que les vôtres en un an.",
  ],
  choix:[
    { t:"Les garder",
      detail:"quarante bras · et une garnison qui n'est pas à vous dans vos propres murs",
      risque:"définitif", ferme:"Ferme : la certitude de savoir à qui obéissent vos murs",
      definitif:true, va:'cb_garder' },

    { t:"Les garder, et les payer",
      detail:"les prendre à votre solde · ce qui coûte, et ce qui tranche la question",
      requisOr:500, risque:"calculé", definitif:true, va:'cb_payer' },

    { t:"Les renvoyer",
      detail:"quarante hommes qui repartent · et un homme qui note",
      risque:"définitif", ferme:"Ferme : deux saisons de mur", definitif:true, va:'cb_renvoyer' },
  ],
},

cb_garder:{
  qui:'caleb',
  titre:"Ce que vous ne saurez jamais",
  texte:[
    "Vous les gardez.",
    { sobre:"Ils restent trois ans.",
      intense:"Ils restent trois ans. Ils montent l'enceinte, une partie du donjon, la moitié du bourg. Douze d'entre eux se marient dans la vallée.",
      extreme:"Ils restent trois ans. Ils montent l'enceinte basse en entier, la moitié du donjon, une bonne part du bourg. Douze d'entre eux se marient dans la vallée, quatre y font des enfants, et le sergent — qui s'appelle Ambroise, qui a quarante-trois ans et une hanche qui le fait boiter par temps humide — finit par appeler Karlsberg *chez nous* sans y penser, un soir de Nivôse, devant témoins." },
    "Vous ne saurez jamais s'ils sont à vous.",
    "§ C'est la seule chose que Caleb ait vraiment achetée : pas les hommes, le doute.",
    "Il ne les rappellera pas. Il n'écrira pas. Il ne fera absolument rien, pendant des années, et vous regarderez quarante hommes monter vos murs en vous demandant chaque matin ce qui se passerait s'il écrivait.",
    "« Ils sont à nous », dit Ambroise, la seule fois où vous le lui demandez.",
    "« Vous en êtes sûr ? »",
    "« Non », dit-il, et il retourne à son mur, parce que c'est un honnête homme et qu'il ne va pas mentir sur une chose pareille.",
  ],
  effets:{ flags:['cb_garde','a2_caleb_quarante','a2_garnison','a2_caleb_dedans'],
           faire:() => { const C = CHANTIER(); C.bras += 6; C.pierre += 4;
                         retenir('caleb', "il a gardé mes quarante hommes, ce qui vaut mieux qu'un contrat"); },
           exploit:{ eclat:6, temoins:'quelques', quoi:"quarante hommes de Fort-aux-Princes montent vos murs" },
           marque:"Quarante hommes gardés. Vous ne saurez jamais s'ils sont à vous, et c'est ça qu'il a acheté.",
           court:"Quarante hommes" },
  plusTard:"Il n'écrira pas. C'est le fait qu'il pourrait écrire qui est l'instrument.",
  suite:'a2_carte', libelleSuite:"La carte" },

cb_payer:{
  qui:'caleb',
  titre:"Cinq cents couronnes pour trancher",
  texte:[
    "Vous les prenez à votre solde. Cinq cents couronnes l'année, versées devant le sergent, avec un rôle nominatif signé des quarante.",
    { sobre:"Trente-quatre signent. Six repartent.",
      intense:"Trente-quatre signent. Six repartent vers Fort-aux-Princes, sans drame, et l'un d'eux vous salue en partant — ce qui est correct, et ce qui vous apprend qu'ils étaient six.",
      extreme:"Trente-quatre signent le rôle. Six repartent vers Fort-aux-Princes le lendemain matin, sans drame, sans un mot de trop, et l'un des six vous salue correctement en montant à cheval. Vous venez d'apprendre le chiffre exact : il y en avait six. Six sur quarante. C'est peu, c'est beaucoup, et surtout c'est un chiffre que vous n'auriez jamais connu si vous ne les aviez pas payés." },
    "§ Trente-quatre hommes qui sont à vous, sans ambiguïté, parce qu'on peut lire leur nom sur un rôle.",
    "Caleb ne commente pas. Sa réponse arrive quatre mois plus tard, en une ligne, dans une lettre qui traite d'autre chose :",
    "*Vous avez payé pour savoir. C'est cher et c'est bien vu.*",
  ],
  effets:{ or:-500, flags:['cb_paye','a2_caleb_quarante','a2_garnison'],
           faire:() => { const C = CHANTIER(); C.bras += 5;
                         retenir('caleb', "il a payé cinq cents couronnes pour lever un doute, ce que je n'avais pas prévu"); },
           exploit:{ eclat:8, temoins:'quelques', quoi:"trente-quatre hommes sur un rôle nominatif" },
           marque:"Trente-quatre signent, six repartent. « Vous avez payé pour savoir. C'est cher et c'est bien vu. »",
           court:"Six sur quarante" },
  suite:'a2_carte', libelleSuite:"La carte" },

cb_renvoyer:{
  qui:'caleb',
  titre:"Quarante hommes qui repartent",
  texte:[
    "Vous les renvoyez le jour même, avec des vivres pour la route et une lettre de remerciement que le sergent transmettra.",
    { sobre:"Ambroise ne comprend pas.",
      intense:"Ambroise ne comprend pas et ne cherche pas à comprendre : c'est un sergent, on lui a dit d'aller, on lui dit de revenir. Ce sont ses hommes qui prennent mal la chose.",
      extreme:"Ambroise ne comprend pas et ne cherche pas à comprendre — c'est un sergent, on lui a dit d'aller, on lui dit de revenir, il notera la date. Ce sont ses hommes qui prennent mal la chose, et il faut voir pourquoi : ils sont arrivés à un chantier où il y avait manifestement du travail pour eux, ils ont regardé le mur pendant une matinée en attendant, et on les renvoie sans qu'ils aient posé une pierre. Un homme de chantier n'a pas de mot pour ça." },
    "§ Vous venez de refuser deux saisons de mur pour une raison que vous ne pouvez expliquer à personne.",
    "La réponse de Caleb met trois mois et tient en une ligne :",
    "*Vous avez refusé quarante hommes gratuits. Je note.*",
    "C'est tout. Il ne dit pas s'il approuve. Il n'approuve ni ne désapprouve : il note, et ce qu'il a noté est que vous préférez perdre du temps à devoir quelque chose.",
    "Vous êtes désormais, dans son état des maisons, dans la colonne de ceux qui ne s'achètent pas.",
    { sobre:"Ce n'est pas forcément une bonne colonne.",
      intense:"Ce n'est pas forcément une bonne colonne. Les gens qui ne s'achètent pas se règlent autrement, et il connaît les autres façons.",
      extreme:"Ce n'est pas forcément une bonne colonne où figurer. Les gens qui s'achètent se gèrent avec de l'argent, ce qui est le moyen le moins coûteux, le moins bruyant et le moins définitif dont dispose un homme comme lui. Ceux qui ne s'achètent pas se règlent autrement. Il connaît les autres façons ; il ne les aime pas ; il les emploie." },
  ],
  effets:{ flags:['cb_renvoye','a2_caleb_note','a2_incorruptible'],
           faire:() => retenir('caleb', "il a renvoyé quarante hommes gratuits — il est dans l'autre colonne"),
           exploit:{ eclat:5, temoins:'quelques', quoi:"quarante hommes renvoyés avec des vivres et une lettre" },
           marque:"« Vous avez refusé quarante hommes gratuits. Je note. » Vous êtes dans la colonne de ceux qui ne s'achètent pas.",
           court:"Je note" },
  plusTard:"Ceux qui ne s'achètent pas se règlent autrement. Il connaît les autres façons.",
  suite:'a2_carte', libelleSuite:"La carte" },

/* ══ LUCIUS — CELUI QUI LÉGITIME ══════════════════════════════════════════ */

ls_legitimation:{
  qui:'lucius',
  lieu:() => `Astrah · la salle des rôles · ${dateA2()}`,
  titre:"Ce qu'un trône vide peut donner",
  texte:[
    "La salle des rôles d'Astrah contient quatre mille registres et deux personnes.",
    { sobre:"Lucius vous y reçoit seul.",
      intense:"Lucius Furius Augustus vous y reçoit seul, sans secrétaire, ce qu'il ne fait avec personne — et c'est le premier terme de la négociation, offert avant qu'elle commence.",
      extreme:"Lucius Furius Augustus vous reçoit seul dans la salle des rôles, sans secrétaire, sans témoin, ce qu'il ne fait avec personne et dont trois provinces parleraient si elles le savaient. C'est le premier terme de la négociation et il vous l'offre avant qu'elle commence : *je vous parle sans témoins, donc je vous parle vraiment, donc vous me devez d'écouter*. C'est très bien joué et il ne s'en cache pas une seconde." },
    "« Votre relèvement de titre est enregistré au bailliage de Chastel », dit-il. « Volume cent-quarante-trois. »",
    "« Vous l'avez lu. »",
    "« J'en ai une copie. » Il pose la main sur un registre beaucoup plus vieux. « Savez-vous ce qu'est un relèvement de bailliage, messire ? C'est une inscription de province. Elle vaut ce que vaut la province, et une province, ça se remplace. »",
    "§ Il ouvre le vieux registre. C'est un rôle royal d'Astrah, tenu jusqu'à quarante ans en arrière, puis rien.",
    "« Ceci vaut autre chose. Une maison inscrite ici n'est pas relevée par une province : elle est **reconnue par une couronne**. Aucun bailliage au monde ne peut rayer une ligne d'un rôle royal. Ils n'en ont pas le pouvoir — c'est une question de hiérarchie des actes, ça se plaide en une demi-heure, et ça a été plaidé onze fois. »",
    "« Il n'y a pas de roi à Astrah. »",
    { sobre:"« Pas encore. »",
      intense:"« Pas encore », dit-il, et c'est la première fois qu'il le dit tout haut à quelqu'un qui n'est pas de sa maison.",
      extreme:"« Pas encore », dit-il — et il le dit très simplement, sans emphase, en refermant le registre. C'est la première fois qu'il prononce ces deux mots devant quelqu'un qui n'est pas de sa maison, et il vient de mettre sa vie entre vos mains, ce dont vous prenez conscience avec un temps de retard désagréable." },
    "« Vous me proposez d'inscrire Karlsberg à un rôle royal qui n'a pas de roi. »",
    "« Je vous propose d'être inscrit le jour où il en aura un. Première page, première ligne, à la reprise du rôle. » Il vous regarde. « La première maison reconnue par la couronne restaurée d'Astrah. Ce n'est pas une faveur, messire. C'est une place dans l'histoire, et elle est libre. »",
    "« Et ce que vous voulez ? »",
    "« Que vous soyez là. »",
  ],
  choix:[
    { t:"« Là comment ? »",
      detail:"faire préciser · un homme comme lui a déjà tout précisé",
      risque:"prudent", va:'ls_prix' },
    { t:"« Non. Une couronne qu'on se donne n'est pas une couronne. »",
      detail:"le dire dans la salle des rôles, sans témoins · à un homme qui vient de s'exposer",
      risque:"définitif", ferme:"Ferme : le rôle royal, et la protection qu'il vaut",
      va:'ls_refus' },
    { t:"« Pourquoi moi ? »",
      detail:"il y a onze maisons rayées et vingt-cinq maisons vivantes · pourquoi la plus faible",
      risque:"calculé", va:'ls_pourquoi' },
  ],
},

ls_pourquoi:{
  qui:'lucius',
  titre:"Pourquoi vous",
  texte:[
    "« Pourquoi moi ? Il y a vingt-cinq maisons dans cette province et vingt-quatre sont plus fortes que la mienne. »",
    { sobre:"« C'est exactement pour ça. »",
      intense:"« C'est exactement pour ça, et je vais vous le dire crûment parce que vous n'êtes pas idiot et que la flatterie vous ferait perdre du temps. »",
      extreme:"« C'est exactement pour ça, et je vais vous le dire crûment, parce que vous n'êtes pas idiot, que la flatterie vous ferait perdre trois quarts d'heure, et que j'ai constaté qu'avec les hommes de votre sorte la brutalité est en réalité la forme de respect la moins coûteuse. »" },
    "Il compte, comme Caleb, mais sur les registres au lieu des doigts.",
    "**Une.** « Une maison forte qui me reconnaît roi me fait un rival. Une maison faible me fait un précédent. J'ai besoin d'un précédent, pas d'un pair. »",
    "**Deux.** « Une maison rayée qui se relève est le meilleur argument possible pour une couronne qui se relève. Vous êtes ma démonstration. Vingt ans de ronces, et un donjon. »",
    "**Trois.** « Et vous êtes un Paria. »",
    "§ Il le dit sans changer de ton, et il n'y a pas de question dans sa voix.",
    "« Je n'ai pas dit ça. »",
    "« Non. Moi si. » Il écarte les mains. « Je m'en moque absolument, ce qui est ma quatrième raison. Les vingt-quatre autres maisons ne s'en moquent pas. Le jour où ça se saura — et ça se saura, messire, un donjon de quatre étages ne reste pas anonyme — vous n'aurez plus qu'un seul allié possible dans quatre provinces, et ce sera celui à qui ça ne fait rien. »",
    "« Ça ne vous fait rien. »",
    { sobre:"« Non. Astrah a eu trois rois de l'Onde. »",
      intense:"« Non. Astrah a eu trois rois de l'Onde en quatre cents ans, et le dernier est celui dont j'ai fait relever la tombe l'an dernier, à mes frais, avec beaucoup de monde et beaucoup de discours. » Il sourit très légèrement. « Personne n'a fait le rapprochement. »",
      extreme:"« Non. Astrah a eu trois rois de l'Onde en quatre cents ans. Le dernier s'appelait Ceoris et c'est sa tombe que j'ai fait relever l'année dernière, à mes frais, avec beaucoup de monde, beaucoup de discours et un chapelain de province qui a lu un texte que j'avais écrit. » Il sourit, très légèrement, pour la première fois de l'entretien. « Personne n'a fait le rapprochement. Trois cents personnes présentes, quatre chroniqueurs, et pas un seul. J'ai trouvé ça extrêmement instructif sur ce que les gens regardent. »" },
  ],
  effets:{ flags:['ls_pourquoi','a2_lucius_sait','a2_lucius_vu'], suspicion:10,
           faire:() => retenir('lucius', "il sait que je sais, et il ne s'est pas levé pour partir"),
           marque:"Lucius sait ce que vous êtes et s'en moque. Astrah a eu trois rois de l'Onde ; il a fait relever la tombe du dernier.",
           court:"Ceoris" },
  suite:'ls_prix', libelleSuite:"« Là comment ? »" },

ls_prix:{
  qui:'lucius',
  titre:"Le prix",
  texte:[
    "« Là comment ? »",
    "« Debout, à ma droite, le jour du couronnement, avec vos couleurs. »",
    "« C'est tout ? »",
    { sobre:"« C'est tout, et c'est énorme. »",
      intense:"« C'est tout, et vous ne mesurez pas ce que c'est. Une couronne ne se prend pas : elle se reconnaît. Il faut quelqu'un qui soit là et qui ne parte pas. »",
      extreme:"« C'est tout, et vous ne mesurez visiblement pas ce que c'est, ce qui est normal — personne ne le mesure avant d'avoir vu une salle vide. Une couronne ne se prend pas, messire. Elle ne se conquiert pas non plus, on raconte n'importe quoi là-dessus depuis quatre siècles. Elle se **reconnaît**. Il faut qu'il y ait des gens dans la salle, debout, avec leurs couleurs, qui ne sortent pas. C'est tout ce qui distingue un roi d'un homme avec un cercle de métal sur la tête, et c'est extraordinairement difficile à obtenir. »" },
    "« Combien en avez-vous ? »",
    "« Trois maisons du sud, qui ont signé pour des raisons de grenier et qui repartiront si ça tourne. » Il ne se ment pas à lui-même, ce qui est sa qualité et son danger. « Il m'en faut sept. »",
    "§ Il y a une deuxième partie et il l'annonce sans transition, ce qui est sa manière de dire qu'elle n'est pas négociable.",
    "« Et cent hommes pendant deux saisons, l'année du couronnement. Pas pour se battre : pour tenir les portes d'Astrah pendant que ça se fait. Si la cérémonie est interrompue, elle n'a pas lieu, et si elle n'a pas lieu une fois, elle n'a lieu jamais. »",
    "« Cent hommes pendant deux saisons, c'est mon chantier arrêté un an. »",
    "« Oui », dit-il. « Et une ligne à la première page d'un rôle royal, que ni Chastel, ni Mont-Draken, ni Fort-aux-Princes ne pourront jamais rayer. Vous mettez un an de pierre en face d'un titre inattaquable. C'est un très bon prix et vous le savez. »",
  ],
  choix:[
    { t:"Accepter. Être là, avec cent hommes.",
      detail:"un an de chantier arrêté · et la première ligne d'un rôle royal",
      risque:"définitif", ferme:"Ferme : la neutralité de Karlsberg dans la question d'Astrah",
      definitif:true, va:'ls_couronnement' },

    { t:"Être là, sans les cent hommes",
      detail:"la reconnaissance sans la garde · voir si le symbole lui suffit",
      risque:"calculé", va:'ls_symbole' },

    { t:"« Faites-vous couronner. Je viendrai après. »",
      detail:"reconnaître un roi qui l'est déjà ne coûte rien · et ne vaut rien",
      risque:"calculé", va:'ls_apres' },

    { t:"Refuser",
      detail:"une couronne qu'on se donne n'est pas une couronne",
      risque:"définitif", ferme:"Ferme : le rôle royal, et la protection qu'il vaut",
      definitif:true, va:'ls_refus' },
  ],
},

ls_couronnement:{
  qui:'lucius',
  lieu:"Astrah · la salle du trône · deux ans plus tard",
  titre:"Debout, à sa droite",
  texte:[
    "Cent hommes pendant deux saisons. Le chantier de Karlsberg s'arrête onze mois ; l'enceinte reste ouverte sur quarante pieds tout un hiver.",
    { sobre:"Le couronnement a lieu un mardi.",
      intense:"Le couronnement a lieu un mardi de Ventôse, dans une salle qui n'avait pas servi depuis quarante ans et qu'il a fallu chauffer trois jours d'avance pour que la pierre ne suinte pas.",
      extreme:"Le couronnement a lieu un mardi de Ventôse, dans une salle qui n'avait pas servi depuis quarante ans. Il a fallu la chauffer trois jours d'avance pour que la pierre cesse de suinter, faire recoudre des tentures qui tombaient en poussière, et trouver quelqu'un qui sache encore l'ordre des choses — ce fut un vieil homme de quatre-vingt-un ans, ancien huissier du dernier roi, qu'on est allé chercher dans un hospice et qui a pleuré du début à la fin sans que personne ose le lui reprocher." },
    "Il y a sept maisons. Six ont signé ; la septième est la vôtre et c'est la seule qui n'ait rien à y gagner de matériel.",
    "§ Vos cent hommes tiennent les quatre portes d'Astrah pendant onze semaines. Il ne se passe rien du tout, ce qui est exactement le résultat recherché.",
    "Vous êtes debout à sa droite. Vous y restez trois heures. Personne ne sort.",
    { sobre:"Puis on rouvre le rôle.",
      intense:"Puis on rouvre le rôle royal d'Astrah, fermé depuis quarante ans, et le vieil huissier de quatre-vingt-un ans écrit la première ligne d'une main qui tremble beaucoup.",
      extreme:"Puis on rouvre le rôle royal d'Astrah — quatre mille pages, fermé sur une ligne inachevée depuis quarante ans — et c'est le vieil huissier de quatre-vingt-un ans qui écrit, parce qu'il est le seul vivant à avoir tenu cette plume-là. Sa main tremble énormément. Ça prend quatre minutes pendant lesquelles trois cents personnes ne font aucun bruit, et l'écriture est mauvaise, et personne n'a jamais rien vu de plus solennel." },
    "**Maison de Karlsberg. Marches Grises. Reconnue.**",
    "§ Un seul mot dans la troisième colonne, et aucun bailliage de ces provinces n'a le pouvoir de le rayer.",
    "Le soir, Lucius vous trouve seul.",
    "« Vous n'aviez rien à y gagner », dit-il.",
    "« Une ligne. »",
    "« Une ligne que je vous aurais donnée de toute façon si vous n'étiez pas venu, parce que j'avais besoin d'un précédent et que vous restiez le meilleur. » Il regarde la salle qui se vide. « Vous êtes venu quand même, avec cent hommes, en arrêtant votre mur. Je ne l'oublierai pas, et je suis un homme qui n'oublie rien : c'est ma seule qualité et c'est celle qui fera de moi un mauvais roi. »",
  ],
  effets:{ flags:['ls_couronne','a2_lucius_couronne','a2_lucius_aide','a2_role_royal','a2_titre_inattaquable'],
           suspicion:14,
           faire:() => { const C = CHANTIER(); C.bras = Math.max(0, C.bras - 8); C.grain = Math.max(0, C.grain - 6);
                         A2().crises.astrah = 4;
                         retenir('lucius', "il est venu avec cent hommes en arrêtant son propre chantier");
                         retenir('caleb', "Karlsberg est au rôle royal d'Astrah, ce que je ne peux pas acheter");
                         retenir('charles', "il a couronné un homme, ce qui le met dans une autre catégorie"); },
           exploit:{ eclat:30, temoins:'province', quoi:"la première maison reconnue par la couronne restaurée d'Astrah" },
           marque:"« Maison de Karlsberg. Marches Grises. Reconnue. » Première ligne du rôle royal rouvert.",
           court:"Reconnue" },
  plusTard:"Astrah a un roi et trois provinces vont passer dix ans à discuter de la nuance, les armes à la main. Vous étiez debout à sa droite.",
  suite:'a2_carte', libelleSuite:"La carte" },

ls_symbole:{
  qui:'lucius',
  titre:"Sans les cent hommes",
  texte:[
    "« Je serai là. Je ne vous donnerai pas cent hommes. »",
    { sobre:"Il réfléchit longtemps.",
      intense:"Il réfléchit longtemps, et vous le voyez peser la chose exactement comme un homme pèse une chose : ce qu'il perd, ce qu'il garde, ce que ça dit.",
      extreme:"Il réfléchit longtemps, debout devant quatre mille registres, et vous le voyez peser la chose comme un homme pèse réellement une chose — pas la mise en scène de la réflexion, la réflexion : ce qu'il perd en sécurité, ce qu'il garde en symbole, et surtout ce que ça dira de lui qu'une maison ait accepté d'être là sans accepter de le garder." },
    "« Vous savez ce que ça signifie, si on l'apprend ? »",
    "« Que je vous reconnais sans vous défendre. »",
    "« Que vous me reconnaissez **et que vous doutez**. » Il hoche la tête. « C'est ce qu'on lira. Et honnêtement, à votre place, je ferais pareil : un an de chantier pour un homme qui n'est pas encore roi, c'est une mise dangereuse. »",
    "« Alors ? »",
    "« Alors j'accepte, parce que six maisons qui signent et une qui vient sans rien devoir, ça se raconte mieux que sept maisons achetées. » Il tend la main. « Vous me coûtez cent hommes et vous me rapportez une phrase. Je prends. »",
    "§ Il vous inscrit au rôle. Pas à la première ligne : à la quatrième.",
    "Il ne le dit pas et il ne s'en excuse pas. C'est exact, c'est mérité, et ça vaut encore infiniment plus qu'un volume de bailliage.",
  ],
  effets:{ flags:['ls_symbole','a2_lucius_couronne','a2_role_royal'], suspicion:8,
           faire:() => { A2().crises.astrah = Math.min(4, (A2().crises.astrah || 0) + 1);
                         retenir('lucius', "il est venu sans ses hommes, ce qui était honnête et un peu vexant"); },
           exploit:{ eclat:16, temoins:'province', quoi:"quatrième ligne du rôle royal d'Astrah" },
           marque:"Quatrième ligne du rôle royal. Il ne l'a pas commenté et c'était mérité.",
           court:"La quatrième ligne" },
  suite:'a2_carte', libelleSuite:"La carte" },

ls_apres:{
  qui:'lucius',
  titre:"Après",
  texte:[
    "« Faites-vous couronner. Je viendrai après. »",
    { sobre:"C'est la seule réponse qui l'atteint.",
      intense:"C'est, de toutes les réponses possibles, la seule qui l'atteigne — et vous le voyez, parce qu'il met une seconde de trop à répondre et qu'il n'en met jamais.",
      extreme:"C'est, de toutes les réponses possibles, la seule qui l'atteigne réellement. Vous le voyez à une chose et une seule : il met une seconde de trop à répondre, et cet homme n'en met jamais. Le refus l'aurait laissé froid — il en a eu dix-huit. L'acceptation lui aurait coûté une dette. Ceci ne lui coûte rien, ne lui donne rien, et le renvoie exactement à ce qu'il craint le plus." },
    "« Vous venez de dire que vous me reconnaîtrez quand je n'aurai plus besoin d'être reconnu. »",
    "« Oui. »",
    "« C'est-à-dire jamais, puisque tout le problème est là. »",
    "« Oui. »",
    "Silence dans la salle des rôles.",
    "« Bien », dit-il enfin. « Vous ne me devez rien, je ne vous dois rien, et vous m'avez fait perdre une matinée en me disant la seule chose vraie que j'entendrai cette année. »",
    "§ Il ne vous en veut pas. Il vous range — dans quelle colonne, on ne le saura que plus tard.",
    "« Revenez quand j'aurai la couronne, messire. Je vous inscrirai quand même, à une ligne moins bonne, et vous saurez pourquoi. »",
  ],
  effets:{ flags:['ls_apres','a2_lucius_vu','a2_lucius_froid'],
           faire:() => retenir('lucius', "il m'a dit la seule chose vraie que j'entendrai cette année et il ne me doit rien"),
           exploit:{ eclat:4, temoins:'aucun', quoi:"vous avez dit à un futur roi ce que personne ne lui dit" },
           marque:"« Vous me reconnaîtrez quand je n'aurai plus besoin de l'être. » Il a mis une seconde de trop à répondre.",
           court:"Une seconde de trop" },
  suite:'a2_carte', libelleSuite:"La carte" },

ls_refus:{
  qui:'lucius',
  titre:"Sans témoins",
  texte:[
    "« Non. Une couronne qu'on se donne n'est pas une couronne. »",
    { sobre:"Il encaisse sans broncher.",
      intense:"Il encaisse sans broncher. Il vient de vous dire, sans témoins, qu'il compte se faire roi ; vous venez de lui répondre non, sans témoins ; et il n'y a strictement rien qu'il puisse faire de ça.",
      extreme:"Il encaisse sans broncher, et c'est le moment le plus dangereux de tout l'entretien. Il vient de vous dire, seul à seul et sans témoin, qu'il compte ceindre une couronne à laquelle il n'a pas droit. Vous venez de lui répondre non. Il n'y a strictement rien qu'il puisse faire de cette situation, sauf une chose, et vous êtes tous les deux en train de penser à cette chose en même temps, dans une salle de quatre mille registres où personne ne vous a vus entrer." },
    "Il fait deux pas et ouvre la porte lui-même, en grand.",
    "« Sortez par la cour d'honneur », dit-il assez fort pour que le couloir l'entende. « Et transmettez mes respects à votre maison. »",
    "§ Il vient de vous faire voir sortant de chez lui par onze personnes.",
    "Ce n'est pas une menace : c'est le contraire. Il vient de se rendre impossible de vous faire disparaître, publiquement, en trois secondes, et sans rien demander en échange.",
    "Sur le seuil : « Vous avez raison, d'ailleurs. Une couronne qu'on se donne n'en est pas une. » Il hausse les épaules. « C'est pour ça qu'il me faut sept maisons. Je regrette que la vôtre n'en soit pas. »",
  ],
  effets:{ flags:['ls_refuse','a2_lucius_refuse','a2_lucius_vu'],
           faire:() => retenir('lucius', "il a refusé en face, sans témoins, et je l'ai fait sortir par la cour d'honneur"),
           exploit:{ eclat:6, temoins:'quelques', quoi:"sorti par la cour d'honneur d'Astrah" },
           marque:"Vous avez refusé. Il vous a fait sortir par la cour d'honneur devant onze témoins, pour rien.",
           court:"La cour d'honneur" },
  suite:'a2_carte', libelleSuite:"La carte" },

/* ══ CHARLES — CELUI QUI VÉRIFIE ══════════════════════════════════════════ */

cd_commission:{
  qui:'charles',
  lieu:() => `Mont-Draken · la cour d'exercice · ${dateA2()}`,
  titre:"La commission",
  texte:[
    "Mont-Draken n'est pas un château : c'est une école. Quatre bâtiments bas autour d'une cour de terre battue, deux cents élèves, et un mur d'ossements catalogués.",
    { sobre:"Charles de Mont-Draken a obtenu sa commission.",
      intense:"Charles de Mont-Draken a obtenu du conseil de province une commission sur les manifestations de l'Onde. Elle lui a été accordée à onze voix contre quatre.",
      extreme:"Charles de Mont-Draken a obtenu du conseil de province une commission d'enquête sur les manifestations de l'Onde en territoire humain. Onze voix contre quatre. Il l'avait demandée trois fois en huit ans ; ce qui a changé, c'est qu'il y a désormais une maison neuve dans les Marches Grises dont on ne sait pas d'où elle sort, et que onze conseillers ont trouvé la coïncidence intéressante." },
    "Il vous reçoit dans la cour, debout, pendant que deux cents élèves travaillent à quarante pas.",
    "« Vous savez ce qu'est cette commission ? »",
    "« Un dossier sur moi. »",
    { sobre:"« Non. »",
      intense:"« Non. » Il a l'air agacé. « C'est un registre. Trente ans que je réclame un registre. »",
      extreme:"« Non », dit-il, et il a l'air sincèrement agacé, ce qui vous surprend. « Ce n'est pas un dossier sur vous, messire, et si c'était ça je vous l'aurais dit — je ne mens pas, c'est bien connu, c'est même la seule chose qu'on trouve à me reprocher. C'est un **registre**. Trente ans que je le réclame à quatre conseils successifs. »" },
    "« Un registre de quoi ? »",
    "« De ce qui arrive. » Il désigne le mur d'ossements. « Trois cent onze pièces, messire. Chacune étiquetée : ce que c'était, où, quand, combien de morts, combien de mes élèves. Trois cent onze. Vous savez combien de manifestations de l'Onde sont étiquetées quelque part dans ces provinces ? »",
    "« Aucune. »",
    "« Aucune. Il y en a eu quatre-vingts en trente ans, j'en ai la trace, et pas une n'est écrite nulle part parce que chaque fois quelqu'un a préféré étouffer. » Il se tourne vers vous. « Résultat : quand un enfant de onze ans fait tomber un mur sans le vouloir dans un village de la marche, personne ne sait quoi faire, et le village décide seul. Vous savez ce que décide un village ? »",
    "§ Vous savez ce que décide un village.",
  ],
  choix:[
    { t:"« Et si le registre existait ? »",
      detail:"lui demander ce qu'il en ferait · c'est la seule question qui compte",
      risque:"calculé", va:'cd_registre' },
    { t:"« Vous voulez me faire inscrire. »",
      detail:"aller droit au point · il est venu pour ça",
      risque:"calculé", va:'cd_inscrire' },
    { t:"« Quatre-vingts en trente ans. Combien en ont réchappé ? »",
      detail:"la question qu'un homme qui a été cet enfant-là poserait",
      risque:"dangereux", va:'cd_rechappe' },
  ],
},

cd_registre:{
  qui:'charles',
  titre:"Ce qu'il en ferait",
  texte:[
    "« Et si le registre existait ? Qu'est-ce que vous en feriez ? »",
    { sobre:"« Trois choses. »",
      intense:"« Trois choses, et je les ai écrites il y a onze ans dans un mémoire que personne n'a lu. »",
      extreme:"« Trois choses. Je les ai écrites il y a onze ans dans un mémoire de quarante-deux pages que j'ai fait porter à quatre conseils et que personne n'a jamais lu — j'ai vérifié : les exemplaires sont revenus non coupés. »" },
    "**Une.** « Une déclaration obligatoire, sans peine attachée. On déclare, il ne se passe rien. C'est tout le mémoire : *il ne se passe rien*. Un registre où l'inscription coûte quelque chose est un registre vide. »",
    "**Deux.** « Une école. Pas ici — ailleurs, tenue par des gens qui en ont. On ne forme pas un enfant à ne pas faire tomber les murs en lui expliquant que les murs ne doivent pas tomber. »",
    "**Trois.** « Et l'interdiction, sous peine capitale, de régler un cas par le village. »",
    "§ Vous mettez un moment à comprendre ce que vous venez d'entendre.",
    "« Vous voulez protéger les enfants de l'Onde. »",
    { sobre:"« Je veux protéger les hommes. »",
      intense:"« Je veux protéger les hommes de ce qui n'en est pas, et je n'ai jamais dit autre chose. » Il vous regarde. « Simplement, un enfant de onze ans qui fait tomber un mur en est un. C'est même toute la difficulté de ma vie. »",
      extreme:"« Je veux protéger les hommes de ce qui n'en est pas. Je n'ai jamais dit autre chose, je ne le dirai jamais autrement, et trois cent onze pièces sur ce mur disent que j'ai raison de le vouloir. » Il vous regarde longuement. « Simplement : un enfant de onze ans qui fait tomber un mur sans le vouloir en est un. Un homme de trente ans qui pousse quatre adversaires à distance dans une crypte en est un aussi, probablement. C'est toute la difficulté de ma vie, messire, et je la traîne depuis trente ans sans que personne ne m'ait jamais aidé à la porter, parce que les deux camps trouvent plus confortable que je sois un boucher. »" },
    "« Combien d'enfants avez-vous fait pendre ? »",
    "« Deux. » Il ne cille pas. « Il y a dix-neuf et vingt-deux ans. Les deux étaient au-delà de ce que je pouvais faire et je le pense encore. Je me trompe peut-être sur le second. »",
  ],
  effets:{ flags:['cd_registre','a2_charles_respect','a2_charles_vu'],
           faire:() => retenir('charles', "il m'a demandé ce que je ferais du registre, ce que personne n'a demandé en trente ans"),
           marque:"Déclaration sans peine, une école, et l'interdiction de régler un cas par le village. Il a fait pendre deux enfants et doute du second.",
           court:"Le mémoire" },
  suite:'cd_epreuve', libelleSuite:"Il propose autre chose" },

cd_inscrire:{
  qui:'charles',
  titre:"Le premier nom",
  texte:[
    "« Vous voulez me faire inscrire. »",
    "« Oui. »",
    "Pas d'hésitation, pas d'enrobage.",
    { sobre:"« Vous ne le nierez pas ? »",
      intense:"« Vous ne prenez même pas la peine de le nier ? »\n\n« Nier quoi ? Je vous demande de vous inscrire à un registre. Si vous n'avez rien à inscrire, la démarche est ridicule et vous rirez. »",
      extreme:"« Vous ne prenez même pas la peine de nier ce que ça suppose ? »\n\n« Nier quoi ? » Il paraît sincèrement dérouté. « Je vous demande de vous inscrire à un registre de déclaration. Si vous n'avez rien à y déclarer, la démarche est ridicule, vous en rirez avec moi et nous parlerons d'autre chose — j'ai deux vallées à tenir et vous êtes en travers de l'une des deux, ce qui nous fera un sujet. Je ne suis pas en train de vous tendre un piège, messire. Je n'en ai jamais tendu un seul de ma vie et c'est la raison pour laquelle je n'ai obtenu ma commission qu'au bout de huit ans. »" },
    "« Le premier nom d'un registre est une cible. »",
    "« Le premier nom d'un registre est celui dont on se sert pour convaincre le deuxième. » Il croise les bras. « Oui, c'est dangereux. Oui, je vous le demande quand même, parce que j'ai quatre-vingts cas en trente ans, aucune inscription, et que quelqu'un doit être le premier ou il n'y en aura jamais. »",
    "§ Il ajoute, et c'est ce qui rend l'homme difficile à détester :",
    "« Si vous refusez, il ne se passera rien. Je n'ai pas le pouvoir de vous contraindre et je ne le demanderai pas : un registre obtenu par contrainte est un registre de dénonciations, et j'en ai vu un, une fois, dans le sud. Je préfère mourir sans mon registre. »",
  ],
  effets:{ flags:['cd_demande','a2_charles_vu'],
           marque:"Il vous demande d'être le premier nom de son registre. Si vous refusez, il ne se passera rien.",
           court:"Le premier nom" },
  choix:[
    { t:"S'inscrire",
      detail:"le premier nom d'un registre de province · en toutes lettres, volontairement",
      risque:"définitif", ferme:"Ferme : le fait qu'on ne sache pas",
      definitif:true, va:'cd_inscrit' },
    { t:"Refuser",
      detail:"il a dit qu'il ne se passerait rien · et il ne ment pas",
      risque:"calculé", va:'cd_refus' },
    { t:"« Inscrivez-en un autre d'abord. »",
      detail:"proposer quelqu'un · il y a quarante et une personnes que vous ne trahirez pas",
      risque:"dangereux", va:'cd_autre' },
  ],
},

cd_rechappe:{
  qui:'charles',
  titre:"Quatre-vingts",
  texte:[
    "« Quatre-vingts cas en trente ans. Combien en ont réchappé ? »",
    { sobre:"Il ne répond pas tout de suite.",
      intense:"Il ne répond pas tout de suite, et c'est la première fois. Il regarde les deux cents élèves à quarante pas.",
      extreme:"Il ne répond pas tout de suite. C'est la première fois de l'entretien, et probablement la première fois qu'on lui pose cette question dans cet ordre-là — pas *combien en avez-vous tué*, qu'on lui a demandée cent fois et à laquelle il a une réponse toute faite : *combien en ont réchappé*. Il regarde ses deux cents élèves travailler à quarante pas." },
    "« Onze. »",
    "« Sur quatre-vingts. »",
    "« Sur quatre-vingts. » Il ne détourne pas les yeux. « Neuf ont été tués par leur propre village avant que quiconque arrive. Quarante et un se sont enfuis et je ne sais pas ce qu'ils sont devenus — statistiquement, la plupart sont morts, mais je n'en ai pas la trace et je ne les compte pas parmi les morts. Dix-neuf ont été exécutés régulièrement, dont deux par moi. »",
    "« Et les onze ? »",
    { sobre:"« Ils vivent. »",
      intense:"« Ils vivent. Sous d'autres noms, dans d'autres provinces, et huit d'entre eux ne savent pas que c'est moi qui les ai fait sortir. »",
      extreme:"« Ils vivent. Sous d'autres noms, dans d'autres provinces, avec des métiers ordinaires. Huit d'entre eux ne savent pas que c'est moi qui les ai fait sortir : on ne le leur a jamais dit et je n'ai pas l'intention qu'on le leur dise. Les trois autres le savent, et sur les trois, deux me haïssent — ce que je comprends parfaitement, puisque dans les deux cas j'étais venu pour les tuer et que j'ai changé d'avis sur place. On ne pardonne pas ça. »" },
    "§ Onze sur quatre-vingts, et c'est le meilleur chiffre que ces provinces aient jamais produit.",
    "« Vous n'avez jamais écrit ces onze-là nulle part. »",
    "« Bien sûr que non. » Il vous regarde enfin. « C'est très exactement pour ça qu'il me faut un registre où l'inscription ne coûte rien : pour n'avoir plus jamais à faire sortir quelqu'un en cachette de mes propres élèves. »",
  ],
  effets:{ flags:['cd_onze','a2_charles_respect','a2_charles_vu','a2_charles_onze'],
           faire:() => { bouger('alycia', { relation:1 });
                         retenir('charles', "il m'a demandé combien en avaient réchappé, et personne ne demande jamais ça"); },
           exploit:{ eclat:3, temoins:'un', quoi:"vous avez posé à Mont-Draken la question qu'on ne lui pose pas" },
           marque:"Onze sur quatre-vingts ont réchappé. Huit ne savent pas que c'est lui qui les a fait sortir.",
           court:"Onze sur quatre-vingts" },
  suite:'cd_inscrire', libelleSuite:"Il en vient à ce qu'il veut" },

cd_inscrit:{
  qui:'charles',
  titre:"Le registre de la commission, folio un",
  texte:[
    "Le registre est un volume neuf, relié de basane, sans une écriture dedans.",
    { sobre:"Vous écrivez la première ligne vous-même.",
      intense:"Il ne l'écrit pas pour vous. Il vous tend la plume, ce qui est le seul geste de toute cette affaire dont vous vous souviendrez avec précision quinze ans plus tard.",
      extreme:"Il ne l'écrit pas pour vous, ce qu'un commissaire de province ferait normalement — c'est lui qui tient le registre, c'est son écriture qui fait foi. Il vous tend la plume à l'envers, par le calame, et il attend. C'est le seul geste de toute cette affaire dont vous vous souviendrez avec précision quinze ans plus tard, et vous ne saurez jamais s'il l'a fait exprès." },
    "*Yohan de Karlsberg. Marches Grises. Déclaré volontairement, sans contrainte, sans peine encourue.*",
    "§ Vous signez. Il contresigne. Deux témoins contresignent : un maître d'armes de l'école et un clerc du conseil.",
    "Et il ne se passe rien.",
    { sobre:"Absolument rien. C'était tout l'objet.",
      intense:"Absolument rien. Vous ressortez par la cour, vous reprenez votre cheval, personne ne vous suit. C'était tout l'objet du mémoire de quarante-deux pages que personne n'avait lu.",
      extreme:"Absolument rien. Vous ressortez par la cour d'exercice, vous reprenez votre cheval à l'écurie, et deux cents élèves continuent de travailler à quarante pas sans lever la tête. Personne ne vous suit, personne ne vous escorte, personne ne consigne votre départ. C'était très précisément l'objet du mémoire de quarante-deux pages que quatre conseils avaient renvoyé non coupé : *on déclare, il ne se passe rien*." },
    "Charles vous rattrape à la porte de l'école.",
    "« Vous mesurez ce que vous venez de faire ? »",
    "« Je crois. »",
    "« Non. » Il pose la main sur le chambranle. « Il y a quarante et un de vos semblables dans ces provinces qui vivent cachés, et à partir de ce soir il en existe un qui vit inscrit. C'est la première fois en trois cents ans. Je ne sais pas si ça finira bien. Je sais que ça n'avait jamais été essayé. »",
  ],
  effets:{ flags:['cd_inscrit','a2_declare','a2_charles_allie','a2_registre_onde'], suspicion:35,
           faire:() => { bouger('alycia', { confiance:-4, peur:2 });
                         retenir('charles', "il s'est inscrit de sa main, le premier, et il n'y était pas obligé");
                         retenir('caleb', "il a déclaré ce qu'il est à un registre de province, ce qui change son prix");
                         retenir('alycia', "il s'est fait inscrire à un registre — je n'ai pas été consultée"); },
           exploit:{ eclat:24, temoins:'province', quoi:"le premier nom du registre de l'Onde, écrit de sa main" },
           marque:"Premier nom du registre de la commission, écrit de votre main. Il ne s'est rien passé. C'était l'objet.",
           court:"Folio un" },
  plusTard:"Quarante et un vivent cachés. Il en existe désormais un qui vit inscrit, et personne ne sait comment ça finit.",
  suite:'a2_carte', libelleSuite:"La carte" },

cd_refus:{
  qui:'charles',
  titre:"Rien",
  texte:[
    "« Non. »",
    "« Bien », dit Charles de Mont-Draken.",
    { sobre:"Et il ne se passe rien non plus.",
      intense:"Et il ne se passe rien non plus, ce qui est le point : il avait dit qu'il ne se passerait rien, et il ne se passe rien.",
      extreme:"Et il ne se passe rien non plus. C'est très exactement le point, et il faut un moment pour le voir : il avait dit qu'il ne se passerait rien si vous refusiez, et il ne se passe rien. Pas de menace voilée, pas de « réfléchissez », pas d'homme sur la route trois jours plus tard. Cet homme fait ce qu'il dit, dans les deux sens, et c'est ce qui le rend beaucoup plus dangereux que s'il mentait." },
    "Il vous raccompagne aux écuries et parle de la vallée haute, des loups qui redescendent, d'un pont à refaire.",
    "Sur le seuil : « Je vous le redemanderai. »",
    "« Je sais. »",
    "« Pas cette année. Peut-être pas dans dix ans. » Il hausse une épaule. « J'ai soixante et un ans, messire, et le registre est vide. Il le sera probablement à ma mort. C'est comme ça. Trois cent onze pièces sur ce mur, et la seule chose que je n'aurai pas obtenue, c'est un cahier. »",
    "§ Vous partez sans être inscrit, sans être menacé, et avec le désagrément durable d'avoir refusé quelque chose de raisonnable à quelqu'un de raisonnable.",
  ],
  effets:{ flags:['cd_refus','a2_charles_vu','a2_charles_attend'],
           faire:() => { bouger('alycia', { confiance:2 });
                         retenir('charles', "il a refusé le registre et je le lui redemanderai"); },
           marque:"Vous avez refusé. Il ne s'est rien passé, exactement comme il l'avait dit. Il le redemandera.",
           court:"Le cahier vide" },
  suite:'a2_carte', libelleSuite:"La carte" },

cd_autre:{
  qui:'charles',
  titre:"Quelqu'un d'autre",
  texte:[
    "« Inscrivez-en un autre d'abord. »",
    { sobre:"Il se raidit.",
      intense:"Il se raidit — la première réaction physique de tout l'entretien — et sa voix change.",
      extreme:"Il se raidit, et c'est la première réaction physique de tout l'entretien : les épaules, la mâchoire, une seconde entière. Sa voix change de registre quand elle revient, et elle descend au lieu de monter, ce qui chez un homme de cette sorte est nettement plus inquiétant." },
    "« Vous venez de me proposer de dénoncer quelqu'un. »",
    "« J'ai dit *inscrivez*. »",
    "« Vous avez dit : *prenez-en un autre à ma place*. » Il vous coupe d'un geste. « Non, messire. Ne recommencez pas. Vous savez exactement ce que vous avez dit et moi aussi. »",
    "§ Il n'est pas offensé pour lui. Il est offensé pour le registre.",
    "« Le premier nom d'un registre de déclaration volontaire doit être volontaire, sinon ce n'est pas un registre de déclaration : c'est une liste, et il y en a déjà onze qui circulent dans cette province avec sept noms barrés dessus. » Il reprend le volume. « Vous en connaissez au moins une. »",
    "« Oui. »",
    "« Alors vous savez ce que je refuse de fabriquer. »",
    "Il range le registre neuf dans une armoire, et vous entendez la clef.",
  ],
  effets:{ flags:['cd_denonce','a2_charles_froid','a2_charles_vu'],
           faire:() => { bouger('alycia', { confiance:-3 });
                         retenir('charles', "il m'a proposé quelqu'un d'autre à sa place, ce que je n'oublierai pas"); },
           marque:"Vous avez proposé quelqu'un d'autre. Il a rangé le registre neuf et vous avez entendu la clef.",
           court:"La clef" },
  suite:'a2_carte', libelleSuite:"La carte" },

cd_epreuve:{
  qui:'charles',
  lieu:"Mont-Draken · la vallée haute",
  titre:"Ce qu'il y a dans la vallée haute",
  texte:[
    "« Avant que je vous demande quoi que ce soit », dit Charles, « il y a une chose dans la vallée haute et j'y vais demain. Venez. »",
    "« C'est une épreuve. »",
    { sobre:"« Oui. Évidemment. »",
      intense:"« Oui, évidemment. » Il n'a pas l'air de comprendre pourquoi on le souligne. « Je ne vais pas décider de ce que vous êtes d'après une conversation dans une cour. »",
      extreme:"« Oui, évidemment. » Il n'a pas l'air de comprendre pourquoi on prend la peine de le souligner. « Je ne vais pas décider de ce que vous êtes d'après une conversation dans une cour d'exercice — vous êtes manifestement intelligent, ce qui est précisément la raison de ne pas vous croire sur parole. Je vais vous regarder faire quelque chose de difficile à côté de gens à moi. C'est la seule méthode que je connaisse et elle ne m'a jamais trompé. »" },
    "§ Dans la vallée haute, il y a une chose qui a vidé deux granges et un hameau de neuf feux, et qui n'a laissé aucun corps.",
    "Ce n'est pas un loup, ce n'est pas un ours, et ce n'est pas humain : Charles a une empreinte moulée dans du plâtre et il ne sait pas ce que c'est, ce qui n'était pas arrivé depuis onze ans.",
    "« Trois cent onze pièces au mur », dit-il en la posant sur la table. « Aucune ne correspond. »",
    "Vous montez à quatre : lui, vous, et deux de ses élèves de dernière année — un garçon de dix-neuf ans, une fille de vingt-deux.",
  ],
  melee:{ eux:1, position:"vallée haute · trois pieds de neige", pression:"aucune trace, aucun corps" },
  choix:[
    { t:"Chasser à sa méthode",
      detail:"relevés, battue, cinq jours · c'est ce qu'il est venu regarder",
      risque:"calculé", va:'cd_methode' },
    { t:"Employer l'Onde devant lui",
      detail:"devant Charles de Mont-Draken et deux de ses élèves · définitif",
      risque:"définitif", ferme:"Ferme : le doute qu'il entretenait poliment",
      definitif:true, va:'cd_onde' },
    { t:"Envoyer les élèves devant",
      detail:"c'est leur dernière année · et c'est ce qu'un capitaine ferait",
      risque:"dangereux", va:'cd_eleves' },
  ],
},

cd_methode:{
  qui:'charles',
  titre:"Cinq jours",
  texte:[
    "Cinq jours de relevés dans trois pieds de neige.",
    { sobre:"Sa méthode est lente et elle marche.",
      intense:"Sa méthode est d'une lenteur exaspérante et elle marche : on ne cherche pas la bête, on cartographie ce qu'elle évite. Une chose qui évite l'eau vive et les crêtes exposées se trouve toute seule au bout de cinq jours.",
      extreme:"Sa méthode est d'une lenteur exaspérante et elle fonctionne parfaitement. On ne cherche jamais la bête : on cartographie ce qu'elle évite. Cinq jours de relevés — l'eau vive, les crêtes exposées au vent, les fermes où il y a des chiens, les deux versants qu'elle n'a jamais franchis. Au soir du cinquième, il reste sur la carte une poche de deux cents arpents où la chose peut être, et elle y est, parce qu'elle n'a nulle part ailleurs où aller." },
    "Ce qui est dedans mesure sept pieds, se déplace à quatre pattes et se dresse pour frapper, et n'a de nom dans aucune langue de ces provinces.",
    "§ Ça tombe en onze minutes, à quatre, sans qu'aucun des quatre soit blessé sérieusement, parce qu'on savait où c'était et qu'on est arrivés dans le bon sens.",
    "La fille de vingt-deux ans porte le coup qui la tue. Le garçon de dix-neuf tient la lanterne, ce qui est le poste dangereux, et il ne la lâche pas.",
    "Charles ne dit rien pendant la descente.",
    "Le soir, à l'école, devant le mur d'ossements, il désigne un emplacement vide.",
    "« Trois cent douzième pièce. » Il écrit l'étiquette lui-même. « Vallée haute. Onze morts. Quatre chasseurs, aucun perdu. »",
    "Il ajoute votre nom sur l'étiquette, entre celui de ses deux élèves, sans commentaire et sans vous regarder.",
  ],
  effets:{ flags:['cd_methode','a2_charles_allie','a2_charles_respect'],
           cout:{ endurance:18 },
           exploit:{ eclat:11, temoins:'quelques', quoi:"la trois cent douzième pièce du mur de Mont-Draken" },
           faire:() => { retenir('charles', "il a chassé cinq jours à ma méthode sans se plaindre et il a laissé la fille frapper"); },
           marque:"Trois cent douzième pièce au mur de Mont-Draken. Votre nom sur l'étiquette, entre ses deux élèves.",
           court:"La 312ᵉ" },
  suite:'cd_inscrire', libelleSuite:"Il en vient à ce qu'il veut" },

cd_onde:{
  qui:'charles',
  titre:"Devant lui",
  texte:[
    "La chose sort du couvert à onze pas de la fille de vingt-deux ans, qui est à contre-pente et qui ne la voit pas.",
    { sobre:"Vous n'avez pas le temps de décider.",
      intense:"Il n'y a pas de décision. Il y a onze pas, une élève de vingt-deux ans à contre-pente, et un corps qui fait ce qu'il sait faire avant que la tête ait un avis.",
      extreme:"Il n'y a pas de décision, et c'est important de le dire exactement : il y a onze pas, une jeune femme de vingt-deux ans à contre-pente qui regarde ailleurs, une chose de sept pieds qui se dresse, et un corps qui fait ce qu'il sait faire quatre bonnes secondes avant que la tête ait le moindre avis sur la question. On peut appeler ça du courage. Ce n'en est pas. C'est de la mécanique, et vous vous êtes construit cette mécanique-là exprès, il y a onze ans, parce que le contraire vous aurait tué." },
    "§ La chose part en arrière de quatre pieds, à plat, comme frappée par un chariot qui n'existe pas.",
    "Elle se relève. Elle est reprise, de côté cette fois, contre un rocher. Le bruit n'est pas un bruit d'os : c'est un bruit de charge, sourd, très bas, qu'on sent dans le sternum à quinze pas.",
    "La fille se retourne enfin. Le garçon a lâché la lanterne.",
    "Charles de Mont-Draken n'a pas bougé du tout.",
    { sobre:"Il regarde. C'est son métier.",
      intense:"Il regarde, très attentivement, jusqu'au bout, et il ne dégaine pas — ce qui, pour un homme qui a passé trente ans à faire exactement le contraire, est un effort qu'on ne mesure pas.",
      extreme:"Il regarde. Très attentivement, jusqu'au bout, sans dégainer, sans un mouvement vers ses deux élèves, sans un mot. Pour un homme qui a consacré trente ans de sa vie à mettre des choses non humaines à terre dès qu'elles se manifestent, et qui a fait pendre deux enfants, l'effort que représente cette immobilité-là ne se mesure pas. Il vous regardera plus tard, mais pas tout de suite : d'abord il regarde ce que vous faites, en professionnel, jusqu'à la fin." },
    "Quand c'est fini, il s'approche du corps, pas de vous, et il l'examine pendant une demi-heure.",
    "Puis, sans se relever : « Les côtes sont enfoncées sur toute la ligne, régulièrement. Ce n'est pas un coup. C'est une pression. »",
    "« Oui. »",
    "« Vous pouvez faire ça à un homme. »",
    "« Oui. »",
    "§ Il se relève. Ses deux élèves sont à dix pas et ils ne savent pas où se mettre.",
    "« Bien », dit Charles. « Maintenant je sais, et vous savez que je sais, et il va falloir décider tous les deux ce qu'on en fait. Je propose qu'on descende d'abord, parce que la nuit tombe et que ma fille a froid. »",
    "Vous mettez trois secondes à comprendre que la fille de vingt-deux ans est sa fille.",
  ],
  effets:{ flags:['cd_onde','a2_montdraken_certain','a2_onde_publique','a2_charles_sait'], suspicion:30,
           cout:{ concentration:24 },
           exploit:{ eclat:14, temoins:'quelques', quoi:"l'Onde employée devant Mont-Draken et ses deux élèves" },
           faire:() => { retenir('charles', "il a sauvé ma fille avec ça, sous mes yeux, et je l'ai regardé faire");
                         bouger('alycia', { peur:3 }); },
           marque:"Vous avez employé l'Onde devant Charles de Mont-Draken pour sauver sa fille. Il a regardé jusqu'au bout sans dégainer.",
           court:"Sa fille" },
  plusTard:"Il sait. Ses deux élèves aussi. L'un des trois parlera, et ce ne sera pas lui.",
  suite:'cd_inscrire', libelleSuite:"Il en vient à ce qu'il veut" },

cd_eleves:{
  qui:'charles',
  titre:"Dernière année",
  texte:[
    "« Envoyez-les devant. C'est leur dernière année. »",
    { sobre:"Charles accepte.",
      intense:"Charles accepte sans discuter, ce qui vous surprend, et vous comprenez pourquoi trois heures plus tard.",
      extreme:"Charles accepte sans discuter une seconde, ce qui vous surprend assez pour que vous le regardiez deux fois. Vous comprendrez pourquoi trois heures plus tard, et ce sera désagréable." },
    "Ils entrent dans le couvert les premiers. Ils font tout correctement — l'écart, l'angle, la lanterne basse — parce qu'ils ont été formés par le meilleur des quatre provinces.",
    "§ Ça ne suffit pas. Ça ne suffit jamais la première fois.",
    "Le garçon de dix-neuf ans prend le coup au flanc gauche et il est à terre en une seconde et demie.",
    "Il faut trois hommes pour finir ce qu'il avait commencé, et ça se passe bien parce qu'il l'avait effectivement commencé : la chose est déjà touchée quand vous arrivez, à la jointure, exactement où on lui a appris.",
    "Il vit. Il vivra. Il ne se servira plus de son bras gauche.",
    "Charles le panse lui-même dans la neige, sans se presser, en parlant d'autre chose.",
    "Puis, plus tard, devant le feu, sans reproche dans la voix :",
    { sobre:"« Vous avez fait ce qu'un capitaine fait. »",
      intense:"« Vous avez fait exactement ce qu'un capitaine fait, et c'était le bon ordre. » Il regarde le garçon dormir. « Je l'ai accepté parce que c'était le bon ordre. »",
      extreme:"« Vous avez fait exactement ce qu'un capitaine fait, et c'était le bon ordre, et je l'ai accepté pour cette raison. » Il regarde le garçon dormir de l'autre côté du feu. « Un homme de trente ans qui vaut quatre hommes ne passe pas devant : il passe en second, il voit ce qui se passe et il décide. C'est de la tactique élémentaire et je l'enseigne moi-même le mardi. »" },
    "« Mais ? »",
    "« Mais je le fais depuis trente ans et je passe toujours devant. » Il tisonne. « C'est mauvais, ça coûte des hommes, et j'ai tort. Voilà. Vous avez raison et j'ai tort, et son bras gauche ne remarchera pas. »",
    "§ Il ne vous accuse de rien. C'est infiniment pire.",
  ],
  effets:{ flags:['cd_eleve_blesse','a2_charles_froid','a2_charles_vu'],
           exploit:{ eclat:6, temoins:'quelques', quoi:"la chose de la vallée haute est morte" },
           faire:() => retenir('charles', "il a envoyé mes élèves devant, ce qui était le bon ordre, et le garçon a perdu son bras"),
           marque:"Le garçon de dix-neuf ans ne se servira plus de son bras gauche. C'était le bon ordre et Charles l'a dit.",
           court:"Le bras gauche" },
  plusTard:"« Vous avez raison et j'ai tort, et son bras gauche ne remarchera pas. »",
  suite:'cd_inscrire', libelleSuite:"Il en vient à ce qu'il veut" },

};

enregistrerScenes(POLITIQUE);

/* ── Où ces trois hommes se trouvent ──────────────────────────────────────
 * Chacun s'ouvre sur ce que le chantier a fait de vous : Caleb quand vous
 * commencez à consommer de la province, Lucius quand vous avez un titre à
 * faire valoir, Charles quand ce que vous êtes devient une question. */
offrir({ id:'cb_creances', lieu:'fortauxprinces', va:'cb_creances',
         titre:"L'état de vos fournisseurs",
         si:() => a('ca_vu') && CHANTIER().faits.length >= 2 });

offrir({ id:'ls_legitimation', lieu:'astrah', va:'ls_legitimation',
         titre:"La salle des rôles",
         si:() => a('a2_lucius_vu') && (a('a2_bannieres') || CHANTIER().faits.length >= 3) });

offrir({ id:'cd_commission', lieu:'montdraken', va:'cd_commission',
         titre:"La commission sur l'Onde",
         si:() => (a('a2_charles_vu') || a('ch_avoue') || a('ch_nie') || a('ch_esquive') || a('ch_trois_cent_onze'))
               && !a('cd_registre') && !a('cd_demande') });
